### ISSUE TITLE
New item: Cube that can be frozen in place

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1123]
New item: Cube that can be frozen in place

a cube that defies physics and would use some external trigger like a button to make it remain frozen in place where ever it is. could be pushed into a wall button by a funnel and then activated, when the funnel is turned off, the cube keeps the button pressed down. 

how would this be created in hammer (the cube, making it freeze in place)

could create some really interesting puzzles

**Comment by Luke18033** [comment]
BEE2.2 had something kind of like this, but it was activated by firing a portal at it, not by inputs. This would probably be possible to implement.

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033, or @LautaroL20, or @TeamSpen210   also how do i assign my own labels to new topics?

**Comment by Byzarru** [comment]
Something like this: http://steamcommunity.com/sharedfiles/filedetails/?id=675500707

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum You need to be a collaborator to add labels.

**Comment by TheDarkBomber** [comment]
This is possible. A great name for it would be a "Suspension Cube", because it suspends in air. A prop_physics can do this, however, only prop_weighted_cubes and players can activate cube buttons. Maybe parent a prop_weighted_cube to a prop_physics. All that needs to be done then is set the model of the prop_physics to a standard cube model and make the prop_weighted_cube non-tangible and invisible.

**Comment by Jadeygaming** [comment]
This used to be a PUNT cube I believe.

**Comment by Luke18033** [comment]
@Jadeygaming Punt Cubes were slightly different. They would freeze in place when clicked on, but this would freeze in place when activated by inputs. Both should be implemented as separate items.

**Comment by Konclan** [comment]
UCP
