### ISSUE TITLE
Rocket Turret rockets are invisible/extremely offset

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1238]
Moved from the BenVlodgi´s section: https://github.com/BEEmod/BEE2.4/issues/287

Roket turret isn´t working well, it moves too slow when the player walks around.

- There seems to be a nodraw surrounding the rocket turret; you cannot stand on top of it when deactivated.
- Rockets do not appear.

**Comment by Byzarru** [comment]
Additionally:
- There seems to be a nodraw surrounding the rocket turret; you cannot stand on top of it when deactivated.
- Rockets do not appear.

**Comment by ZombiePwner1** [comment]
@Byzarru The rocket turret is very bugged right now.

**Comment by LautaroL20** [comment]
Ty, added to the post´s description.

**Comment by Luke18033** [comment]
There's no way to fix the rotation speed, it's hardcoded into the entity as far as I know.

**Comment by Luke18033** [comment]
I've been looking into the invisible rockets issue. It's specific to maps - a map that I compile (with BEE or Hammer) doesn't have the issue, but any map I downloaded off the workshop does. I'm going to decompile one of those maps, compare it to my own, and see if I can figure anything out.

**Comment by Luke18033** [comment]
Okay, I figured it out. The rockets aren't actually invisible, they're just offset 2400 units forward from the correct position (usually ending up outside the map, this can be seen with `ent_text`). The reason that happens is because the `rocket_turret_projectile` entity isn't in the default FGD, so VBSP doesn't know what to do with the replacement rocket and places it at the map origin, 2400 units away from the `point_template`. TeamSpen's Hammer Addons fix this, so maps compiled with them installed wouldn't be affected (hence why TeamSpen and I could never replicate the bug).

This was accidentally fixed for the next release - the script now applies forces and attaches triggers directly to existing rockets instead of spawning in new ones, so this can't happen. Either way, I'm happy to say that the mystery of the invisible rockets has finally been solved.

Now to fix the collisions...

**Comment by FrozenDragon0** [comment]
@Luke18033 Finally! Been waiting to use the rocket turret forever. About time this bug is fixed. Hopefully no more issues occur aside from the laser beam tripwire being slightly bugged.
