### ISSUE TITLE
Extended Relaxation Vault

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1245]
Moved from the BenVlodgi´s section: https://github.com/BEEmod/BEE2.4/issues/32

Original post by: @ellingtonvengaboysmuseum:

"since choosable entry and exit elevators will be done by style. why not add the extended relaxation vault as a level start type choice with different variants depending on the style. this would be used to introduce you to a story if you created a long series of tests in PTI.
- for 50's underground style, have the ERV be replaced by a train bringing you into aperture (as seen in portal stories mel)
- for overgrown, make it an overgrown relaxation vault with the announcer voice.
- for clean, regular vault with GLaDOS or multiverse cave introducing you.
- for Wheatley, clean but with a Wheatley style test chamber with Wheatley greeting you."

--------------------------------------------------------------------------------------------

Some suggestions by @Byzarru:

- ERV should be a stylevar option, replacing the elevator.
- There should be several ERV layouts (One room with sign, two room with sign, etc). Possibly link to corridor options.
- Modern Old Aperture's ERV should be a stasis chamber (see [Portal 2: Repercussions](https://www.youtube.com/watch?v=yms0qNRJCi8) by Lemurr or [Oxygen Station](http://steamcommunity.com/sharedfiles/filedetails/?id=269845529) by josepezdj). The plot would be that the test subject is being awakened in the modern day amidst the ruins of Old Aperture. The test subject would leave the chamber, walk through some catwalks, and enter an Enrichment Sphere before starting the test.
- BTS and P1 BTS should start sleeping at a chair in an office.
- Underground BTS should use the above idea with the stasis chambers.
- The train ride should only be an option for Prime 1950s (That is the name I am trying to push for the style). Player starts on a tram that brings them to a lobby, similar to the ruined lobby in Portal 2. They proceed to an enrichment sphere before starting the test.

**Comment by Byzarru** [comment]
My own notes:
- ERV should be a stylevar option, replacing the elevator.
- There should be several ERV layouts (One room with sign, two room with sign, etc).
- Modern Old Aperture's ERV should be a stasis chamber (see [Portal 2: Repercussions](https://www.youtube.com/watch?v=yms0qNRJCi8) by Lemurr or [Oxygen Station](http://steamcommunity.com/sharedfiles/filedetails/?id=269845529) by josepezdj). The plot would be that the test subject is being awakened in the modern day amidst the ruins of Old Aperture. The test subject would leave the chamber, walk through some catwalks, and enter an Enrichment Sphere before starting the test.
- BTS and P1 BTS should start sleeping at a chair in an office.
- Underground BTS should use the above idea with the stasis chambers.
- The train ride should only be an option for Prime 1950s (That is the name I am trying to push for the style). Player starts on a tram that brings them to a lobby, similar to the ruined lobby in Portal 2. They proceed to an enrichment sphere before starting the test.

**Comment by Byzarru** [comment]
There's already been a suggestion to make entry/exit doors available on the floor, but ERVs would work best as an alternative to the elevator (there's no equivalent in Old Aperture and the idea with the train and the ideas I brought up wouldn't work if I'm correct in assuming how ellington thinks the ERV would work). Floor/Ceiling entries should use lifts, Aerial Faith Plates, or Excursion Funnels but otherwise work as their regular counterparts.

**Comment by LautaroL20** [comment]
@Byzarru - I have included your notes inside the post´s description.

**Comment by TeamSpen210** [comment]
I've made the Clean entrances and exits, they use lifts to push you in and seal up the chamber.

**Comment by Luke18033** [comment]
@Byzarru The ERV shouldn't be an entry replacement, then you can't customize what's around it.

**Comment by Byzarru** [comment]
An ERV in a box only belongs in P1, Clean, and Overgrown. They'd be total anachronisms in Old Aperture, prompting the ideas that ellington and I have proposed. There could be a stretch for BTS, like an employee lounge. If you need to make space to build customize an area around the ERV, it takes up space that could otherwise be used for the puzzle (in a potentially extreme case, but I've hit this problem often in trying to make a BTS map look like a proper maintenance area while only using BEE). Also, using an ERV as a replacement to the elevator essentially changes nothing in terms of map layout, both in terms of how items are placed and how the map itself is navigated.

**Comment by Luke18033** [comment]
Not really necessary, it just encourages story maps, and seeing the same relaxation vault layout over and over in different maps would just get old.
