### ISSUE TITLE
Add handle_ 8_positions to the invisible logic items.

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1446]
The purpose, of course, would be to add another whole level of ability for antline manipulation.  Yes, I've tried it and it works beautifully except the grip is really hard to grab (need to rotate so there is a wall in the way to grab the grip).  Maybe make the item a strip instead of a full voxel square.  The AND gate especially gives a LOT of extra options for antline layout and giving it the 8 positions would be a major improvement.

**Comment by LautaroL20** [comment]
Thats exactly what the Antline Magnet does.

**Comment by LautaroL20** [comment]
"Maybe make the item a strip instead of a full voxel square." And thats exactly what the actual Antline Manget does.

**Comment by TeamSpen210** [comment]
But it's useful to have on the logic gates as well. The magnet also has some specific antline coordinates.

**Comment by libbybapa** [comment]
Lautaro, it is *not* what an antline magnet does.  Antline magnets are slightly useful.  AND logic gates are far more useful for specific antline manipulations, e.g. branching antlines.  Do you need some screenshots in order to understand the usefulness of what I'm asking for?

I was playing with the handle_8_positions and the connection points.  I'm new to what those do so I might be mistaken, but I think most useful would actually be to make the invisible logic gates 1/2X1/2 voxel in size, give the connection points of a laser relay, and let them handle_8_positions.

**Comment by libbybapa** [comment]
Here's a configuration that is possible with the handle_8_positions and the AND gate.  It is NOT possible with an antline magnet.  Granted it would be better with the corner aperture logos on top of each other.
![20170122152516_1](https://cloud.githubusercontent.com/assets/19520567/22186738/b8e42292-e0b7-11e6-8221-d961f899265a.jpg)

Here's the best you can do with the AND gate without the handle_8_positions:
![20170122152816_1](https://cloud.githubusercontent.com/assets/19520567/22186758/f9c6f6e0-e0b7-11e6-881e-7b72148a18dc.jpg)
It's ok, but I prefer the other version.

Here is the best you can do using an antline magnet: 
![20170122153533_1](https://cloud.githubusercontent.com/assets/19520567/22186774/6f4f5ea2-e0b8-11e6-9db4-72136250372d.jpg)
Also sorta ok, but the first version is the best of the three.  

I think that being able to fine-tune the connection positions is really advantageous.

**Comment by libbybapa** [comment]
I wanted to mention that the Delayer should also have handle_8_positions.  It works fine that way (no other changes necessary) and allows some nice clean antline routing options that are otherwise impossible (not possible even with the router).  Here's an example of a routing that is not possible without being able to move the Delayer:

![20170213075236_1](https://cloud.githubusercontent.com/assets/19520567/22907499/aadcd170-f206-11e6-8580-f059e50e62a9.jpg)

I've been using the invisible logic items with the handle_8_positions and it makes accurate, clean antline routing MUCH easier.  The biggest issue is that the model for the logic items is so large that it covers the grip and makes selection of the grip a real pain.  Usually I need to rotate until a wall is blocking the view in order to move the grip.  

Here is a clean routing possibility that is not possible without moving the logic item: 

![20170213075301_1](https://cloud.githubusercontent.com/assets/19520567/22907620/353d1a14-f207-11e6-9bd5-5a945294d100.jpg)
Being able to move the AND gate allows the small space for the signage between the antline and the conductive plate.  The signs look worse to either side (bad symmetry with the room) and cannot go on the side opposite the conductive plate.

Here's another that was not possible with the antline router and needed the movable AND gate:
![20170213160555_1](https://cloud.githubusercontent.com/assets/19520567/22907940/ea93bd86-f208-11e6-8f9a-21c8fe1a70a2.jpg)

The added functionality is very beneficial.

**Comment by TeamSpen210** [comment]
This is long since implemented, with the strip versions of gates.
