### ISSUE TITLE
Closed Solid Field not making the wall where its placed to become "Grided"

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1521]
_From @LautaroL20 on January 6, 2017 14:30_

![20170106112538_1](https://cloud.githubusercontent.com/assets/12244376/21720621/f51d278e-d402-11e6-82fb-b10aa536630a.jpg)

_Copied from original issue: TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#10_

**Comment by Luke18033** [comment]
The Gridded Wall item can be used for this, but it should still be done automatically.

**Comment by Luke18033** [comment]
Has this been fixed? Custom fizzlers were redesigned at one point, but I'm not sure if that would have affected this at all.

**Comment by LautaroL20** [comment]
I am almost sure that this issue still persist. I don´t know which stuff on custom fizzlers was specifically "redesigned", but i can guess that the compiler´s behavior in this aspect still wasn´t touched because it has not been long since i´ve tested some of these fizzlers.

In order to implement gridded walls in non PeTi fizzlers, Spencer will require to modify the internal configuration of the compiler, since you can´t actually implement such feature by only tunning the config.cfg files of this type of item.

**Comment by Luke18033** [comment]
This will be fixed in the next release.
