### ISSUE TITLE
Decorational Items

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1551]
Do you have an interesting idea for BEE2 that involves an absolutely useless item with no value beyond asthetic?

Put it here!

**Comment by Byzarru** [comment]
It'd probably be best to discuss this on the BEE2.4 thread [here](https://github.com/BEEmod/BEE2.4/issues/414). As far as placeable items, I've already suggested posters and marker overlays (#1096), and more ideas are sure to open up. Each new item should really go in its own issue, rather than be bunched here.

**Comment by TheDarkBomber** [comment]
But for non-placeable items, we have the Decorations Package Object.

**Comment by Luke18033** [comment]
We don't have decorations yet. What's a Package Object?

**Comment by Byzarru** [comment]
It's something TDB made up to make everything more specific and complicated.

**Comment by TeamSpen210** [comment]
Actually that's my internal name for the different things that can be inside a package - items, styles, music, voice lines, etc.
