### ISSUE TITLE
Antlines do not create checkmarks on chamberlocks unless two buttons are connected.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1587]
![20170215164133_1](https://cloud.githubusercontent.com/assets/18079316/22966581/c7df30b8-f39d-11e6-8c0e-129e8a1767ea.jpg)

**Comment by Luke18033** [comment]
That behavior is coded into the exit door item. Place a NOT gate somewhere in the map, and connect that to the chamberlock.

**Comment by TheDarkBomber** [comment]
Or a Laser Gate. (a laser going into a catcher)

**Comment by Luke18033** [comment]
No, use a NOT gate. It's invisible and uses less entities.

**Comment by quat1024** [comment]
Worth noting that you can create those checkmark items on anything you want - not just chamberlocks or anything - by connecting at least two things to it... EVEN IF all but one connection is invisible. I like to use this when I connect an antline to a fizzler josepezdj-style, with an antline that goes to the top/bottom of a fizzler instead of the models on the side of it.

Most things are triggered by all of the connections being on, though, so use a NOT gate like luke said because it's on by default
