### ISSUE TITLE
Rolling back the Dev version

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1605]
So, the current Dev version of BEE2 does NOT like compiling for me for whatever reason,
is there a way to roll back my Dev version to a previous version that I know to work?

**Comment by Luke18033** [comment]
I don't know if that's possible to do in a way that works well, but I've got one idea. In GitHub Desktop, revert the commit that made the problem start. That'll only affect your local copy, since you don't have write access to the online copy. That might cause problems later though, so I wouldn't try it. Check out the [BEE-Development chat](https://gitter.im/BEEmod/BEE-Development) if you want help on developing for BEE or using the dev version.

**Comment by TheDarkBomber** [comment]
If you want to compile with the DEV version, also get the DEV version of the compiler program.

**Comment by TeamSpen210** [comment]
You can indeed checkout older versions, you need to use the command line to do it in Github desktop. Find the commit you want to revert to, and copy down the hash (random alphanumeric characters). Then right click on the repro in the app's left list, choose open in command prompt/terminal/git bash/powershell, then type in `git checkout ` followed by the hash. To undo type in `git checkout dev` or just switch the branch.
