### ISSUE TITLE
Items: 1/3, 2/3, 1/4, 3/4 thickness block

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1611]
More blocks in the category of chamber structure.

Er... what else to say... 

Qualifications:
- Very good at being structural
- Blends in well with surroundings
- Can support heavy loads
- Cannot speak
- Incapable of stabbing
- Hazard-proof

Happy Modding!

**Comment by TeamSpen210** [comment]
Could you describe more how they're shaped? You've given one dimension, the game is 3D.. And also where they position and rotate.

**Comment by Endermage77** [comment]
They are basically full-size blocks with different thicknesses, like the already-existing 1/2-thick block.

**Comment by libbybapa** [comment]
The 1/4 and 3/4 full voxel flat blocks already exist.

A 1/4x1/4x1/4 would be useful.  Use two variants in order to allow all 16 positions on the face of a voxel.  

On a similar note, vertical versions would also be useful 1/4x1/4x1/2, 1/4x1/4x3/4, 1/4x1/4x1.  Again, I think you would need two variants for each in order to allow all 16 positions on the face of the voxel.

**Comment by Endermage77** [comment]
Alternatively, you could use the 8-Positiion widget to deterimine whether it shows up on the left or right side (using the near/far or far/near spots).

**Comment by TeamSpen210** [comment]
Don't we already have this?
