### ISSUE TITLE
Implement the Hover Turret

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1641]
I would like for the cut Hover Turret to be implemented into BEE2.4. Somebody made a hover turret fix add-on which you could use for this. Since the turret doesn't actually hover (it hangs from the ceiling), call it something like the Laser Turret or Ceiling Turret. This would only be placeable on the ceiling and possibly walls. Here are style suggestions for this item:

- Clean: Custom core model with red eye
- Overgrown: Dirty version of custom red-eyed core, occasionally sparking
- Portal 1: Anger Core
- Old Aperture 50s-70s: Some sort of prototype design
- Old Aperture 80s: Dirty red-eyed core like on Overgrown.

Now, for unimplemented styles:
- Refurbished, Art Therapy: Same as Clean.
- Reconstructing: Same as Overgrown, but sparking less often.
- TWTM: Futuristic version of Clean model.

**Comment by Byzarru** [comment]
Some of the prerelease material called it the "Lazer [sic] Turret". It seems more like a rocket turret that uses lasers instead of rockets. I have some notes, I'll give them in a couple of hours.

**Comment by TheDarkBomber** [comment]
The hover turret is in the mod PORTALHOT, you should use the models from that.

**Comment by Luke18033** [comment]
@TheDarkBomber - I didn't think that had been released yet.

**Comment by andremiles1** [comment]
A Turret that can walk - like how a Track Platform moves - would be awesome.

**Comment by Byzarru** [comment]
- The item as it appears in publicity material does not appear to be close to finished, in both form and function. As such, the item should not be included in BEE as-is. The following are some notes and suggestions on how to finish the item.
- I will always argue in favor of the duck test.
- An alternate name for the item was "Lazer(sic) Turret."
- Apparently it emits a blue laser that harms the player but does not impede progress. This blue laser is identical in appearance to the Rocket Turret's laser, which does not harm players. This similarity will confuse players. The best compromise I can think of is to use a Thermal Discouragement Beam. The fact that this is a beam that moves will tip players off that this is an entirely new item. It will also fulfill the item's purpose - being a moving laser that causes damage. 
- Another idea I think I proposed on Gitter was a Rocket Turret variant that would fire a Discouragement Beam at the player instead of a rocket. This could trigger laser catchers and relays and make for an interesting puzzle mechanic. This shouldn't be the Hover Turret, but I think it's worth mentioning on this thread.
- In the prerelease materials, Hover Turrets were attached to the ceiling by a string and could be disabled by breaking the tether. As a test element in the finished Portal 2, I think that this is sloppy in terms of design, especially compared to other test elements. Instead, it should attach to the ceiling via an arm. It could still possibly be detachable, a la cameras.
- I think Hover Turrets still fired a laser after being disabled. This shouldn't be implemented, so it fits in with other turret items. (Also, would be tricky to practically use a spherical laser emitter in a test) 
- The appearance of the Hover Turret should be close to the Rocket Turret. It could maybe resemble a Portal 1 core (the Curiosity Core was used in the prerelease) attached to a management rail arm attached to a wall.
- This item should be placeable on floors, and Rocket Turrets should be placeable on ceilings.

**Comment by Byzarru** [comment]
I could draw up come concept art for a finished lazer turret later.

**Comment by Byzarru** [comment]
![image](https://cloud.githubusercontent.com/assets/22107242/23490809/2215fbb6-fec0-11e6-9350-996474de13d8.png)

**Comment by Endermage77** [comment]
Sooo you basically want a core-shaped laser camera?

**Comment by Byzarru** [comment]
That's my take on it. Personally, I think the item should be updated and overhauled instead of being added as-is, and this is how I think that would work.

**Comment by Byzarru** [comment]
![](https://files.gitter.im/BEEmod/BEE2-items/hBpu/blob)

**Comment by Konclan** [comment]
Oh god don't add the laser turret, it was in a map around last December and it was one of the most annoying things

**Comment by Konclan** [comment]
The map is Snowed In by Brave https://steamcommunity.com/sharedfiles/filedetails/?id=596214423

**Comment by TheDarkBomber** [comment]
@Luke18033 PORTALHOT has been released.

**Comment by Byzarru** [comment]
It could emit a laser once it detects the player and use the blue seeker while it's not firing. The difference between this and my laser turret concept is that this turret will follow you and fire until you are out of view, while my turret holds still and fires for a few seconds.

**Comment by ZombiePwner1** [comment]
@Byzarru I don't think you can change the hover turret to do that you'd probably need to edit the games code in order to achieve this.

**Comment by Byzarru** [comment]
It would have to be a totally new item, I think.

**Comment by TeamSpen210** [comment]
Indeed this would be very difficult to implement.

**Comment by TheDarkBomber** [comment]
@TeamSpen210 But it's in a Portal 2 sourcemod named PORTALHOT.

**Comment by Byzarru** [comment]
@TheDarkBomber But you said the hover turret looks just like the ones in beta Portal 2, and (according to Konclan) is "very annoying" in a normal gameplay environment (SUPERHOT is a game about slowing down time, yeah?). It would be difficult to fix the item not only in terms of function, but form as well.

**Comment by TheDarkBomber** [comment]
Use that model for P1 style, or Beta Style.

**Comment by King0191** [comment]
(Copied from duplicate Issue i made) 
it seems that the A.I. is intact, Just missing model and voice-lines. It doesn't fire a Thermal Discouragement Beam, Seems to be the same beam as the Stalker NPC in HL2. However would it be possible to recreate the Hover Turret (with a model, Possibly the placeholder Curiosity Core for Portal 1 style. I like the Curiosity Core model) except it fires a Discouragement Beam?
This would allow for an interesting test mechanic where you temporarily activate a Relay or Catcher, and it drops a cube or some other item. It could either shoot it from its eye, or have a little emitter on the bottom of it.
I don't feel the Anger Core or Red eye core fits. Turrets are meant to make you feel BAD for killing them. Anger/Red Core doesn't fit that at all.

**Comment by Luke18033** [comment]
Not really needed, the original beta hover turret is unfinished and bad, and a custom laser turret would be hard to implement and still doesn't have much puzzle use.

**Comment by CockroachSlayer** [comment]
Some of us would want the hover turret as a feature for test chambers though. Also you could probably just add the code from the Hover Turret fix mod.

https://www.moddb.com/games/portal-2/addons/hover-turret-fix
