### ISSUE TITLE
Paired Buttons & Cubes

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1668]
<s>Basically, we could use the already-existing timer widget that is used to pair cubes and droppers and use it to pair cubes and buttons, too. For example, a button with timer value 17 can only be activated by cubes with timer value 17.

To make this distinguishment between numbered and unnumbered cubes, we can replace the logo on the side of the cube with an antline signage, and the same for the button.</s>

New revision! The paired button-cube system would use the colorizer to link cube and button "types" together, allowing for a much more visual and helpful method of linking them together than the arduous signage-timer thing I suggested above. The signage-timer idea wouldn't really work anyway, since the timer's already used for linking cubes to droppers.

**Comment by Byzarru** [comment]
The Music Cube is (hopefully) going to be included with the Blue Portals Pack, which already allows three unique connections.

**Comment by TheDarkBomber** [comment]
The music cube isn't going to be added.

**Comment by Byzarru** [comment]
Why not?

**Comment by TheDarkBomber** [comment]
No need.

**Comment by Byzarru** [comment]
:cry:

**Comment by Luke18033** [comment]
@TheDarkBomber, you can't tell somebody you're going to add something just to then say "were not going to, no need"...

**Comment by Luke18033** [comment]
I'd like to have the Music Cube or something similar, there have been many times where I've needed to redesign an entire puzzle because it needs more than 2 unique cube types.

**Comment by Byzarru** [comment]
And I would've done most of the custom assets anyways (the texture and the music). Besides, we are including the Heavy Cube, which doesn't even have any material that suggests how it worked while the Music Cube was included in a video.

**Comment by Endermage77** [comment]
So is that a yes or a no for the signage-cube/button idea?

**Comment by Byzarru** [comment]
If the Music Cube _is_ implemented, it's a yes for at least three connections (the video only had three instruments and all of the loops will have to be custom made, I can envision at least two more instruments). If not, it _might_ be a yes for a wider range of items, but there is no answer for certain.

**Comment by TheDarkBomber** [comment]
@Luke18033 Just get these implemented then.

**Comment by Byzarru** [comment]
The Music Cube has the advantage of having been developed and showcased in a mod before, and it's arguably a lot more fun. I'm still going to develop the texture and the tracks if anyone else would be interested in making this item.

**Comment by quat1024** [comment]
If this was to be implemented, it should definitely be as an additional feature for the existing cube colorizer, instead of having a timer control on buttons. Perhaps if the cube colorizer was placed in the same spot as a button instead of a cube dropper, it would act as a "button colorizer".

I don't like using timer signage... I'm already fairly against having the timer signage on *cubes* in the first place, because the timer signage is *always* there, adding clutter, but puzzle authors rarely (if ever!) use it, and the use cases it *does* have are extremely easy to work around (for example, if you want the cube to be initially hard to reach but then respawn in a different location, put the cube dropper above a 90 degree panel which the player can open with a button press)

I like the idea, it might lead to some interesting puzzles. But I'm also super on the fence about this, because it has the potential to be *very* confusing if implemented poorly.

> there have been many times where I've needed to redesign an entire puzzle because it needs more than 2 unique cube types.

Well, off the top of my head I can think of cube / lasercube / sphere, and if you want to count frankencubes, that's 4 right there. You could also rework the puzzle to use a well placed cube sacrifice, which would force the player to make a choice about which cube goes on which button, kind of like how [Chander Test 16](https://steamcommunity.com/sharedfiles/filedetails/?id=132397163) uses the weird laser field nonsense to enforce bringing three cubes and leaving behind one. You can also look at libbybapa's (ridiculous) [There and Back Again](https://steamcommunity.com/sharedfiles/filedetails/?id=865946642) for a good example of having multiple cubes which are differentiated by the methods used to respawn them

**Comment by Byzarru** [comment]
I posted this explanation in defense of the Music Cube on gitter:
> The problem with using the connection icons is that it may lead people to assume that the cube or button itself activates an output instead of being linked to a button

But I'm primarily arguing for why the item (which has this functionality) should be included in the BP pack TDB is developing, and not so much as an implementation of this feature.

**Comment by quat1024** [comment]
^ Using the cube colorizer would solve that ;) I don't think anyone will confuse colored cubes/buttons for an activator

**Comment by TeamSpen210** [comment]
I didn't really want the coloured cubes to have any inherent properties, other than visual distinctions. Especially since in the next release you can change the colours to anything, it would be easy to have 2 with almost identical colours that don't work together.

**Comment by Endermage77** [comment]
I would like to point out that that although there are currently at least 5 different cubes, there are only two cube-specific buttons, one being the Cube button (Which admittedly will take any non-sphere cube), and the other being the Sphere button, which ONLY takes spheres.
Basically, what I want here is an easy way to have more buttons that take ONLY cubes of type x.

**Comment by TeamSpen210** [comment]
I might want to make some apparatus which works as a laser-only cube button - like a cutout in the floor, with a catcher and emitter on the sides. They'd be recessed to ensure you can't hit from outside, and it'd block using the laser in other directions.

**Comment by Endermage77** [comment]
I would think the laser-cube-only button would work better with the laser on the bottom and catchers all around the sides, so it stays active no matter which way the cube faces.

**Comment by TeamSpen210** [comment]
It might be fancy and have a rotating base which fixes the orientation for you.

**Comment by Endermage77** [comment]
Which one saves on lag?

**Comment by Luke18033** [comment]
Doesn't look like this really went anywhere, colorized buttons aren't being added.
