### ISSUE TITLE
Portal 1: Make Antlines Less Thick

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1717]
The antlines for Portal 1 style is a little thick. Is seems too thick, and it bothers me a lot. Is there any way to see if you can make it thinner?

![20170313191357_1](https://cloud.githubusercontent.com/assets/25728252/23879127/990a5482-0821-11e7-96b0-ec9b67477bba.jpg)

**Comment by ZombiePwner1** [comment]
That's on purpose due to reasons.

**Comment by hop193** [comment]
> That's on purpose due to reasons.

Can you be a little more specific, please?

**Comment by Luke18033** [comment]
It's on purpose, but it's not permanent. The compiler doesn't have the logic to correctly set up the Portal 1 antlines, which are thinner than in Portal 2.

**Comment by hop193** [comment]
> It's on purpose, but it's not permanent. The compiler doesn't have the logic to correctly set up the Portal 1 antlines, which are thinner than in Portal 2.

Alright, thanks.

**Comment by TeamSpen210** [comment]
Well I could potentially make the straight parts half the size, but the difficultly is really with the corners - it'd be a lot of work to figure out exactly which sides of the overlay need to attach to the corner, which quadrant to put it in, and so on. Really you'd want it to be on a more appropriate side of the tile instead of centered, but that's also difficult. It gets more compilicated as well, since depending on what side the corner might need to be two corners, or a corner and straight part, or something like that.
