### ISSUE TITLE
1960´s Old Aperture Build Error

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1764]
![20170321213322_1](https://cloud.githubusercontent.com/assets/25728252/24178204/0cc68032-0e7e-11e7-82c3-8c2d9e570092.jpg)

**Comment by TeamSpen210** [comment]
Must be missing a HEP launcher instance.

**Comment by TeamSpen210** [comment]
That instance should be there though...

**Comment by hop193** [comment]
Weird...let me look in packages.

**Comment by Endermage77** [comment]
The packages folder has to be in the "BEE2.4_pr24_win" folder, which is where the "bin" and "config" and the other main folders are. By default, the BEE2 exe looks for the packages folder placed here.

I say by default though, because you can change the directory where BEE2 looks in the config.config file in the "config" folder by changing *package* under the directories heading to the new location of your package folder, with the format of "blah/blah/package". No quotes.

Be aware, however, that by default BEE2 starts looking in the "BEE2.4_pr24_win" folder mentioned above, meaning that you have to leave out all of the folder directory including and above that folder name, and trying to place your package folder anywhere outside of that folder won't work.

**Comment by LautaroL20** [comment]
This is fixed now.
