### ISSUE TITLE
Portalable Door

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1775]
Upgrade the BEE door with a tick box: 'Start Reversed' which will change the portability. Useful for when a door is by a bunch of portable walls.

**Comment by TeamSpen210** [comment]
That should be done automatically.

**Comment by hop193** [comment]
Well, sadly, it doesn't, at least for Portal 1 style.

**Comment by HugoBDesigner** [comment]
It works for me, it takes the portalability of the floor. I personally wish it was configurable (in order to match the walls), but the door item already uses "Start Enabled" for open/closed states and "Start Reversed" for which way it's facing (inwards/outwards). A "poor" solution would be to add half-walls on top of the door's surface

**Comment by TeamSpen210** [comment]
It's implemented for P1 style.

**Comment by hop193** [comment]
>  it takes the portalability of the floor.

OH, That's why it's been like that. For me, it was "black" because the floor was non-portable.

**Comment by Luke18033** [comment]
It should be a property on the item. How about use Start Open to determine if the door starts open, and switch Start Enabled to control portalability?

**Comment by HugoBDesigner** [comment]
Because the "Start Reversed" determines which way the door is facing: useful for Portal 2 doors
