### ISSUE TITLE
Modify the Splash Screen

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1816]
To me, I like to have BEE2 running in the background while I make a level in Portal 2 because, sometimes, I forget what some kind of setting does or the item's purpose overall. (For example, Victory Lifts having "Auto-drop First cube") The only problem is if I need to know something and it isn't open, when I run it, the splash screen is in the middle of the screen. Now, this wouldn't be a big issue, if I could just click out of the box to be able to see what I'm doing. Sadly, I can't. I have to wait for it to load to continue. Plus, (for Windows) clicking in the bottom-right corner of the taskbar (to hide all programs and just show the desktop) won't even get rid of it! Can you please make it so you can "minimize" out of the Splash Screen while it loads? Thanks!

**Comment by Luke18033** [comment]
This isn't possible unfortunately, but in the next version you'll be able to drag it around (and off the side of) the screen.

**Comment by Luke18033** [comment]
This is a BEE2.4 issue.

**Comment by hop193** [comment]
Sorry, and by version, do you mean Pre-Release 25 or BEE2.4.1?

**Comment by Luke18033** [comment]
Pr25. I'd say BEE2.4.1 if I was referring to that.

**Comment by hop193** [comment]
Oh, OK.

**Comment by TheDarkBomber** [comment]
@Luke18033 Actually it is possible, it's just that @TeamSpen210 doesn't care.

**Comment by TeamSpen210** [comment]
Do you know anything about the code?

**Comment by TheDarkBomber** [comment]
Do you know anything about looking at and rewriting code?

**Comment by HugoBDesigner** [comment]
Despite not knowing about Bee2's code or language, I know from experience that loading screens aren't as flexible as regular windows. They can't be manipulated easily because one of the things they do is actually generate the manipulable windows. If we were to make the program load faster by delaying the loading of some features, it'd "work", but it'd make the program super laggy to begin with and it'd be super sloppy. I guess a better solution, for now, would be making the loading screen smaller.

**Comment by Luke18033** [comment]
That and making it draggable, which is already done.

**Comment by TheDarkBomber** [comment]
@HugoBDesigner Loading screens aren't as flexible as regular windows as they can't be dragged.

**Comment by HugoBDesigner** [comment]
But Luke just said they were made draggable?
