### ISSUE TITLE
The BTS Exit Door fleetingly opens for 1 second and then closes while the imput was not activated yet

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1870]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/25193972/42dddbf0-250f-11e7-9726-74794677a0d1.gif)

______________________________________________________________________________

That happens when you approach closely to the exit door and then you walk back away from it, when some non-activated imput is connected to the door.

**Comment by TeamSpen210** [comment]
It must trigger the close animation again.

**Comment by LautaroL20** [comment]
Not a bug then?

**Comment by TeamSpen210** [comment]
It's a bug, I need to redo it to work more sensibly.

**Comment by Luke18033** [comment]
Why doesn't it just work like the Clean door?

**Comment by TeamSpen210** [comment]
The clean door is a special entity specifically for it.

**Comment by Luke18033** [comment]
I know that. But you can use the same logic, just replace the `open` and `close` inputs with `setanimation open` and `setanimation close`.

**Comment by TeamSpen210** [comment]
No. That gives this problem - if the animation triggers twice, it snaps to the first frame of that animation and re-closes.

**Comment by Luke18033** [comment]
Couldn't you use a script to override the model on a `prop_testchamber_door`?

**Comment by TeamSpen210** [comment]
Maybe, but it's easier to replicate the functionality with a few relays.

**Comment by Syni44** [comment]
I'm having this issue as well. If I stay away from the exit door in order to not trigger this, and activate the switch meant to open it, it will stay closed, but removing the switch will open it, as if there's NOT logic happening. Conversely, doing this bug and then activating the switch has it working normally.

In addition, the door at the other end of the corridor once inside the initial exit doesn't seem to open in any circumstance.
