### ISSUE TITLE
Idea: Ability to Change Loading Screen...Screen

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1898]
Every time you load a BEE2.4 level, it just shows the picture of P-BODY jumping into a portal, just like what it does in PeTi. I think in the "Compiler Options" window, you should be able to choose the picture. Examples:

- GLaDOS
- Overgrown Aperture Symbol
- Clean Aperture Symbol
- The Entrance to Old Aperture
- The 1950s - 1980s Aperture Symbol
- Wheatly Laboratories Symbol
- Default (P-BODY jumping into portal)

These are the ones on the top of my head. I'm pretty sure there's more, but I'm just not remembering them now.

**Comment by LautaroL20** [comment]
This is not possible. Since those loading screens happen before the map is loaded, the game can't read from the map to figure out which one to use. Instead they're determined based on the map name - `sp_a1_` - `sp_a4_` . We can't change the PeTI map name, so this is the one thing that's impossible to do.
