### ISSUE TITLE
Closed Solid field is completely broken. Missing textures mysterious black and purple checkerboards.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1918]
![20170507074057_1](https://cloud.githubusercontent.com/assets/18079316/25776735/e34b774e-32f9-11e7-81e3-de31d2d9d148.jpg)

Using laser field emitter frames.

![20170507074641_1](https://cloud.githubusercontent.com/assets/18079316/25776737/ee96b05a-32f9-11e7-8e27-9fbe4237dc37.jpg)

Mysterious black and purple checkerboards.

![20170507074650_1](https://cloud.githubusercontent.com/assets/18079316/25776739/f69bc858-32f9-11e7-89cf-0bd081b094b8.jpg)

Missing textures..

**Comment by Luke18033** [comment]
Being able to place gel on it is intentional.

**Comment by ZombiePwner1** [comment]
Just make a paint fizzler in the field since gel on the field looks very wrong.

**Comment by Luke18033** [comment]
That's just because the texture is missing.

**Comment by ellingtonvengaboysmuseum** [comment]
someone ripped this field off from my original unreleased force field (it was white and looked VERY similar to this), fortunately i found a way to encrypt all my work when i designed it, hidden DRM coding would make it so it would not work if any part was altered. so the Texture Files will not work across multiple portal 2 game ID's since the files have been changed and the encryption algorithm picked this up.

**Comment by Luke18033** [comment]
What do you mean "removed from the coding section"?

**Comment by ZombiePwner1** [comment]
This seems fixed now.
