### ISSUE TITLE
Compressed smoke field deflection field and inquisition fields are still using their old In-Game Icons

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1922]
![20170507081222_1](https://cloud.githubusercontent.com/assets/18079316/25776857/04d4c4e4-32fd-11e7-852c-b4c11984bd30.jpg)

**Comment by Luke18033** [comment]
Weird, I changed those...

**Comment by LautaroL20** [comment]
The problem here is that you obviously (and for anyone who had a previous Beemod version) didn´t delete the "bee2" folder insisde the Portal 2 directory which contains all the bee materials & models, so the game keeps using the old resources.

Since the PRL25 doesn´t override / delete the files in those folders anymore, now you have to do it manually. This is something that definitelly must be in the Readme file to let know the rest of people.
