### ISSUE TITLE
Global Cube Droppers and Value Portal 2 Update

### ISSUE THREAD

**Issue by RDWofRDW** [BEEmod/BEE2-items#1962]
The Portal Deflector Cube would be complete if the Global Cube Dropper dropped the Portal Deflector Cube.  But now, there is a bigger problem since Value decided to update Portal 2 to remove the shiny Salt Caves.  The Global Cube Droppers all stopped working in all my maps.  Have you discovered this?  Plan to fix it? A fix for BeeMod2.2.5 users?

**Comment by TeamSpen210** [comment]
Strange. They never dropped those anyway.

**Comment by LautaroL20** [comment]
> RDWofRDW Said: "A fix for BeeMod2.2.5 users?"

That version is totally abandoned since some years ago, so do not expect any updates for it. That version is the one i were using before Bee2.4 reached the PRL18, where it became stable.

**Comment by LautaroL20** [comment]
> "That version is the one i were using before Bee2.4 reached the PRL18, where it became stable."

Although it is worth mentioning i am contributing here since the PRL6.5 came out, finding out bugs. Here´s my very first post: 

* "The first bug is related to the "Exporting..." process, wich makes less than half the progress, and then **it becomes stagnant forever**" (https://github.com/BEEmod/BEE2.4/issues/80)

There is where it born my phrase "Stagnant Forever" that i use sometimes in titles...

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
