### ISSUE TITLE
Add custom test elements from "Try Anything Twice"

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1966]
Reference:
https://forums.thinking.withportals.com/community-releases/try-anything-twice-t1997-75.html

**Comment by Luke18033** [comment]
Booster strips would be nice to have as well, they're a bit different than faith plates. I'm not sure if they're even possible to implement though.

**Comment by HugoBDesigner** [comment]
They could be implemented like rail platforms I guess

**Comment by Luke18033** [comment]
Some additional notes:
- Laser filters and cube defuser fields would also be added. Defuser fields should have their texture redone for Portal 2 styles, the original one doesn't match with the other fizzlers. Laser filters would use their original texture on all styles.
- Booster strips would be resizeable using the track platform class, working similarly to Conveyors. The autoportal at the end would be built in, and Auto-Drop and Auto-Respawn would allow choosing what portal is created (none removes the autoportal and both spawns the frame only).
- Due to a limitation of `trigger_push`, the original booster strips only worked in specific places, which isn't suitable for PTI. However, `trigger_catapult` is available in Portal 2, which may allow us to work around that issue. Additionally Portal 2 is a different engine version so the `trigger_push` bug could have been fixed.

**Comment by Endermage77** [comment]
What are the items being suggested, again?
And what do they do?

**Comment by Luke18033** [comment]
Download the map. The lasers are in chamber 2, the HEP buttons (which we both forgot about) are in chamber 4, and the booster strips and exploding cubes are both in chamber 5.

**Comment by Luke18033** [comment]
HEP buttons are similar to timed catchers, but they don't "absorb" the peelet, it just bounces back off. They emit a blue light.

**Comment by HugoBDesigner** [comment]
HEP buttons are really useful, we totally forgot about those

**Comment by Luke18033** [comment]
The TA2 laser system was actually the basis for the Sendificator, so from a technical standpoint they almost already exist in BEE. The booster strips probably don't need to be added, Propulsion Gel does basically the same thing.

**Comment by Luke18033** [comment]
These should really be separated into individual issues though.
