### ISSUE TITLE
Cool Light Strips can have Portals placed on them

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2-items#2017]
![why are you reading this 2017-05-28 19-38-27-099](https://cloud.githubusercontent.com/assets/26350889/26531349/4475676e-43df-11e7-8d08-d219a792a9c4.jpg)

**Comment by LautaroL20** [comment]
Are you using the Pre-release 24 or 25?

**Comment by iEnderMan06** [comment]
@LautaroL20 Dev

**Comment by LautaroL20** [comment]
Your game must be using old instances and materials from past releases, since this bug was fixed a long time ago (https://github.com/BEEmod/BEE2-items/issues/1474)

## Solution: 
Delete everything in `Portal 2\sdk_content\maps\instances\bee2` and `Portal 2\bee2`

Hit the Sync button on the Github app while standing in the Dev Branch. Then launch Beemod and do a "Full Export" (exporting having the Preserve Game Directories unchecked) and the issue must not be there anymore.

**Comment by Luke18033** [comment]
An easier way to do that is to just remove Portal 2 from  BEE2.4's game list, re-add it, and then export.
