### ISSUE TITLE
Overgrown exit door is duplicated in a mysterious way

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2039]
_From @Te4mLuna on June 3, 2017 15:49_

This happened twice so far and also includes the weird white void you can see behind the exit.
This white void is the same as the one I mentioned the good showing up as in another issue I opened.
![20170603174522_1](https://cloud.githubusercontent.com/assets/19846848/26754988/fb6ee806-4884-11e7-913f-640a5e1a7db7.jpg)
![20170603174529_1](https://cloud.githubusercontent.com/assets/19846848/26754990/fc419eea-4884-11e7-8b55-0de657c63f29.jpg)

_Copied from original issue: BEEmod/BEE2.4#656_

**Comment by ZombiePwner1** [comment]
F***ING LOL.

**Comment by Luke18033** [comment]
This is fixed now, right?

**Comment by LautaroL20** [comment]
I am almost sure that this issue had to do with old resources from past beemod releases. The original author should try following my trite pre-made message to solve it:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by Te4mLuna** [comment]
I have benn silently following. I will follow your steps as soon as I get back into map making but I currently don’t have the time. I will make sure to comment again though if this was to happen again!

**Comment by LautaroL20** [comment]
@Te4mLuna - The latest version right now is the Pre-release 27. You are probably using an old version, make sure to follow my steps though.

**Comment by Luke18033** [comment]
I think this is now fixed?

**Comment by LautaroL20** [comment]
Most likely.

**Comment by Luke18033** [comment]
Checked in-game, this no longer happens.
