### ISSUE TITLE
Style Suggestions

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2073]
Open Old Aperture Tests like in Aperture Tag
![art_therapy](https://user-images.githubusercontent.com/29339358/27298550-10f757e6-5521-11e7-997d-4d427d77b306.jpg)
Cave Style/Vrit Order Style like the first part of the old aperture chapter.
Chamber Assembly Style https://github.com/BEEmod/BEE2-items/issues/2060
Office Style 1950's or Portal 1 offices.
Overgrown Portal 1
Aperture Tag Style like the final chapter
Moon Surface Styles (Observation rooms are windows to see the surface of the Moon and 0 G option)

**Comment by Endermage77** [comment]
1: Not going to happen anytime in the near future. Definitely on the slate and likely going to be seen someday, though.
2: Already in. It's called the 60's Style.
3: Interesting concept. I wonder what TeamSpen would say to this.
4 & 5: The Portal 1 Overgrown idea doesn't have any assets, so that one is on long term; P1 Office/BTS has been suggested. See both in #553. Old Aperture Office/BTS has been talked about in a couple threads, but I can't seem to find where.
6: This is called the Stage style by the devs; See #1328.
7: See #1494, in which I talk with Luke about space windows in space. On the moon.

**Comment by TeamSpen210** [comment]
2: Not quite, but that's desirable at some point.

**Comment by IceTudor** [comment]
P1 Overgrown? Overgrown IS P1 but it's overgrown, doesn't make alot of sense.

**Comment by Luke18033** [comment]
Not really any new suggestions here, and it's a combined issue

**Comment by LautaroL20** [comment]
Do not forget to apply the corresponding label after closing an issue.
