### ISSUE TITLE
Selection Meshes from Triggers have not proper dimensions

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2078]
![Image](https://user-images.githubusercontent.com/12244376/27666453-4026ed9e-5c4a-11e7-8e03-a4fded1c0040.jpg)

**Comment by Luke18033** [comment]
This is actually the case with most of the original BEE items, Ben must have gotten the dimensions wrong.

**Comment by LautaroL20** [comment]
Well, as for the Logic Gates and Triggers both are fixed now. I didn´t see more inacurate meshes for the moment, if you see them just open an issue and ill fix them in Blender easily.

**Comment by Luke18033** [comment]
As I said, the original BEE1 items have incorrectly sized meshes, so that would be Triggers, Invisible Logic Gates, Door, Pneumatic Diversity Vent, HEP items, Crusher, Warm Light Strip, Autoportal and Drawbridge. You've already fixed the meshes for Triggers and Logic Gates, and I think TeamSpen210 fixed the HEP meshes a while ago. Autoportals just got a new model so they're probably fixed as well. Warm Light Strips just reuse the regular Light Strip mesh which is sized correctly.

**Comment by LautaroL20** [comment]
Drawbridge mesh is fine, as for the Pneumatic Vent and Crusher´s Meshes, they indeed aren´t using proper dimensions. Ill gonna fix them in Blender.

**Comment by TeamSpen210** [comment]
I believe it was originally somewhat intentional, to make them easier to click on.

**Comment by LautaroL20** [comment]
I understand they do not need to perfectly match, but these meshes may interfere with others when there are items close to it, making them unselectable due to the overlap dimensions.

**Comment by TeamSpen210** [comment]
Indeed they should match the models.
