### ISSUE TITLE
P2 Piston Platform bugs.

### ISSUE THREAD

**Issue by BluCodeGH** [BEEmod/BEE2-items#2083]
I have noticed two bugs with the piston platform. ~Firstly, when activated the piston platform will not raise unless it is stood on by the player. If the player moves on to it while it is powered it will start to raise.~

A second bug is that the piston platform got stuck in the raised state, as can be seen below, and when I used noclip to get onto it as soon as I touched it I died.

![stuck-raised](https://user-images.githubusercontent.com/22122986/27714910-d7b2678a-5d01-11e7-952d-26b25bea2a84.jpg)
The stuck piston platform. (sorry for the low quality image)

**Comment by Luke18033** [comment]
The first isn't a bug, it's the result of a modification BEE2.4 makes to the piston platform. See [here](https://github.com/BEEmod/BEE2-items/wiki/Default-PeTI-Items#piston-platforms) for more info.

**Comment by LautaroL20** [comment]
No need to take a photograpy, just press the "PrtSc" key then launch MS Paint and paste the image there.

**Comment by BluCodeGH** [comment]
@LautaroL20 I am not the source of that photo, my friend sent it as he was playtesting a puzzle I made. I'm not sure why he didn't PrtSc either.

**Comment by TeamSpen210** [comment]
Uncheck the 'Auto-Drop' option. With it enabled, the player must be standing on it for it to move. Without it, it'll only obey the input. This was changed because it offers 4 modes total - player-controlled, input controlled, player and input (like in Portal 1), and immovable. The last is most useful because we can swap out the item with a much cheaper version.
