### ISSUE TITLE
New item suggestion :

### ISSUE THREAD

**Issue by TREVTRPD** [BEEmod/BEE2-items#2137]
An Item that works live a save trigger, but instead of saving.. it ends the level.

**Comment by TeamSpen210** [comment]
Why? That would give bad, unprofessional looking results.

**Comment by Endermage77** [comment]
I don't really see the value of a custom endpoint to PTI maps either, unless you used a feature like this in addition to, say, a start zone trigger that overrides the start point of the map, to string several maps together into one seamless chamber. But then again, chambers in the PTI are not especially meant to chain together like that; They're supposed to be able to be chained together in a modular fashion, so that it makes sense, no matter which order you play the levels (Hammer-made levels are obviously an exception to this rule, though.)
