### ISSUE TITLE
Everything Went Wrong

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2146]
3D Factory went wrong
![620_20170813121642_1](https://user-images.githubusercontent.com/28140988/29248623-749c985e-8025-11e7-85bc-0905128b14a0.png)
Sphere Exterior went wrong
![620_20170813124208_1](https://user-images.githubusercontent.com/28140988/29248628-8e5fcf90-8025-11e7-98ee-16560587e445.png)
Death Fizzler's Laser Grid is misaligned
![620_20170813124255_1](https://user-images.githubusercontent.com/28140988/29248633-a56ef6a2-8025-11e7-9cf6-a20d685aa9c4.png)

**Comment by Luke18033** [comment]
The second issue is probably caused by an areaportal leak in the map somewhere, and would probably happen on any non-pit skybox.

**Comment by CreepiX987** [comment]
@Luke18033 what do you mean?

**Comment by IceTudor** [comment]
The laserfield one happens to me too, its annoying and looks horrible, has to be fixed.

**Comment by TeamSpen210** [comment]
I've rewritten the logic for those completely, it's fixed.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

In the other hand, the laserfield issue have been fixed.
