### ISSUE TITLE
Seems like im having more bugs...

### ISSUE THREAD

**Issue by Ewber** [BEEmod/BEE2-items#2171]
This one first.

```
VBSP failed.

Valve Software - vbsp.exe (Jun 28 2017)
2 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/logic/bee/trigger_once.vmf
```

And this...

```
VVIS failed.

Valve Software - vvis.exe (Jun 28 2017)
2 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

```

I had enough of these errors, im gonna tell some other stuff...

Using Overgrown with the default beemod palette. Also using 7 for entry and 3 and 2 for the exit.

**Comment by LautaroL20** [comment]
Try the following, and if you still experience the same issue, feel free to re-open your issue again:

1. Open Beemod and click on File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> Yes.

2. Verify the Game Cache Files. 

3. Make sure to have downloaded and installed the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7 - 10.

4. Click on File ----> Options ----> Development, and now uncheck the option "Preserve Game Directories".

5. Now choose your favorite Items & Style, and export your palette to the game.

6. Happy mapmaking!
