### ISSUE TITLE
OH FLIDERSTRIX, WHAT NOW!?!?!?!?

### ISSUE THREAD

**Issue by Ewber** [BEEmod/BEE2-items#2173]
Ok, I can compile fine, but heres one sentence to describe whats going on...

> DOH FIDDLESTICKS, WHAT NOW?

Yeah, im currently using the portal 1 style, and the doors wont render.

**Comment by Ewber** [comment]
Oh, and this too ```
VBSP failed.

Valve Software - vbsp.exe (Jun 28 2017)
2 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/items/lautaro/empty.vmf

```

**Comment by LautaroL20** [comment]
`Could not open instance file instances/BEE2/items/lautaro/empty.vmf`

Thats pretty strange, can you take a pict of the items you had in the palette when you got this build error? It seems you are using an old version of the compiler.

**Comment by Ewber** [comment]
![capture](https://user-images.githubusercontent.com/31393813/29799102-b60d54aa-8ca4-11e7-9a27-14d305a26037.PNG)
2 Things, when I had nothing in the map, it would compile, but it would play the fiddlesticks sound, and the error notice I got from the console was when I had a few items.

**Comment by Ewber** [comment]
And the exit and entry doors dont show, exposing the nodraw brushes.

**Comment by LautaroL20** [comment]
The bug related to my empty instance can only means you are using an outdated app version. 

Download the PRL25 Application: https://github.com/BEEmod/BEE2-items/releases
Download the PRL25 Packages: https://github.com/BEEmod/BEE2.4/releases

Make sure to always have both application and packages from the same version of release, otherwise issues can occur.

After that, try the following:

1. Open Beemod and click on File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> Yes.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and installed the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7 - 10.

5. Click on File ----> Options ----> Development, and now uncheck the option "Preserve Game Directories".

6. Now choose your favorite Items & Style, and export your palette to the game.

**Comment by Ewber** [comment]
I have done the exact same thing before, and the files are both prl25. I am also running windows, and its a toaster.

**Comment by TeamSpen210** [comment]
@LautaroL20, why do you have an `empty.vmf`? Simply set the path to `""` to delete the instance.

**Comment by LautaroL20** [comment]
@TeamSpen210 - That´s exactly what the vbsp_config file has, i do not have idea whats going on with the issue this guy is having. The Config File:

`````
"Conditions"
{
"Condition"
{
"instance" "<ITEM_LAUTARO_GRIDDED_WALL>"
"Result"
{
"AlterTexture"
{
"Pos" "0 0 0"
"Dir" "0 0 -1"
"gridPos" "1"
"tex" "<4x4>"
}
"ChangeInstance" ""
}
}
}

**Comment by Ewber** [comment]
When I first got bee2 I used prl26 with prl25 packages, thats why it must be causing problems now.

**Comment by LautaroL20** [comment]
Never use different releases, otherwise issues will happens. The PRL26 is stil WIP.

**Comment by Ewber** [comment]
Ok, I think I might just use the normal editor and hammer.

**Comment by TeamSpen210** [comment]
Actually, that should work - the app should be mostly backwards-compatible, but not really forwards-compatible.
