### ISSUE TITLE
BEE2.4 Error - Failure to Start

### ISSUE THREAD

**Issue by ChristopherFredC** [BEEmod/BEE2-items#2191]
I've been trying to start up BEE2.4 (With the Art Therapy and Refurbished prototypes). I tried installing the Art Therapy content, but that for some reason was taking too long which is why I canceled it. When I tried to start up BEE2.4, I got this error - https://cdn.discordapp.com/attachments/265680483243786240/354766435001827330/bee_error.PNG

**Comment by Endermage77** [comment]
Chances are, whatever was in Art Therapy or Refurbished probably started messing with the default BEE2 files before you cut them off, at a point when the BEE2 thing became unusable for some reason.
I'd say you made a good call anyway: Neither of those styles function very much in most cases due to bugs in their current state.

Sadly, I'd guess that your BEE2 is now beyond salvage, and the next course of action would be to copy any palettes you had to a backup folder and redownload the whole thing.

Before you do, though, I would see what the devs have to say about it.

**Comment by ZombiePwner1** [comment]
@Endermage77 Art therapy shouldn't be downloaded right now since the files get put in the wrong place which @TeamSpen210 Needs to fix.

**Comment by TeamSpen210** [comment]
No, just replace your packages folder with the normal versions. Probably you've overwritten something partially or something?
