### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#2192]
- Pellet Catcher does not respond to pellets, simply has them bounce off.
- Rexaura Cube Module plays the correct beep sound when given a cube, along with zap, which is not included in the mod. Not supposed to play any sound when cube is manually removed either.
- Portal 1 theme still plays 'fiddlesticks' voiceline randomly.
- Pellet Emitter and Catcher SFX in level editor (when right-clicked or placed) is absurdly loud.

List will be updated once more bugs are discovered.

**Comment by MrKrunk** [comment]
(Misclicked and posted, writing what I intended here.)

• Pellet Catcher does not respond to pellets, simply has them bounce off.
• Rexaura Cube Module plays the correct beep sound when given a cube, along with zap, which is not included in the mod. Not supposed to play any sound when cube is manually removed either.
• Portal 1 theme still plays 'fiddlesticks' voiceline randomly.
• Pellet Emitter and Catcher SFX in level editor (when right-clicked or placed) is absurdly loud.

List will be updated once more bugs are discovered.

**Comment by Luke18033** [comment]
Comment merged into original issue.

**Comment by CyberSquime** [comment]
When using the P1 style, I would restart my game and for the FIRST compile, it would play the error noise on start. Any other compiles wouldn't play it.

**Comment by LautaroL20** [comment]
Next time make sure to split each bug into a separate issue, that helps developer finding each bug faster in the respository, instead of having to click on an issue just to read a pilled up of notes. Issue has been splitted: 

https://github.com/BEEmod/BEE2-items/issues/2193
https://github.com/BEEmod/BEE2-items/issues/2194
https://github.com/BEEmod/BEE2-items/issues/2195
https://github.com/BEEmod/BEE2-items/issues/2196
