### ISSUE TITLE
new style portal terminal 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2207]
this is the portal terminal mod here  [http://www.moddb.com/mods/portal-terminal](url)

**Comment by BETTEREXTENEDEDITORMOD** [comment]
<img width="447" alt="capture1" src="https://user-images.githubusercontent.com/31172185/30340293-e6ccffc0-97a6-11e7-95cb-13100eb7f6d2.PNG">
<img width="283" alt="capture 3" src="https://user-images.githubusercontent.com/31172185/30340303-ed6d044c-97a6-11e7-940d-00136a7ed726.PNG">
<img width="435" alt="capture 4" src="https://user-images.githubusercontent.com/31172185/30340307-f0892b42-97a6-11e7-8d36-1070a66b7242.PNG">

**Comment by CreepiX987** [comment]
2minecraftish4me

**Comment by BETTEREXTENEDEDITORMOD** [comment]
its supposed to take place in a unfinished 20th century computer simulation of course it's going to look a bit pixely

**Comment by ZombiePwner1** [comment]
Problems with this.

1. Gel: We can't make gel pixelated only valve has the ability to do this.
2. How will entrances and exits work? I mean if you think about it will look abit or quite weird with pixelated things everywhere.
3. Turrets: we can make them pixilated but that'd require a new model + animations.
4. Light bridges: Yes we can change the model of the emitter but the actual bridge itself we can't change. Same goes for lasers.
5. Funnels: Funnels will be a annoying problem with this style since we can't change the emitter otherwise that breaks the animations and we can't change the beam.
6. A lot of other custom items will need pixelated models which will look weird in my opinion.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
oh an exit is just a square that lifts you up into the next chamber
<img width="435" alt="capture 4" src="https://user-images.githubusercontent.com/31172185/30359568-828cac7c-9800-11e7-98b8-fd9afd0325c5.PNG">

**Comment by ZombiePwner1** [comment]
I'll see what @TeamSpen210 thinks.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
so my style is at least possible?

**Comment by ZombiePwner1** [comment]
@TeamSpen210 What do you think?

**Comment by TeamSpen210** [comment]
It looks rather terrible. In general I'm not really interested in doing custom stuff like this, unless it's already in a known mod or map...

**Comment by Endermage77** [comment]
This looks more like a Debug Mode than anything else.

The default style is already almost there in terms of appearance, so why create a whole new thing that will need new models for every single item current and new...?

**Comment by TeamSpen210** [comment]
It is one, it's got 'fullbfight' mode on since there's no lighting of any kind. That's usually considered a basic error to have in Hammer maps. I don't intend on adding that to BEE.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
oh ok i guess issue closed
