### ISSUE TITLE
allow items to be placed on unstationary scaffold track platforms and piston platforms [somehow]

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2214]
this would allow for interesting puzzles including my rotating panel idea here #2204 
this could work like the snapping mechanic used in glass and grating or it could use 
a timer value for a button fizzler laser HEP ect

**Comment by Endermage77** [comment]
I think a couple of items (e.g. cubes, turrets) can be put on tracks and pistons, but they're special cases because they are movable entities that can fall around and... stuff.

As for everything else, that would probably not be doable without editing the source code...
... which is strictly off-limits.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
if this is not doable then i guess issue closed

**Comment by TeamSpen210** [comment]
Basically I'd need to remake every item that can do this.
