### ISSUE TITLE
Players (still) Getting Stuck in Player Droppers

### ISSUE THREAD

**Issue by dnldrl** [BEEmod/BEE2-items#2244]
The description of Pr25 says the Co-op player dropper problem was already fixed, but I am still experiencing it. 
Also, I know user LautaroL20 already addressed this problem in #1439, but I don't get what TeamSpen  meant by "deleting the clip". Perhaps I misunderstood that last bit, but if you have an answer or solution to why I am still experiencing it, please tell me.

Other details-
Map style: Clean
All three variants suffer the same problem

**Comment by LautaroL20** [comment]
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. 

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

__________________________________________________________________________________________________

Respect to the "clip" it is a brush entity from Hammer editor, which are using these droppers, and by deleting them it may fix this old bug but your problem is different, try out the solution from above

**Comment by dnldrl** [comment]
ok thanks! :) but what will happen to the maps i were making after I reinstall BEEMOD? will the map be corrupted? will the map be missing all the resources?

**Comment by TeamSpen210** [comment]
No, this doesn't touch your actual maps. If you really want you can back them up first... Actually do that anyway if you have any you don't want to lose.

**Comment by LautaroL20** [comment]
@dnldrl - Feel free to let us know if my steps has solved your issue.

**Comment by dnldrl** [comment]
yes! it worked :) thank you!!

**Comment by Nikita74RU** [comment]
My bee mod works now.
P.S I love it
