### ISSUE TITLE
When is the next major update due for release?

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2247]
When is the next major update due for release? it has been six months since a major release...

**Comment by Luke18033** [comment]
I'm not sure, I have noticed that it's been quite a while since the last update. You'll have to ask @TeamSpen210 about that. It's usually a good idea to ask questions like this on [Discord](discord.me/beemod), that way we don't need to open an issue just to have it immediately closed once the question is answered.

**Comment by TeamSpen210** [comment]
I was going to do one yesterday.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Let us know to all collaborators before you release the next update, so we can give the latest enhancements and playtesting on recent items and such.
