### ISSUE TITLE
Conveyor belt idea.

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2261]
Why not make it so that you can select on the conveyor belts button type? It could work like this:
Weighted: Standard.
Cube: Incinerator at the end, like the turret redemption line, destroys all cubes/turrets/etc.
Sphere: Lasers, like in the BTS area where the turret parts are cut out

**Comment by Endermage77** [comment]
You could probably create the laser belt by putting some laser fields on timers above the belt.

As for the incinerator belt... somebody could probably suggest the firey bit separately?
What if I don't want to conveyor stuff into the fire, but fling stuff in instead. Or drop stuff in?

**Comment by IceTudor** [comment]
That's kinda an entirely different idea, this is for conveyor belts. I do wish we had the old BEE2 Incinerator back. I kinda miss it

**Comment by TeamSpen210** [comment]
Button type doesn't work with the track platform type. The laser thing really needs to be something commpletely different, it needs supports and anchors on different sides and really isn't something you can make cookiecutter. The incinerator can be done already, with a Discouragement Field, Fizzler or Death Fizzler. The reason why the conveyor is one block away from the anchor surface is so that you can put items directly above it.

**Comment by IceTudor** [comment]
Oh, sad, really wished to make a level with it, what is the discouragement field by the way? Always hear of it but never knew what it was.

**Comment by TeamSpen210** [comment]
Fancy unofficial name for Laserfields.

**Comment by IceTudor** [comment]
Oh... Weird.
