### ISSUE TITLE
Separated COOP Checkpoint causes "Failure To Compile" in Overgrown Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2263]
`Could not open instance file instances/BEE2/over/items/tSpen/coop_checkpoint_sep.vmf`

**Comment by Luke18033** [comment]
I think this would actually be my fault - back in Pr25 when I was improving the co-op checkpoint icons, I decided to also add an Overgrown variant of the separated checkpoint. So I changed the editoritems file to point to that instance instead of the Clean one, but forgot to actually make the instance. Whoops. Or I might have actually left it out intentionally, since I was a Hammer noob at the time.

**Comment by Luke18033** [comment]
"Fixed" by reintroducing #647
