### ISSUE TITLE
Cube Dropper in BTS Style gone "Nuts", it spawns 2 cubes at the same time in a "Mysterious Way"

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2-items#2270]
2 cubes will spawn out of one dropper at the same time in BTS style in a "mysterious way".

**Comment by Endermage77** [comment]
Would you like to change the title so that it more helpfully reflects what you want to say?
I''m afraid just simply typing "cubes" won't especially help people know what you mean at first glance. Or even second glance.

**Comment by LautaroL20** [comment]
@eeeee48 - Can your redo the description? Seems very unclear for me.....

**Comment by ZombiePwner1** [comment]
@LautaroL20 He means that 2 cubes will spawn out of one dropper at the same time in BTS style.

**Comment by LautaroL20** [comment]
Lol, dat bug then.

**Comment by IceTudor** [comment]
Well, normally the game releases a cube, then spawns another as backup, however, with no dropper valve, it would release 2.

**Comment by eeeee48** [comment]
it more then 2
my friend who played my map said he got 20 or 30 out
and none of them respawned

**Comment by LautaroL20** [comment]
@eeeee48 - This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
