### ISSUE TITLE
Absolute fizzler does not work as intended in coop.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2273]
https://gyazo.com/855e6e0d332340bbdc1b1908bac7cc12

**Comment by TeamSpen210** [comment]
I honestly didn't think about that in Coop.

**Comment by TeamSpen210** [comment]
Turns out I had thought about it and did implement it properly for Coop. The problem is actually that the voiceline attributes for fizzlers aren't being used, and the portalgun logic uses those to decide if the scripts and entities should be added. So it won't have the logic, unless you place a Portalgun ON/OFF button in the map. This also means fizzler voice lines won't ever trigger.

**Comment by IceTudor** [comment]
Absolute fizzler? What's that?

**Comment by TeamSpen210** [comment]
An item made by Tuleby. When you go through it it fizzles *all* portals, for example ones made by a Pedestal, or ones you place through an ON/OFF Button. In Coop it'd fizzle your partner's portals too.

**Comment by IceTudor** [comment]
Including blocking portals?

**Comment by TeamSpen210** [comment]
It's an "upgrade" to normal fizzlers, so it still has all their effects.

**Comment by IceTudor** [comment]
Oh I get it, an emancipation grid with the ability to erase not only yours, but ALL portals. Makes sense.

**Comment by IceTudor** [comment]
So would a Death fizzler essentially be a laserfield upgrade?
