### ISSUE TITLE
Portals can still be placed on cold light strips.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2275]
![20171011075227_1](https://user-images.githubusercontent.com/18079316/31416047-3b0b60f4-ae59-11e7-8a69-bea7ef5adbb2.jpg)

**Comment by Luke18033** [comment]
This is probably also caused by the game using old resources, you should know the solution to the issue.

**Comment by LautaroL20** [comment]
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
