### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2287]
I'm trying to create some custom fizzlers for BEE2.4 PRL25, any help on how to make them?

**Comment by Luke18033** [comment]
Step 1 would probably be to update to Pr27, since it completely changes the way fizzlers are made and you might as well make it in the new format so that you don't have to convert it later. I'm not sure exactly how to make a custom fizzler, but you can look at the existing ones as an example.

**Comment by Luke18033** [comment]
Also, it's usually a good idea to ask questions like this on the [Discord server](https://discord.me/beemod) so that we don't open a bunch of issues just to have them immediately closed once the question is answered.

**Comment by IceTudor** [comment]
Dunno how to update, have no discord and never plan to aswell.

**Comment by LautaroL20** [comment]
@IceTudor - To update to the PRL27, youll have to download the app and packages, here:

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.0pr27 (Application)
https://github.com/BEEmod/BEE2-items/releases/tag/pr27 (Packages).

**Comment by LautaroL20** [comment]
Also, to make sure you will not experience issues caused by the game for using old resources from past Beemod releases, you will have to do the following once you installed PRL27;

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by TeamSpen210** [comment]
Relevant: https://github.com/BEEmod/BEE2-items/wiki/vbsp_config_fizzler
