### ISSUE TITLE
Triggers activate connected item(s) even when not all other inputs are active

### ISSUE THREAD

**Issue by toncica2** [BEEmod/BEE2-items#2290]
When a test element is connected to multiple inputs and at least one of the inputs is a Trigger Zone then the Trigger Zone (both Multiple and Once) will enable the element before the last connection is active.

Another beahvior of this bug is that when you add a weighted button and a trigger once, then you press first the button then to walk thru the trigger, that will activate the item. However if you first walk thru the trigger then to press the button, this issue will not happen.

In this demonstration video the Trigger Zones are placed on square lights:
https://youtu.be/0DSHXdJvYgY

**Comment by Endermage77** [comment]
There used to be a logic item called the Override Gate in BEE2.4. It was an A/B Input item and it worked like this:
A would toggle the output normally.
When B activates, it forces the output on/off regardless of whether A is activated.

Would that do?

**Comment by toncica2** [comment]
It was meant as a bug report, not a request. This is not how trigger zones should behave. The instant workaround would be to avoid a direct connection and connect the trigger zone to the test element via an AND gate.

**Comment by Endermage77** [comment]
Oh. I thought this was a request for a Trigger Override. My bad.

**Comment by LautaroL20** [comment]
Yes, this also happens to me, and it doesn´t have to do for using old resources from past releases. Another beahvior of this bug is that when you add a weighted button and a trigger once, then you press first the button then to walk thru the trigger, that will activate the item. However if you first walk thru the trigger then to press the button, this issue will not happen.

**Comment by TeamSpen210** [comment]
This is now fixed.
