### ISSUE TITLE
PRL 27 BUG: A/B inputs don't change antline overlays

### ISSUE THREAD

**Issue by toncica2** [BEEmod/BEE2-items#2307]
The A/B inputs work, but their antlines don't indicate when they are triggered.

**Comment by TeamSpen210** [comment]
Yeah, it's because they aren't helped by the compiler.

**Comment by toncica2** [comment]
Why label this as 'Enhancement'? For the record, I have been using A/B inputs before and the antlines were working until PRL27.

**Comment by TeamSpen210** [comment]
Is this the antlines on the input side of the A/B item, or between A/B and the target? Because the latter never worked (which is the enhancement), the former should work correctly (bug if not).

**Comment by toncica2** [comment]
Ah okay, it's the latter. Apparently I have always set A/B connections to invisible before.

**Comment by TeamSpen210** [comment]
It's how I implemented them. Basically for each connection, there's a pair of commands - one for when it's activated, and one for when it's deactivated. For input A/B, I reuse those to instead be whenever A toggles, and whenever B toggles. Then the A/B items only trigger one. Which means for antlines since they didn't get the memo, they just are switched permanently on for A and off for B.

**Comment by TeamSpen210** [comment]
Implemented in the `connections` branch.
