### ISSUE TITLE
Most Custom Fizzler "Fizzler" Models Missing

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2330]
Most Custom Fizzler "Fizzler" Models are Missing.

this bug happens across all styles with Closed Solid Field, Physics Repulsion Field, Compressed Smoke Field, Matter Inquisition Field, Radiative Flux Rectangle, Force Deflection Field, and Physler.

![preview0008](https://user-images.githubusercontent.com/11165643/32148206-d2df2f0e-bcc9-11e7-8e4f-fd5df4f2ba67.jpg)

**Comment by Luke18033** [comment]
Somebody already reported this, I can't find the issue though. Anyway, it ended up being invalid because this is yet another issue caused by BEE not overwriting old resources after an update. To fix it, remove Portal 2 from the BEE2 game list and then re-add it. This will completely remove all BEE resources, meaning next time you export it'll copy over the new versions.

**Comment by Luke18033** [comment]
I don't think that'll fix the CSFi texture though, that bug is still present now.
