### ISSUE TITLE
Using conditions to apply gridded texture on wall of fizzlers doesn't work

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2340]
@TeamSpen210 - just compared the code of @LautaroL20's gridded wall and applied it in the vbsp config of my fizzler and modified it and the gridded texture is not being applied to the walls the fizzler is placed on...

i put the snippet of code needed at the end of the vbsp config file and nothing is happening in game...

"Fizzlers"
	{
		"Fizzler"
		{
			"ID" "WARIO_LCEF_FIZZLER"
			"Item_ID" "ITEM_WARIO_LCEF_FIZZLER"
			"Base_Inst" "<ITEM_WARIO_LCEF_FIZZLER:fizz_base>"
			"Base_Inst_static" ""
			"Model" "<ITEM_WARIO_LCEF_FIZZLER:fizz_model>"
			"Model_static" "<ITEM_WARIO_LCEF_FIZZLER:bee2_static>"
			"Has" "Fizzler"
			"Has" "wario_lcef_fizz"
			"Pack" "PACK_WARIO_LCEF_FIZZ_CLEAN"
			"Pack" "PACK_WARIO_LCEF_FIZZ_MDL_CLEAN"
		"Brush"
			{
			"Name" "fizz"
			"side_color" "2.55 1.1 2.55"
			"side_vortex" "2.55 0.50 2.55"
			"tex_center" "BEE2/fizz/lcef_fizz/lcef_center"
			"tex_left" "BEE2/fizz/lcef_fizz/lcef_left"
			"tex_right" "BEE2/fizz/lcef_fizz/lcef_right"
			"tex_short" "BEE2/fizz/lcef_fizz/lcef_field"
			"Keys"
			{
				"classname" "trigger_portal_cleanser"
				"spawnflags" "4096"				
				"visible" "1"
				"usescanline" "0"
				"StartDisabled" "0"
			}
			"Singular" "1"			
			}
		"Brush"
			{
				"Name" "fizz"
				"tex_trigger" "tools/toolstrigger"
				"singular" "1"
				"Keys"
				{
					"classname" "trigger_paint_cleanser"
					"spawnflags" "5199"
					"StartDisabled" "0"					
				}
			}
		}
	}
"Conditions"
{
"Condition"
{
"instance" "<ITEM_WARIO_LCEF_FIZZLER>"
"Result"
{
"AlterTex"
{
"Pos" "0 0 0"
"Dir" "0 0 -1"
"gridPos" "1"
"tex" "<4x4>"
}
"ChangeInstance" ""
}
}
}

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - The gridded wall code i used for my own items such as the Standing Fizzler, Reclined Fizzler, Gridded Wall, Protruding Ped Buttons, and Left-Middle-Right Ped Buttons are only for specific positions. 

This means that if the fizzler you are working on uses a part of the the Puzzlemaker´s code, the gridded offsets are supposed to be generated automatically, since this is not the case for almost all cuztom fizzlers that works with part of puzzlemaker´s code this means that Spencer needs to hack the excact result type from the original fizzler so all fizzlers can have gridded walls.

**Comment by ellingtonvengaboysmuseum** [comment]
this issue needs to be resolved in bee coding itself by @TeamSpen210
