### ISSUE TITLE
Find result type from the original fizzler to grid walls on all fizzlers

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#2343]
as @LautaroL20 suggested in my last post (before i closed it), the exact result type needs to be found on the original fizzler so all custom fizzlers can have 4x4 gridded walls...

also along with all custom fizzlers, the original fizzler needs to be set to handle 8 positions too, image shows what is happening when it is placed by default with handle 6 positions, that wall tiling is kind of but ugly... with 8 positions it will line up perfectly when the 4x4 tiling is correct

![preview0021](https://user-images.githubusercontent.com/11165643/32247357-71b13f84-be58-11e7-8694-f3f1607db7e7.jpg)

**Comment by Libbybapa** [comment]
I noticed the implemented tag on this and was curious, is the existing fizzler item going to be changed to an 8-position movement handle?

**Comment by Luke18033** [comment]
I think the plan for that was to have a stylevar option which would swap items with a 6-way handle (such as fizzlers and light bridges) to use an 8-way handle instead. That way you could use either, and existing items should even keep their position when switching handles.

**Comment by Libbybapa** [comment]
Am I right that a stylevar would not allow the use of both 8-position and 6-position items in the same map, correct? 
 
A while back I duplicated the light bridge package and changed all the necessary items so that I had both the normal 6-position bridge and the 8-position bridge (with different icon) in BEE and could add both to a palette and use both in the same map.  I just added a red 8 in the corner of the icon in order to differentiate.  That seems like an approach that would allow more options.

**Comment by Luke18033** [comment]
The problem is that your method requires duplicating every item with a 6-position handle, which isn't something we'd want to do. What I'm saying is that if you placed an item in the center position, then switched it to use an 8-way handle, it should retain that position even though it isn't selectable anymore.

**Comment by Libbybapa** [comment]
If I understand correctly then, you could set the stylevar, export BEE add fizzlers/light bridges with the 6 position handle, save map, exit portal, set the stylevar to 8, export, add other fizzlers/light bridges and have them stay in the positions you put them, allowing a mix of 6 or 8 position items.  Sounds good to me.  :)
