### ISSUE TITLE
How do I...

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2374]
How do I easily update to PRL27? I'm stuck on PRL25

**Comment by ellingtonvengaboysmuseum** [comment]
download both the packages and prerelease 27

**Comment by TeamSpen210** [comment]
Just download the new version, and overwrite your old one.

**Comment by LautaroL20** [comment]
@IceTudor - But to prevent Portal 2 from keep using old resources from past Beemod releases, once you installed the latest pre-release version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
