### ISSUE TITLE
Overgrown entrance/exit doors

### ISSUE THREAD

**Issue by 91Yugo** [BEEmod/BEE2-items#2414]
I have a problem with the entrance and exit doors. I hope you can do something for helping me :)

Entrance
![20171119201602_1](https://user-images.githubusercontent.com/33499533/33443697-7f4d54ea-d5f8-11e7-969f-066ac8ae39b4.jpg)
nce

And the exit door have a "black bar" that's block the wait
![20171130175404_1](https://user-images.githubusercontent.com/33499533/33443717-8cf1a16e-d5f8-11e7-978f-04ab8da1b98c.jpg)

**Comment by CaliMari** [comment]
I haved this kind of problem.But... i forgot the solution sorry.It was in pre-release 25 for me.

**Comment by 91Yugo** [comment]
I had the last version doesnt work too

**Comment by Luke18033** [comment]
This was fixed long ago, you probably just need to unmount/remount Portal 2.

**Comment by LautaroL20** [comment]
@91Yugo - This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
