### ISSUE TITLE
Two Bugs

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2426]
In bts if goo is placed low enough this happens :
![20171025130654_1](https://user-images.githubusercontent.com/29339358/34359046-96cf7c20-ea4c-11e7-995a-fdc0531057d8.jpg)

Portal 1 Laserfield does this :
![20171024094332_1](https://user-images.githubusercontent.com/29339358/34359060-b47b915a-ea4c-11e7-9ae6-d6114f6dddeb.jpg)

**Comment by CaliMari** [comment]
BTS is still a work in progress (WIP) so in the next release i think it is gonna be fixed.But the portal 1 thing IDK what happens.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
