### ISSUE TITLE
How to go about creating an item?

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2432]
I wanna learn to do this, and I'd just maybe make a new cube type with a different model, but how exactly would i create it? what language is it in and can u link me any sample code?

**Comment by SimonNightFox** [comment]
Hello Segemgames and I think I know the solution to the problem, maybe it will not work for you, but if you open HAMMER you will see items from BEEmod just delete these items, and zaminite their own, if you are a good programmer, I think you can do it .. I did so with the module, since my HAMMER did not work .... GOOD LUCK(I'm sorry but the text may contain errors, I'm Russian and i using a google translator

**Comment by LautaroL20** [comment]
If you want to create items for beemod or just for your personal use, first thing you need to do is learn basic knowledge at Hammer Editor. The basic language used for items which uses some aditional configuration that can not be done via Hammer Instances, is set in a file called `vbsp_config.cfg` and can be learned from the following page: https://github.com/BEEmod/BEE2-items/wiki/vbsp_config

Also, for a good example of how a bee item work, you should unzip one of the bee´s items packages to see how text files, configurations and folders interacts which each other there. Also, for assistance you can use the bee´s discord chat room where you can get instant help: https://discord.me/beemod
