### ISSUE TITLE
Portal Gun obtained from pedestal disappears when loading a save

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2-items#2436]

**Comment by toncica2** [comment]
I just noticed this bug in prl27 and it's still there in prl28. It's worse than described because the player ALWAYS spawns without a portal gun, no saving or dying is possible in such a map without losing the portal gun. "give_portalgun" gives me the blue portal gun but I would need the orange portal gun in this case. Is there a workaround?

**Comment by TeamSpen210** [comment]
It must be my VScript I wrote to do the spawning, and on/off buttons.

**Comment by toncica2** [comment]
Is there anything I can do to make a single map playable? The map is huge and can't be completed by a normal human being without dying/loading.

**Comment by TeamSpen210** [comment]
@toncica2 What portal-related items are you using (Pgun buttons, pedestals, autoportals)? Check the second commit (ac25e765294edae74f091d770817e5e7bbe9dbae), and edit `Portal 2/BEE2/scripts/vscripts/portal_man.nut` to stop it doing this (hopefully).

**Comment by toncica2** [comment]
@TeamSpen210 That fixed it. I had blue and orange autoportals and pedestal guns with the orange portal gun being acquired first. Thanks for the quick work.
