### ISSUE TITLE
Suggestions for PRE-28

### ISSUE THREAD

**Issue by CaliMari** [BEEmod/BEE2-items#2438]
-Panel Light Bridge
-Custom Music
-Overgrown Decorations (Broken Walls,Ceiling broken with sky,etc.)
-Living Panels + Large Living Panels (Broken option with Start Reversed,working on all styles)
-Wheatley Style and Bottomless Pits
-Platforms with Portal Surface,Metal and Portal Surface with AutoPortal
-Panel AutoPortal
-Small Water Pools (Maybe in the decorations)
  
EDIT 1 : Bottomless Pit --> Bottomless Pits

**Comment by ZombiePwner1** [comment]
@CaliMari We already have custom music... And we won't beable to add all of this style in one release.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by CaliMari** [comment]
Then how can i do suggestions? @LautaroL20

**Comment by LautaroL20** [comment]
Just read the guidelines for this repository, [here](https://github.com/BEEmod/BEE2-items/blob/master/.github/contributing.md).

**Comment by CaliMari** [comment]
@LautaroL20 oh!sorry!i thought contribution is if you want to join the team and make content and test alpha/beta versions and etc. sorry :grin:
