### ISSUE TITLE
Portal 1 Style Fizzlers do not disable particles when disabled

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2467]
This button here:
![20180127091901_1](https://user-images.githubusercontent.com/25313980/35474466-764a6c02-0343-11e8-8a93-8a3bb370e2e9.jpg)

Is powering down this fizzler over here:
![20180127091849_1](https://user-images.githubusercontent.com/25313980/35474469-80950a32-0343-11e8-98a3-1d22f8266a7b.jpg)

This fizzler, in fact, is inactive, and does not fizzle cubes brought through it.
However, the particle field does not go away.

**Comment by cartman1337** [comment]
I got curious about this one, since I hadn't run into this problem myself. It seems the problem is limited to fizzlers with a width of 1 block:
![Deactivated fizzler 1 block wide](https://i.imgur.com/tESfptO.jpg)
It seems active, but is as Endermage77 said inactive, and I've portaled through to prove it.

Fizzlers 2 blocks wide or wider deactivates correctly:
![Deactivated fizzler 2 blocks wide](https://i.imgur.com/j69AhCx.jpg)

**Comment by Nikita74RU** [comment]
Didn't fix for me!!
