### ISSUE TITLE
The option for cube disolver

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2514]
Add please the option for cube dissolver for it to generate the emitter model under itself. The the test subject will understand that it's trigger there.
![20180220152516_1](https://user-images.githubusercontent.com/35931028/36426748-ce2074da-1653-11e8-8650-b4ae0e8d3fb0.jpg)

**Comment by cartman1337** [comment]
Maybe with an option to make it look like the cube incinerator from one of the old Beemods?

**Comment by SCIENTIST2004** [comment]
i mean cube dissolver but not incinerator

**Comment by cartman1337** [comment]
Yes I know. My point is that, despite looking very different, they do exactly the same job; destroy the cube, send an output, and take up one block of space, and since it's possible to have different models of the same item, selectable as "cube type" in the editor, why not implement both items as one? With the option to add even a third, fourth and fifth cube destroyer model if needed.

**Comment by Endermage77** [comment]
Ah, you see, the difference between the two is that the incinerator would take up a fair amount of embedding space in the floor, for the hole underneath. 

However, you can still classify them as the same object, except you'd have to make it a itemvar swap instead of a stylevar.

Although, the thing in the image given looks like an excellent style swap for a BTS item.

**Comment by TeamSpen210** [comment]
It's not supposed to be visible at all. It's a trigger, which is used between chambers to reset the gun. On that note, I need to add it an an Absolute Fuzzler to the Chamberlock item.

**Comment by LautaroL20** [comment]
This is intentional then.
