### ISSUE TITLE
It is broken???

### ISSUE THREAD

**Issue by Skrublord54** [BEEmod/BEE2-items#2524]
I was downloading Beemod and none of the versions worked
So I went and wasted 2 hours of my time downloading all of them and when I opened portal 2...
nothing changed
I got so triggered that I almost threw my laptop
PLEASE HELP ME!!!!!!!

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by TeamSpen210** [comment]
Did you actually export anything to the game? It doesn't do anything until you run it.

**Comment by Skrublord54** [comment]
THANK YOU SO MUCH

one last problem
beemod will not open...  ('-')

**Comment by Endermage77** [comment]
Here's a rudimentary guide to launch BEE2-modded Portal 2, assuming it's all in order:
1. Download the mod file and the packages file. Extract both and put the contents of the packages file (The "packages" folder) in the BEE2 folder.
1. Find the BEE2.exe file, located in Bin, located in the main BEE2 folder, and launch it.
2. Assemble a palette by dragging items from the middle to the area on the left.
3. Open the little menu buttons above the palette (left area) and find all the options like Voiceline and Skybox and Style and all those cool bells and whistles.
4. Click "File" in the very upper left corner and click the option called "Export." This exports the palette to the editor and replaces the game's items with yours. It also launches the game, too.

I assume, if those steps don't work, that BEE2.exe doesn't work, yes?

**Comment by Skrublord54** [comment]
and last time that Beemod worked, the auto portal spawned in the corner of the chamber mostly under the floor
