### ISSUE TITLE
Rocket turret doesn't show up in any of the "Old Aperture" styles

### ISSUE THREAD

**Issue by gps05** [BEEmod/BEE2-items#2540]
What it looks like in-game:
![preview0005](https://user-images.githubusercontent.com/37035342/36944831-e61b50e0-1fcd-11e8-929d-52e757227f29.jpg)
What it looks like in the editor:
![20180304170157_1](https://user-images.githubusercontent.com/37035342/36944834-f7aed2b4-1fcd-11e8-9505-319722e2ce67.jpg)

**Comment by Endermage77** [comment]
The rocket turret is one of the less functional items in BEE2 right now. This post, for instance, or perhaps also taking into account its abysmal accuracy (Ignoring the slow turn speed, which is normal) when it functions correctly, even if the player is standing still.

**Comment by ZombiePwner1** [comment]
@gps05 Yes the rocket turret is very bugged right now and we are still trying to fix it.

**Comment by Luke18033** [comment]
Checked this out, the reason it happens is actually pretty simple and stupid - the turret instance has all of the global logic, including the nodraw box around it which would cull out the turret. You aren't seeing any void effects here since it doesn't touch any of the brush faces, but if you were to noclip in there the turret would appear. I'm not sure why there's even a separate variant for this style, it's identical to the Clean version aside from this.

**Comment by TeamSpen210** [comment]
Must have typoed addglobal → addoverlay

**Comment by Luke18033** [comment]
No, it's literally a part of the instance itself...

**Comment by Luke18033** [comment]
There's a separate logic instance which also gets added properly

**Comment by Luke18033** [comment]
Should be fixed in the geometry branch.
