### ISSUE TITLE
Error with building the puzzle.

### ISSUE THREAD

**Issue by TheBurninator** [BEEmod/BEE2-items#2544]
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198058696039\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 41 (ms)
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "@��v�b��"

VBSP failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)

[

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
