### ISSUE TITLE
New item: Wall button with arrow

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2551]
As always I have no clue if this is possible to make without hammer, but the following button would be nice to have if it is even doable.
<img width="125" alt="button" src="https://user-images.githubusercontent.com/33907318/37247958-0b99d4a8-24c5-11e8-8ab8-10c7fdcda4fc.png">

**Comment by ZombiePwner1** [comment]
Yes it's doable.

**Comment by Cellolide** [comment]
That would be a nice addition then, but definitly something that is highly need.

**Comment by Endermage77** [comment]
I like the idea of a wall button in general. For example, in puzzles where a push button is on the ceiling such as in the first puzzle of chapter 7, it would be helpful to be able to put a button straight overhead rather than mounted on an awkwardly placed pedestal.

**Comment by TeamSpen210** [comment]
Doesn't really fit inside a chamber.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
