### ISSUE TITLE
Animal King, Rocket Turret, Some of the fields, Sendificator

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2552]
Animal King wont activate. If someone could help me. Please comment.
Rocket turret wont turn. it just stays in place and I cant connect it to anything. Not even if I disable it.
Some of the fields dont have correct texture. and the Sendificator is confusing

**Comment by TeamSpen210** [comment]
What version are you using? The Animal King never existed in BEE2.4.

**Comment by Endermage77** [comment]
This sounds like the BEE2.5 alpha version, yes.
1. Animal King no longer exists, and will not be coming back to the newer versions.
2. Rocket Turret is still buggy in the current version, but some styles such as P1 do feature functional turrets (With miraculously absent accuracy).
3. Most of the fields are fixed in the current version, and documentation is available for sendificator usage on the good old wiki which is available up in the tabs above.

**Comment by LautaroL20** [comment]
The Animal King would be absolutely useless having it in Bee 2.4, it is something that should be adchieve thru hammer for maps with custom storylines.
