### ISSUE TITLE
Leaks in '50s Office Observation Room

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2556]
These are minor issues that are only visible by using noclip, but nonetheless should probably be fixed. Behind the doors in the room and to the right of the window inside the room, I discovered some texture leaks. Here are some screenshots for context:

![preview0016](https://user-images.githubusercontent.com/23202923/37319661-4ab54b68-262d-11e8-82a7-d31b3a8953b5.jpg)
Oddly, it looks in the first one like the leak only happens in the goo pit and the small alcove in the opposite wall. (It contains nothing but cold strip lights and a repulsion gel dropper.)
![preview0017](https://user-images.githubusercontent.com/23202923/37319663-4e190c04-262d-11e8-895b-4f60d9a8385b.jpg)

**Comment by Luke18033** [comment]
There's nothing to fix here. The surfaces can't be seen without noclip, so they don't need to be textured.

**Comment by TeamSpen210** [comment]
Those aren't leaks. I know that players aren't able to get in there, and so those surfaces are left blank so the game doesn't waste time drawing them. The repulsion gel area isn't drawing because the compilers were able to determine that you cannot possibly see that area from your current position, and so it isn't being drawn.

**Comment by Neightro** [comment]
I have to be honest; that is a little unprofessional. Nowhere in the official Portal 2 maps are there missing textures, even where you can never see them. I strongly doubt that leaving leaky surfaces would improve render times that much, even over solid black surfaces.

**Comment by TeamSpen210** [comment]
Yes there are. Go into a Wheatley map, say, and fly outside. And it's not a leaky texture, it's the lack of a texture leaving whatever was rendered in the last frame still visible.

**Comment by Neightro** [comment]
I was interested to see what you were referring to, so I looked around a few Act 4 maps, but the only one I've found so far that doesn't have a skybox (sp_a4_tb_intro) just has a white void. Maybe it was patched?

**Comment by TeamSpen210** [comment]
Keep in mind you can't see it, since the texture is invisible. But here's an example:
![nodraw_example](https://user-images.githubusercontent.com/8453732/37380303-ff4ea972-272f-11e8-8338-e2916529be12.png)
Going above the ceiling shows that there's no texture on the backside of these walls, since you can't see those. Valve is actually pretty lazy with this, and doesn't apply `nodraw` a lot of the time when they can.
