### ISSUE TITLE
Co-Op Camera+Monitor Crash

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#2582]
Whenever I use a Screen Camera and a Monitor in this Overgrown Co-op map I'm making. It crashes.

**Comment by LautaroL20** [comment]
You must attach at least one screenshot to help us understanding what do you mean, since the description is not clear.

**Comment by Luke18033** [comment]
As I said in the other issue, the camera/monitor functionality might be broken in multiplayer in which case we can't fix it.

**Comment by Luke18033** [comment]
Can confirm the camera/monitor entities are not the issue here. Here's a screenshot of my normal monitor instance working perfectly fine in splitscreen Co-op.
![image](https://user-images.githubusercontent.com/19228201/85070760-38c0d500-b16b-11ea-9711-47f04e070475.png)
If I use the BEE2 monitor instance instead, the game instantly crashes. I'm going to look into this.

**Comment by Luke18033** [comment]
Okay, the problem seems to be caused by setting a target entity in the `ai_script_conditions`. That's used for detecting when players look at the screen to deploy it. I'll see if I can get it to work in a different way, or just switch it to deploy when entering the map.
