### ISSUE TITLE
Create the item magnet and Specific cubes for different purposes like in blue portals and also make the item gravity gun like in the multiverse (the custom map series)

### ISSUE THREAD

**Issue by AlexBaker2648** [BEEmod/BEE2-items#2587]
Create the item magnet and Specific cubes for different purposes like in blue portals and also make the item gravity gun like in the multiverse (the custom map series)

**Comment by Luke18033** [comment]
See #2139 for Blue Portals stuff. We're probably not going to implement the ITM gravity gun.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.
