### ISSUE TITLE
Green High Energy Pellet launcher editor model does not have a selectionmesh, and therefore it is using a wrong one which is being generated by the editor.

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2605]
Lautaro: "The pellet launcher editor model does not even have its own selection mesh at all as i was able to check this. Basically, since the editor model does not have a selection mesh, it is using one provided directly by the puzzlemaker, which is an ordinary box"

![Half-Life 3 Unconfirmed](https://user-images.githubusercontent.com/12244376/38170347-e0df47c0-3559-11e8-9d85-071c93795f4d.jpg)

**Comment by LautaroL20** [comment]
The info is wrong. In the first place, the pellet launcher editor model does not even have its own selection mesh at all as i was able to check this. Basically, since the editor model does not have a selection mesh, it is using a default one provided directly by the puzzlemaker, which is an ordinary box. In order to draw the selection meshes, you need to type in console:`puzzlemaker_drawselectionmeshes 1`

![Half-Life 3 Unconfirmed](https://user-images.githubusercontent.com/12244376/38170347-e0df47c0-3559-11e8-9d85-071c93795f4d.jpg)

**Comment by SCIENTIST2004** [comment]
@LautaroL20 The info is wrong. In the first place, the pellet launcher editor model does not even have its own selection mesh at all as i was able to check this. Basically, since the editor model does not have a selection mesh, it is using a default one provided directly by the puzzlemaker, which is an ordinary box. In order to draw the selection meshes, you need to type in console:puzzlemaker_drawselectionmeshes 1

thank you
