### ISSUE TITLE
Ripped in two parts chamber.

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2609]
Like a old test chamber, 
https://youtu.be/3RBpeeP7_s0

**Comment by TeamSpen210** [comment]
That is not ripped in half, and this is very difficult to do.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

**Comment by LautaroL20** [comment]
Do not add aditional labels such as "ehnancement" when the issue is invalid/duplicate, if you want. But it really matters the "invalid" or "duplicate" labels, to clarify the reason of its clousure.
