### ISSUE TITLE
I have some suggestions

### ISSUE THREAD

**Issue by emeraldore22** [BEEmod/BEE2-items#2613]
1. More decorative elements. Things like rubble or destroyed panels could be very effective for the overgrown and old aperture segments. Also perhaps some broken panels. I may also note that a test chamber is not a test chamber without some sort of detail/decor, especially in old aperture which looks more new than old in chambers I have seen and created.

2.More announcer lines. There is around 10 minutes of announcer lines in the game, you should be able to use all of them.

3.A full dialogue selection list. Sometimes when testing if my chamber works, I would come across the same line for multiple chamber designs, a little annoying and would be helpful if you could pick which line or lines to use and at what time.

4.More diversity for observation rooms. What I mean by this is in overgrown test chambers add the ability to portal in and out of them. 

5.Sequences. By sequences I mean something like a rail or beam falls through the chamber at one point creating rubble. Would be for overgrown and old aperture styles. Sequences could also include but not limited to large rumbles to imitate shaking.

Tbh I just really want more decorative elements as I am tired of having to use the minor decorative elements, good mod though, it really opened my eyes to how certain elements could do a certain amount of things.

**Comment by Endermage77** [comment]
1. Test chambers without decor, I'm pretty certain, are still test chambers. Their function is to test a scenario involving things, no matter how drab it appears to be. Still, you raise a good point, since if that were the case then there'd be no point in adding styles to this mod.
2. Sure.
3. Useful. Been suggested multiple times, TSpen doesn't want to do that because he thinks that's what Hammer is for. If you mean you want to choose exactly what lines to play and when during-chamber rather than in-the-editor.
4. TSpen doesn't really want players to go into the observation rooms. It would break some maps. Additionally, it is possible to portal into the observation rooms anyway via portal-bumping.
5. TSpen would probably never let this fly, because this also fits his category of what should be done with hammer anyway like #3.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
