### ISSUE TITLE
3 bugs

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2624]
1. in old aperture the entry door is invisible:
![20180405225420_1](https://user-images.githubusercontent.com/35931028/38389126-2098c48e-3926-11e8-84af-b7e4dc54b373.jpg)
2. sometimes all test chamber disapears or becomes invisible in a mysterious way when i scroll up maximum:
![20180405230113_1](https://user-images.githubusercontent.com/35931028/38389391-fbd532a8-3926-11e8-8959-f23aa93fee6c.jpg)
3. if a test chamber has a signage, an error will happen

**Comment by Luke18033** [comment]
1. Already known, although I think it was reported on Discord so there's no issue for it.
2. That's a Valve bug, I've heard of it happening in the default editor and BEE2 wouldn't even be able to change something like that.
3. What style? This is already known to happen in Portal 1. Also post the console log.

In the future, please don't combine unrelated issues, it means we can't individually label and close them.

**Comment by SCIENTIST2004** [comment]
@Luke18033: What style? This is already known to happen in Portal 1. Also post the console log.

1960

@Luke18033: In the future, please don't combine unrelated issues, it means we can't individually label and close them.

ok.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
