### ISSUE TITLE
New Item: Motion Sensor

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2657]
a new item that is a type of switch: a Motion Sensor

it would be basically a sensor that triggered whenever a player was within a style var determined range of motion and would power whatever it was connected to upon detecting player or cube movement. also a cube could be used to block its line of sight. it could be instant on and off after motion was not detected or it could have a countdown timer which would be set and determine how long before whatever it was powering would lose power. also if the player was within the range of detection and stopped moving, the countdown would not reset until it detected motion unless the fine motion stylevar was true which means it would always reset the timer whenever a player or cube moved within it's detection range.

a example simple puzzle for such a item would be one where the player had to carry a cube through a test chamber which had a motion sensor near the exit door set to close the exit door upon motion detection. they had to place the cube in front of the sensor to block it's line of site to keep the exit door open...

to make this you would need triggers that would detect a moving player / moving cube and a small cube detecting trigger very close to it that disabled the main player detecting trigger whenever the cube was within it (blocking it's line of sight)

there should be 3 variants with configurable ranges of detection

- [ ] one like a camera (which picks up motion where ever it is facing in it's range of detection)
- [ ] one like a ceiling motion sensor that has a round range below it
- [ ] one like a lutron maestro motion sensor which would be wall mounted and has a half circle range in front of it

it would have a few controls and style vars

- [ ] a stylevar that determines if it is on / off when finding motion or uses a timer
- [ ] a countdown timer until it deactivated after it detected motion
- [ ] a stylevar to detect fine or coarse motion
- [ ] a stylevar to set the radius it detects motion in

**Comment by HugoBDesigner** [comment]
I don't think it should have a timer of its own. It could be done with the Delayer item. It'd be better, in my opinion, to let it only go on and off. This "new item" could, perhaps, be a variant of the camera itself. The Turing Test actually has a puzzle element like that:
https://youtu.be/FxuJwjrAuXU?t=678

The ceiling one just sounds to me like a trigger placed from the ceiling to the floor, which is already doable. The others seem interesting enough to be kept. I think it'd be preferable if the item could just detect player presence, rather than movement. If the player is in line of sight, it triggers, regardless of whether they're moving

**Comment by Konclan** [comment]
I have no idea what this would be useful for. Just sounds like triggers with extra steps.
