### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by SametKayaTr** [BEEmod/BEE2-items#2701]
İtems Looking Like Errors Help Me

**Comment by Konclan** [comment]
First what you’re gonna want to do is post more details like pictures or logs cause uuuh we don’t know what you’re talking about. We can’t assume to know the problem.

**Comment by HugoBDesigner** [comment]
I really hope you're not planning on posting your bingo on every issue that makes you check a square

**Comment by Nikita74Russian** [comment]
@HelloLama, do not check Nikita74Russian makes a dummy question too many times, because when you want me to be shamed, you will be.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
@HugoBDesigner - I really hope you'll pin directly TeamSpen210 through Discord in the future asking to ban people who bypass the first ban, to prevent our email inbox to be filled up with tons of spam comments instead of crossing your arms and leaving it to keep happening all over the issues. It seems strange that a little comment whose situation to be generated is limited, makes you annoying after the spamming situation we gone through...
