### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2754]
I noticed that a new bee mod release came out every 4 monthes. and 4 monthes have already passed.
so a new releases hasn't come out because of summer?

**Comment by ZombiePwner1** [comment]
@SCIENTIST2004 It takes time for each release to come out as new content is added in each release.

**Comment by LautaroL20** [comment]
Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
