### ISSUE TITLE
Very Strange Bug

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2756]
in Editor:
![20180717003637_1](https://user-images.githubusercontent.com/35931028/42814098-d81425ae-89cb-11e8-86b0-f4b5f3c99a58.jpg)
In Game:
![20180717003815_1](https://user-images.githubusercontent.com/35931028/42814118-e23e34f2-89cb-11e8-909b-3599053c094e.jpg)
I Chose a Clean style

**Comment by LautaroL20** [comment]
That is caused by exporting the bee´s palette when the game is running. To prevent this from happening, make sure that Portal 2 is closed, then choose the desired style & items and export it, then launch the game and this issue will not happen.

**Comment by SCIENTIST2004** [comment]
But this happens even if portal 2 is closed

**Comment by LautaroL20** [comment]
Then try this:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by SCIENTIST2004** [comment]
Thanks

**Comment by LautaroL20** [comment]
You re welcome.
