### ISSUE TITLE
Pistons not behaving correctly PR29

### ISSUE THREAD

**Issue by ChaoSpawN** [BEEmod/BEE2-items#2772]
I have the same issue as is described here, with a different setup:
https://github.com/BEEmod/BEE2-items/issues/2636
So this has unfortunately not been fixed completely.

Using v2.4.0pr29 and matching packages. Original Clean style.

Only difference between my setup and the above setup is that in mine the piston platform is connected to a standard pedestal button with a 5s timer, and 'Autodrop First Cube' is disabled. 
Upon pressing the button the first time, nothing happens. Second time it goes down one block, etc just like in the above thread.

**Comment by Luke18033** [comment]
If you knew the issue had already been reported, why did you open a duplicate? It specifically says in the [contributing guidelines](https://github.com/BEEmod/BEE2-items/blob/master/.github/contributing.md) not to do that even if it's a major bug/has been forgotten about/whatever the reason is. It's been fixed in the next release, use a NOT gate as a workaround until then.

**Comment by ChaoSpawN** [comment]
Wow, sorry man. That thread was marked closed so I assumed I couldn't post there anymore. Please forgive my insolence...
