### ISSUE TITLE
The rocket turret and other stuff

### ISSUE THREAD

**Issue by ohyesss** [BEEmod/BEE2-items#2812]
Ok. so one, the rocket turret's rockets are only visible when you are far from it. And two, it just doesn't work in any of the old apertures. And also the clean and original clean elevator does not trigger the workshop vote page.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
