### ISSUE TITLE
The piston platform in 1950s theme shows as a "Blue Error"  for non-beemod users

### ISSUE THREAD

**Issue by Venima** [BEEmod/BEE2-items#2813]
![Blue Error](https://user-images.githubusercontent.com/12244376/44689585-65ec4280-aa2e-11e8-9c65-73c0f4b1457e.jpg)

**Comment by LautaroL20** [comment]
I will do some self playtesting to see if it also happens to me too, because i really dislike missing model issues. Stay tunned.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
