### ISSUE TITLE
More effective Turret & Turret skin

### ISSUE THREAD

**Issue by UncleEle** [BEEmod/BEE2-items#2817]
In some chambers, turrets are used as an obstacles that you need to remove but sometimes
the player skip the phase with b-hop that in the most of the case isn't an intendeed solution.
Lately i play PS: Mel and i notice that turret are REALLY more powerful than the classic one's
So my suggestion is to add a tutter that inflict more damage or less by setting it from item 
section of bee mod
Another suggestion is to add a possible to set a skin for turrets from the same section
![thing](https://user-images.githubusercontent.com/38593922/45650437-932c8d80-bace-11e8-9173-a51419beab5d.png)

**Comment by ZombiePwner1** [comment]
@UncleEle Damage we can do but the skin side of this we cannot add as the turret's model doesn't have any skins.

**Comment by Luke18033** [comment]
That's not the problem, we can easily pack in a custom model with extra skins. The problem is that the alternate skins don't actually exist anywhere in the files, so someone would need to make them. I also don't think turret models can have more than 2 skins each, since 3-6 need to be used for gels.

**Comment by Luke18033** [comment]
Super-damage turrets have already been suggested in #1150.
