### ISSUE TITLE
PR.30 Unstationary Scaffold Items 

### ISSUE THREAD

**Issue by Overwatch-C-17** [BEEmod/BEE2-items#2823]
All of Unstationary Scaffold Items emit fullbright on the model, like texture with mat_fullbright 1. (That console command still off in fact)

**Comment by LautaroL20** [comment]
For being the first time, ill open a separated issue for the bug which makes the random PETI music not working at all, just by you.

Remember to read the guidelines that says:

"If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be."

**Comment by Overwatch-C-17** [comment]
Understood
