### ISSUE TITLE
PRL30: Angled Panel inputs do not work

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2824]
![prl30 bug](https://user-images.githubusercontent.com/12244376/46572855-300e7800-c963-11e8-9ec6-f49be7b37827.jpg)

So in my recent map i've now published to test out PR30 and BMMC (which is for some reason 98 MB for a simple map literally smaller then the normal sized PeTI maps) Angled Panels did not respond to any futbol or logic gate inputs.
 I have reason to believe this is an error with Angled Panels. as the Futbol and Logic gates worked with other items. Such as the light bridge.

As for the 98 MB file size. I will keep you all posted in either the discord or in issues 😄

**Comment by King0191** [comment]
![20181005233415_1](https://user-images.githubusercontent.com/37309250/46566986-53034280-c8f7-11e8-819d-ea70a6c38455.jpg)
![20181005233417_1](https://user-images.githubusercontent.com/37309250/46566987-53034280-c8f7-11e8-9d6b-a32a73713a35.jpg)

**Comment by LautaroL20** [comment]
>  King0191 said: "Maps made with PRL30 are for some reason 98 MB for a simple map literally smaller then the normal sized PeTI maps." 

This is a MASSIVE BUG if that is really happening, if you are sure it does not have to do with BMMC, then open a separated new issue for it, please.

**Comment by LautaroL20** [comment]
I can confirm that this bug occurs, and with all type of connections:

![prl30 bug](https://user-images.githubusercontent.com/12244376/46572855-300e7800-c963-11e8-9ec6-f49be7b37827.jpg)

**Comment by LautaroL20** [comment]
I have done aditional testing, and in order to solve this issue, everyone must have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise issues will occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
