### ISSUE TITLE
HUGE issue with Exursion Funnels and Potentially Pellet Catcher and Triggers

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2829]
Triggers don't activate Exursion Funnels. I know this is exclusive to triggers due to buttons and floor buttons activating them. but NOTHING that i've tried (buttons, floor buttons, triggers, and pellet catchers) cannot change the polarity of a Funnel. So triggers. and funnels are for SURE broken. However Pellet Catchers are a potential broken item.

**Comment by TeamSpen210** [comment]
I can't reproduce this, it seems to work perfectly fine.

**Comment by LautaroL20** [comment]
Guidelines says: "If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be."

By the way, i think that what really happens is this, where the issue is explained in more details, here: https://github.com/BEEmod/BEE2-items/issues/2837
