### ISSUE TITLE
Conductive Plates doesn´t "Conduct"

### ISSUE THREAD

**Issue by TheSpacedOutEgg** [BEEmod/BEE2-items#2836]
I realise this is a new mod, but this glitch somewhat bothers me..

I like to use conductive plates as an alternative for normal floor buttons, but they don't seem to be conducting any sort of power. I even hooked a Trigger Once up to it and put it near the entry door, and it STILL doesn't work.

**As shown by the image below, the conductive plate isn't transferring a signal to the turret dropper in any way, shape, or form:**

![20181011155120_1](https://user-images.githubusercontent.com/42051142/46845005-59c60580-cd8e-11e8-8e14-d9356fb4ddbd.jpg)

If the image doesn't appear, tell me, and I'll try to re-upload it.

**Comment by ZombiePwner1** [comment]
@TheSpacedOutEgg Strange. Also the mod has been out for a long time now but the release for version 30 however is new.

**Comment by TheSpacedOutEgg** [comment]
Well, until the latest release is cleaned over, I think I'll be sticking with PR29.

**Comment by Endermage77** [comment]
The conductive plate may need to Start Enabled in order to work.
You see, it essentially is a button that needs an input to work.

**Comment by King0191** [comment]
Well you see, @LautaroL20. People like me have followed those instructions and still have issues with arm panels and conductive plates. and Preserve Game Directories isn't even automatically turned on. 
So this is a problem

**Comment by LautaroL20** [comment]
@King0191 - If @HugoBDesigner or other collaborators such as Luke18033 does confirms that those issues you mentioned are indeed happening with PRL30, i bow to you, then to ask you pardon on knees and ill automatically re-open all those issues. I know what i am saying and i am sure your mentioned issues has only to do with a wrong way of installating Beemod.

BTW, ZombiePwner1 does not count as a "collaborator" since he actually has never collaborated in anything with the development of Beemod and he´s actually kinda rookie at installing Beemod properly.

**Comment by LautaroL20** [comment]
@HugoBDesigner - Ive also tested the other issues before closing them, and they has only to do with a wrong way of installing a new Pre-Release. It is probably related to resources from past releases that ends mixing up the compiler files from PRL30. That is why i always make sure to paste on the closed issues my pre-made message with the specific steps to follow in order to help users to fix those issues which are not true bugs.
