### ISSUE TITLE
Fizzler Suggestion

### ISSUE THREAD

**Issue by OceanWaves999** [BEEmod/BEE2-items#2867]
It would be cool to have a fizzler that when walked through, remotely fizzles all cubes 
in the map. It could be used as a corrector. like if someone someone gets a cube stuck somewhere and
can't get it back, you can go through it and reset the cube.

**Comment by LautaroL20** [comment]
As @King0191 said, a pedestal button to respawn the cube is what you need in a cube stuck scenario. The fizzler suggestion for that purpose is pretty bad, We already have a lot of suggestions that many of them will never be implemented due to life´s duration (80 years as most if you are a careful person). If someone really wants to suggest something, make sure it has a reasonable logic and that really worths it.
