### ISSUE TITLE
Possibility of manually re-implementing old BEE2 Items?

### ISSUE THREAD

**Issue by MeloettaRules28** [BEEmod/BEE2-items#2888]
For instance: The Living Panel. If you would grab the package file from the old BEEMod and bring it in the new BEEMod packages folder, would the item work?

**Comment by Luke18033** [comment]
No. Why else do you think everything has to be ported? The format is completely different. You could probably make a tool to auto-convert BEE2.2 stuff to BEE2.4 packages, but you'd still need to edit it manually if you wanted to take advantage of any of the new compiler functionality.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
