### ISSUE TITLE
How to make water without coop as an issue

### ISSUE THREAD

**Issue by DylanKTV** [BEEmod/BEE2-items#2890]
I have and idea which is very simple. simple to the gratings that cant work in co-op just say in the description DO NOT USE IN COOP. I mean its the simple way out of it unless you want to go the extra mile and try to make it work for coop or just to scrap the idea.

**Comment by Luke18033** [comment]
What? If you're referring to the death animation with non-deadly water, there's a simple solution to that, which is to just make the water deadly in Co-op maps. (But not in SP obviously, otherwise it would just be goo with a different texture.) We'd probably want to make it appear electrified or something, so there would be some sort of indication that it kills you. Of course, swimmable water really isn't the top priority right now, so it's probably not going to happen for a while, if at all.

**Comment by ZombiePwner1** [comment]
@Luke18033 You know how swimmable water reacts in coop right?

**Comment by Luke18033** [comment]
I've never seen it, but I've heard from a few other people that the players get stuck in an infinite death animation loop.
