### ISSUE TITLE
Overgrown does not compile EVEN IF THE MAP IS EMPTY!!!

### ISSUE THREAD

**Issue by DrPipBob** [BEEmod/BEE2-items#2917]
Portal 2 does not want to compile an overgrown map even if the map is empty.
![20190225195310_1](https://user-images.githubusercontent.com/47915535/53354256-75920880-3937-11e9-9154-20293a5eeed1.jpg)
![20190225195329_1](https://user-images.githubusercontent.com/47915535/53354257-75920880-3937-11e9-828f-0af19b2717ef.jpg)
VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is D:\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.load_config(): Loading Settings...
[I] vrad.load_config(): Config Loaded!
[I] vrad.main(): Final status: is_peti=True, edit_args=True
[I] vrad.main(): Reading BSP
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Adding special packed files:
[I] vrad.main(): Injecting "scripts/vscripts/BEE2/mon_camera_args.nut" into packfile.
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScriptCode Strings"...
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogMaxDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogStart" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "startDisabled" for ent of type "prop_dynamic_override"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown class "playtest_manager"!
[W] packlist.pack_fgd(): Unknown keyvalue "parentname" for ent of type "point_teleport"!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "vrad.py", line 861, in <module>
  File "vrad.py", line 790, in main
  File "F:\Git\srctools\srctools\packlist.py", line 633, in eval_dependencies
  File "F:\Git\srctools\srctools\packlist.py", line 720, in _get_material_files
  File "F:\Git\srctools\srctools\packlist.py", line 180, in pack_file
ValueError: No tabs are allowed in filenames ('materials/models\\\\props_bts\truss.vtf')
WARNING: File "materials/maps/preview/nature/water_glados_01_cheap_-2400_0_0.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/metaldoor_white01_-1904_2096_-48.vmt" does not exist!

**Comment by LautaroL20** [comment]
In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!
