### ISSUE TITLE
Pin an issue that holds all ideas for new testing elements, and new variations of items that people have suggested

### ISSUE THREAD

**Issue by kdabest2** [BEEmod/BEE2-items#2960]
basically what it says.

**Comment by LautaroL20** [comment]
No, each suggestion must stay separated in order to close each one while they are being implemented.

**Comment by Luke18033** [comment]
No, I think this is meant to be something different - a regularly-updated pinned issue with links to individual issues for things people have suggested. If you wanted to suggest something, you would look through there first to see if there was already an issue for it. There's really no need for this though, since you can just do a search.

**Comment by TeamSpen210** [comment]
We also have 200 "new item" issues open.
