### ISSUE TITLE
[new feature idea]

### ISSUE THREAD

**Issue by Vortetty** [BEEmod/BEE2-items#2963]
I think the ability to add your own item stacks would be cool, does anybody know how to implement this? i want to do this so i can fit more in my editor, however i only know basic python and batch programming, so i can't do it myself. i also currently am inexperienced when it comes to writing game code, otherwise i would just write the code myself

**Comment by Luke18033** [comment]
What do you mean by "item stacks"? We can't expand the palette, if that's what you're asking. See [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ). It is possible to combine items like with buttons, triggers etc. but they need to share the same properties and editor collisions, so it doesn't work for most stuff.

**Comment by Vortetty** [comment]
not expanding the palette, i was hoping i could do something like the cubes, where you have a selector, but be able to have say, the 2 fizzlers, and the force field all in one item, or add the mirror gel to the rest of the gels. so i could maximize the efficiency of the palette without expanding it.

**Comment by xXThePortalMasterXx** [comment]
sounds cool, but you would only be able to fit about 6 things into one slot i think. so maybe that could work idk

**Comment by Vortetty** [comment]
ok, i was wondering, just wanted to see if it was worth it to learn the code just to do this, but if it is possible, i may try, thank you for your quick reply.

**Comment by TeamSpen210** [comment]
This can’t be done as a general feature.

**Comment by Vortetty** [comment]
what do you mean by "general feature?"

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
