### ISSUE TITLE
BEE2.4 "There was an error building the puzzle"

### ISSUE THREAD

**Issue by creepkido** [BEEmod/BEE2-items#2976]
Hi, sorry if this was already solved. I need help because I can't publish this one map I made. Here's the console:

Primitive Monketh unpaused the game
Primitive Monketh unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198139113925\1556762787.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/1556762787.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (14,21,10)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 255 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 19520 (ms)

VVIS failed.

Valve Software - vvis.exe (Oct 26 2018)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1556762787.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1556762787.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1556762787.prt

[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198139113925\autosave.p2c

**Comment by LautaroL20** [comment]
In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by creepkido** [comment]
It worked, thank you so much!

**Comment by LautaroL20** [comment]
No problem.
