### ISSUE TITLE
Suggested new test elements

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#3]
i have created a list of suggested new test elements below, if I think of any others at any time I will update the list and post an update message here. please don't close or remove this topic... _new items will be at top after each update_

suggested new testing elements and general suggestions
- add the surface division field (make it wall embedded and the same size as a 1 voxel wide world portal door and prevent it's size from being changed)
- change the color of the paint fizzler field to pink (to match the Liquid Coloring Excision Field)
- besides the 4 custom fizzlers fourthreaper made, I have suggestions for four more that I made in a mod once (don't ask me for the files because I lost them years ago), the first one is simply called a force field and it is a fizzler which is a force field (larger alternative to the light bridge) that completely blocks EVERYTHING from going through it and it has a very bright lime green graphic for the field itself, basically it acts like glass or solid wall, the next one is called a "cube repulsion field" and it is a fizzler that allows the player and portals to pass through without fizzling them, but it prevents turrets and cubes from passing through it at all, but it doesn't destroy them, also it uses trigger pushes to push turrets and cubes away from it if their too close to it, (it acts like glass to the cube), it's field color is a navy blue. the third fizzler is called a "portal interference field" and it is a fizzler that allows portals to be fired through it, BUT it will fizzle them if the player passes through it at all. it's color is a dark grey/black and the final fizzler is called a "paint adhesion field" and it acts like the light bridge or a wall with paint and allows paint to stick to it and also the player can walk on it, but cubes, turrets, and portals will pass through it. it's color is a neutral white.
- bottomless pits available in ALL styles (for underground bottomless pit make the test take place in a cave outside the enrichment spheres with the typical underground cave aesthetics, for overgrown make it an overgrown BTS area similar to that area in the beginning of the game where Wheatley says "that is not a docking station", for p1 make it an open pit with a large orange glow and fire at the bottom (incinerator), i think you know how to do BTS, Wheatley, and clean.
- pneumatic diversity vents (with all the junctions ect and proper exits that silently destroy cubes and turrets)
- tube rides (diversity vents that transport player through randomly generated tube ride outside test chamber in clean, overgrown, bts, Wheatley and p1 styles)
- electric death floor (idea's from electric death floor in portal flash version)
- some form of pedestal button that slows down or completely freezes time for a short period (allows player to walk on top of goo pits and walk by turrets. (THIS CAN BE DONE - seen it done here - https://www.youtube.com/watch?v=4TbZh28q_b0)
- a pedestal button that lowers the gravity level in the test chamber to 1/6th of what it is or completely removes gravity for a short period of time (this can be done to) (a example of how this can be used, you have a long goo pit, you have a portal that is very low and close to the goo pit, a faith plate sends you through the portal fast, but normally you would fall in the pit due to gravity, but you press a button which completely removes gravity for a short period and you fly over the goo pit in zero gravity to complete the test.)
- <s>a sendtificator that can transport players along lasers. (if it can be done)</s> (Can't be done)
- teleporters which teleport the player between them when a button is pressed and the player is in the trigger field in the teleporter. (example could be used to teleport the player through a death fizzler where there are no portable surfaces)
- add extended relaxation vault for all styles
- add a 2x2 centered version of the ~~faith plate, faith plate target, and~~ excursion funnel
- add actual clear liquid water that the player can dive into without harm and liquid lava if you can (alternative to goo pit)
- <s>see if you can change the color of the discouragement beam and make a version that kills the player on contact because there is an option to make the discouragement beam deadly in hammer, maybe make this version have separate laser relays and end receiver that can only be powered by this version of the beam.</s> (Too buggy)
- change portal colors used with player model (change portal colors if atlas or p-body are selected)
- turn down volume on shredder big time (spinny blade wall) it is too loud and drowns out everything else

**Comment by TeamSpen210** [comment]
* Diversity vent: Yes
* Electic death floor: This might be nice at some point
* Time slow button: No - I'd have to effectively make a new version of every item in the game with extra entities to make it behave 'frozen'. There is a time-slowing console variable I can change, but that slows down everything (including player speed) - that'd be useful for complex fling manoeuvres, but not much else.
* Gravity changer: maybe, although I'd make it a standalone device, or global map configuration instead. It's definitely possible.
* Player Sendificator: I believe there are technical reasons why HMW didn't implement that, like ensuring you don't get stuck in the ceiling. I don't really want to change HMW's work too much.
* Teleporters: Sure. 
* Relaxation Vault: This would be nice for a kind of vertical entry room.
* 2x2 funnel maybe, but not faith plate (the calculated trajectories will be all wrong)
* I could borrow some of the sendificator code to make it change colour slightly, but the deadly bit doesn't actually work too well. (It only effects the first beam, not parts after a portal or reflection cube.) I don't think it'd add much though.

**Comment by ellingtonisland** [comment]
updated recently, also

- felix made a time slow button once in hammer! use point_servercommand to change phys_timescale https://www.youtube.com/watch?v=4TbZh28q_b0
- for a gravity changer it should be a button that disables and lowers gravity for a certain amount of time (timer)
- for the 2x2 centered faith plate, just make a 2x2 centered target to accompany this version of the faith plate.
- if the laser is buggy when it is deadly, i will remove this suggestion from the list

**Comment by TeamSpen210** [comment]
I'm planning on making the skybox option in the future also control which bottomless pit is used, and I'll probably end up making all those kinds of skyboxes. I'll have for Old Aperture both enrichment sphere (goo-filled sphere below) and test shaft (rock cave) skybox options.

**Comment by ellingtonisland** [comment]
updated on 6/6/2015

**Comment by TeamSpen210** [comment]
If you want other fizzlers, feel free to make your own package. It's not too difficult, and probably won't even require you to make any instances. Just duplicate the paint fizzler package, and modify all the names and VBSP_config to fit your fizzler.

I know it's possible to make a time-stop effect, and I could do it fairly easily in Hammer. The problem is that I'd need to add logic to basically every instance in the BEE2 to let them behave 'stopped'. I'm not doing all that work - use Hammer if you want that sort of thing. 

I actually can't make more than one faith plate target, other than different versions in each style. Even if I did forcefully set the instances with the custom compiler, the speeds calculated by the PeTI would be wrong, probably causing you to fly on wrong trajectories. It'd be fine in an open area, but if there are any walls it'd be hard to predict where the player flies.

**Comment by ellingtonisland** [comment]
for a custom fizzler what do i do about the clean_center.vmt, clean_left.vmt, clean_right.vmt, are they all the same texture file with different names?

**Comment by TeamSpen210** [comment]
Those materials use the Patch 'shader', to keep the fizlesize down. Look at the death fizzler textures or the original Valve textures, which have the full values. The difference between the versions is which fizzler_bounds texture is used. This texture creates the glows around the emitters, and the rings in Old Aperture emitters. Different layouts need to be used to avoid distorting the effects. The 'base' version (the material with the full name) is used for the short 128-sized fizzlers. 

Josepezdj wrote a big writeup of the [properties in fizzler \(`SolidEnergy`\)](0) materials, read that. You usually don't need to make extra textures for custom fizzlers, since the colour is actually defined as a shader property. 

The VBSP_config file's CustFizzler result is used to determine the brush entities that make up the fizzler, and which textures to use. A good example is the Death Fizzler, since it uses 4 different brushes to make up all the modes.
  
[0]: http://forums.thinkingwithportals.com/mapping-help/how-do-the-various-fizzler-vtfs-work-t8310.html

**Comment by Luke18033** [comment]
@ellingtonvengaboysmuseum - The Cube Repulsion Field and the Force Field/Paint Adhesion Field (combined as the Closed Solid Field) have already been implemented into the development version.

**Comment by Luke18033** [comment]
Most of these now have their own dedicated issues.
