### ISSUE TITLE
Ability to change standing/reclined fizzler type

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2-items#3013]
Like the standing fizzler, but a laser field instead

**Comment by Libbybapa** [comment]
"Sunk Cost Fallacy" is the erroneous belief that past investment is a relevant factor in the decision on how to proceed.

**Comment by LautaroL20** [comment]
I will spend just a few seconds of my time to reply someone...  

> Libbybapa said: "Sunk Cost Fallacy is the erroneous belief that past investment is a relevant factor in the decision on how to proceed."

You are incurring in the "Straw Man Fallacy". Distorting the original message i was having with TeamSpen210, in order to confuse people about the true purpose that i am trying to transmit. Having said, i think your "comments" regards to this subject can perfectly fit inside a small box of matches.

My purpose was never about stopping my item´s progression but keeping their most valuable features among the upcoming enhancements it could get, simple as that.

**Comment by Libbybapa** [comment]
I did nothing to distort your message.  I made a simple statement of fact.  If it applies, it applies.  If it doesn't, it doesn't.  It is irrelevant how much work/time/effort you put into the item in the past.  What matters is the desired end result and the amount of effort required to get there.

**Comment by Luke18033** [comment]
This is now implemented in the geometry branch.

**Comment by LautaroL20** [comment]
In that case, i will have to do appropriate editor models for the X4 and X5 extensions.

**Comment by Luke18033** [comment]
TeamSpen already made them I think.
