### ISSUE TITLE
Any Word on Newer Bottomless Pits 

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#3024]
**"Ellington's Flydog is Back"**

Any Word on when the Newer Bottomless Pits that will properly generate around a test chamber that paint and lasers etc... could fall into and vanish from view are coming or going to be implemented?

**Comment by Luke18033** [comment]
Okay who keeps adding a question label? I specifically keep removing that because you're not supposed to use issues to ask questions, that's what Discord is for.

**Comment by ZombiePwner1** [comment]
@Luke18033 Just deleted it I'm not too sure who keeps adding it but it's definitely one of the other Members.

**Comment by calclover2514** [comment]
Um...Github does say who adds the labels:
> LautaroL20 added the Question label 9 days ago

**Comment by Luke18033** [comment]
I mean who created the label itself, not added to the issue. Was probably him though.

**Comment by TeamSpen210** [comment]
I added it actually, so we have a clear reason why the issues are closed instead of a generic "invalid". As to the pits, I've got several prerequisites I need to finish implementing first.

**Comment by LautaroL20** [comment]
> TeamSpen210 Said: "I added it actually, so we have a clear reason why the issues are closed instead of a generic "invalid". As to the pits, I've got several prerequisites I need to finish implementing first."

I think the same, labeling just with an "invalid" label for when someone from time to time randomly decides to ask about something, applying a question label to close them  after answering is not that bad and makes sense for those who could be checking the "closed issues" tab and understanding what the issue was about. 

The question has been answered, closing.
