### ISSUE TITLE
New Turrets 

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3032]
How do you like this idea to add new turrets:
 **Exploding Turrets** when they turn over after the shooting they explode and they will be red,
 **the King** it will be huge and will shoot bombs,
 and can be done to the _old laboratories_ turrets looked like from **Aperture Tag or Portal Stories Mel?**

**Comment by Luke18033** [comment]
Th Animal King isn't being re-added. An auto-destroying turret variant might be a good idea, to prevent unintended use of them when dead (stacking to reach ledges, etc.) They would probably fizzle though, not explode. I've asked about the Old Aperture turret model, that might be added, there was some weird thing with getting permission to use it though which is why it only appears in Tag currently (where the model is already present).

**Comment by Luke18033** [comment]
Self-fizzling turrets have already been suggested in #1612.

**Comment by Kalail** [comment]
> Король животных не добавляется. Саморазрушающийся вариант башни может быть хорошей идеей, чтобы предотвратить непреднамеренное использование их, когда они мертвы (укладка для достижения выступов и т. д.).) Они, вероятно, шипеть, хотя, не взорваться . Я спросил о старой модели башни Aperture, которая может быть добавлена, была какая-то странная вещь с получением разрешения на ее использование, хотя именно поэтому она появляется только в теге в настоящее время (где модель уже присутствует).

THANK YOU

**Comment by LautaroL20** [comment]
> > Король животных не добавляется. Саморазрушающийся вариант башни может быть хорошей идеей, чтобы предотвратить непреднамеренное использование их, когда они мертвы (укладка для достижения выступов и т. д.).) Они, вероятно, шипеть, хотя, не взорваться . Я спросил о старой модели башни Aperture, которая может быть добавлена, была какая-то странная вещь с получением разрешения на ее использование, хотя именно поэтому она появляется только в теге в настоящее время (где модель уже присутствует).
> 
> THANK YOU

WAT.

**Comment by TeamSpen210** [comment]
A translated version, I assume.
