### ISSUE TITLE
New music

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3040]
why not add music from **Aperture Tag**, and **PORTAL STORIES MEL**

**Comment by Konclan** [comment]
There is music from both those mods, you just need the mods installed to get the music. Otherwise packages would be massive.

**Comment by LautaroL20** [comment]
@Konclan - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.

**Comment by Konclan** [comment]
I didn’t know what to label it and I was correct in assuming you would get it since you’re label man

**Comment by underlineGalaxy** [comment]
@Konclan is it possible to use Aperture Tag music on normal Portal 2 PeTI levels? Rexaura, PS: Mel and others work, all except for Aperture Tag. I have both of these mods installed on my steam.

**Comment by Konclan** [comment]
You can use Aperture Tag music in Portal 2’s PeTI yes. You need Aperture Tag installed and it has to be installed on the same hard drive as Portal 2.

**Comment by underlineGalaxy** [comment]
@Konclan yeah... nope. It doesn't work for me.
Funny thing, it shows Aperture Tag music on Bee mod while I have installed.. and I didn't even add Aperture Tag as a portal 2 instance! So what I tried to do was add it as an Portal 2 game (Aperture Tag), verify file integrity of aperture tag and all that, try it again on bee mod... and it doesn't work.
