### ISSUE TITLE
Add aperture tag fizzler support to standing/reclined fizzler.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3048]
Currently nothing happens when the paint gun item is connected to the stand/reclined fizzlers it'd be great for support for this.

**Comment by Luke18033** [comment]
This would again require #3013.

**Comment by LautaroL20** [comment]
Indeed, also that makes too look like this could be kinda a duplicate of that though.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Get on steam you wheely sent you a bunch of messages.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - My CPU is dying so i am currently connected thru a very much potato computer that does not hanlde Steam very well, i can barely use some basic websites like this. I am waiting to get the new CPU next week.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Ugh why does your CPU have to die at the wrong time?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Its frustrating as hell, specially having to wait until next week because i can not even watch a 360p´s Youtuve video without getting terrible fps.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Well this is gonna take awhile...

**Comment by ZombiePwner1** [comment]
@LautaroL20 PC fixed?

**Comment by Luke18033** [comment]
Can you guys please not use GitHub issues to discuss things totally unrelated to the actual issue? This exists for keeping track of things which need to be fixed/added in the mod, it's not a discussion forum for taking about whatever you want. Please use another site/app like Discord if you just want to chat.

**Comment by LautaroL20** [comment]
Alright. I wish i could use Steam for chatting, but unfortunately i had the Steam Ward protection linked only with my died PC. However, this will be my last message about this and i will probably move to the Off-Topic tab at the Bee´s Discord  

@ZombiePwner1 - I will need to recover the security code by connecting the Hard Device where i had my Steam account thru my future PC, which will take more time until i got all the pieces that i am purchasing in order to mount it all. Join the Beemod discord channel and in the off-topic tab, i will share you more details on this subject.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I'm there and I'll delete all these messages once your in the tab.

**Comment by Luke18033** [comment]
Basically a duplicate of #3013
