### ISSUE TITLE
How to get a Large Glass Panel?

### ISSUE THREAD

**Issue by jotmo** [BEEmod/BEE2-items#3082]

**Comment by LautaroL20** [comment]
Large Glass Panel is being developed by an user called Lucke1833, but i will help to its development once i get finished my new PC, since i am currently a contributor who´s using a Potato PC :(

PS: If a member sees this, please add the corresponding "question" label since this potato pc does not allow me running this feature...

**Comment by Luke18033** [comment]
It is indeed an item I've been working on, though there's still a lot that needs to be done before it'll really be finished...I've got a checklist in #466 of things I still need to do.

@LautaroL20 How does a computer not allow you to add labels? Are you using Internet Explorer or something?

**Comment by LautaroL20** [comment]
That is due because my potato pc is using Windos XP and uses outdated versions of Chrome and Firefox in order to being able to running these web explorers onto an outdated system like XP.

**Comment by jotmo** [comment]
Is there something like a beta or something like that?

**Comment by LautaroL20** [comment]
> Is there something like a beta or something like that?

Yes, you will need to download the respective branch, here: https://github.com/BEEmod/BEE2-items/tree/glass_pan

**Comment by jotmo** [comment]
I did everything according to the instructions and the panel appeared, but an error appears when assembling the test chamber. Any ideas? If there was an underlying question, send a message.

**Comment by Luke18033** [comment]
I haven't updated it in a while, it's probably broken.
