### ISSUE TITLE
Can't build puzzle when trying to publish test. 

### ISSUE THREAD

**Issue by KomainTodd** [BEEmod/BEE2-items#3139]
This is the console:
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198119479348\1573429979.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/SteamThings/steamapps/common/Portal 2/sdk_content\maps/1573429979.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (23,13,20)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 75 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/SteamThings/steamapps/common/Portal 2/portal2/puzzles\76561198119479348\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 16025 (ms)

VVIS failed.

Valve Software - vvis.exe (Oct 26 2018)
4 threads
reading d:\steamthings\steamapps\common\portal 2\sdk_content\maps\1573429979.bsp
reading d:\steamthings\steamapps\common\portal 2\sdk_content\maps\1573429979.prt
LoadPortals: couldn't read d:\steamthings\steamapps\common\portal 2\sdk_content\maps\1573429979.prt

Anyone know the fix?

**Comment by KomainTodd** [comment]
Here's the .vmf file
[1573429979.zip](https://github.com/BEEmod/BEE2-items/files/3836157/1573429979.zip)

**Comment by Luke18033** [comment]
Alright, I'll check it out later today when I'm home

**Comment by KomainTodd** [comment]
Okay, thank you!

**Comment by Luke18033** [comment]
Whoops, that's the wrong version. You'll want to grab the one in `styled/`.

**Comment by KomainTodd** [comment]
[1573429979.zip](https://github.com/BEEmod/BEE2-items/files/3841706/1573429979.zip)
This is the .vmf from styled

**Comment by Luke18033** [comment]
You've got a bunch of half grates placed right up against a corner of the chamber. That's been known to cause leaks, and I'm not sure why I didn't remember to ask about it earlier. Here's what I'm talking about:
![image](https://user-images.githubusercontent.com/19228201/68816623-dd0df680-0633-11ea-92f4-88491ead0aae.png)
The problem spots are highlighted in blue. This isn't the only place in the map you've done this, but it's the first one Hammer pointed out. You'll just want to make sure you don't have any half grates placed like that, or hollow out the block diagonally behind them (which will stop the leak, since that area is now inside the map).

**Comment by Luke18033** [comment]
#2013 would fix the problem, making this issue basically a duplicate.
