### ISSUE TITLE
Texture glitches

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3189]
I have been playing around with the editor and suddenly for the first time it shows very glitchy textures. Never seen before and since i downloaded the BEE2 today and this is the BEE2 test chamber, I think its an issue with BEE2

The first 3 are water
the next is a hole 
and the last is the door

![PORTAL 2 09 01 2020 19_24_47](https://user-images.githubusercontent.com/59677445/72055090-e525a200-3315-11ea-9388-1de2ed4273ae.png)

![PORTAL 2 09 01 2020 19_24_52](https://user-images.githubusercontent.com/59677445/72055106-e9ea5600-3315-11ea-92dd-704c339d2822.png)

![PORTAL 2 09 01 2020 19_24_58](https://user-images.githubusercontent.com/59677445/72055114-ee167380-3315-11ea-881d-d4b46a90bbd8.png)

![PORTAL 2 09 01 2020 19_25_47](https://user-images.githubusercontent.com/59677445/72055119-f1a9fa80-3315-11ea-8004-e03cd6f07370.png)

![PORTAL 2 09 01 2020 19_25_55](https://user-images.githubusercontent.com/59677445/72055124-f4a4eb00-3315-11ea-9243-0f2b37a42d8f.png)

**Comment by LautaroL20** [comment]
Now it is in the correct repository (Item packages).

**Comment by Anus95** [comment]
yeah sorry, didn't know

**Comment by LautaroL20** [comment]
Does this issue also happens with other styles appart from Overgrown?

**Comment by Anus95** [comment]
no i tried with clean and it was alright,then i tried again with ovg and it still had leaks, I guess i will stick with other styles for now until the issue is solved.

**Comment by Anus95** [comment]
i changed the entrance to 1:right turn and before I was using 5:small right and changed the exit to 2:white from 1:black

**Comment by LautaroL20** [comment]
That clearly indicates that certain Overgrown´s corridors might be causing the leak. I will going to test those corridors to see if the problem is there, if not, you will have to try doing a clean install of Beemod by deleting old resorces from past releases.

**Comment by Anus95** [comment]
Maybe the past releases part is correct as i have tried installing a previous release (didn't work) and also the issue appeared suddenly as i have used the corridors before and there was no issue, once i opened it again and the issues were there. Also I did install the Beemod that only changed your palette a bit and then i wanted to move on so the new beemod overlaped it. Anyways still thank you lots for the help

**Comment by LautaroL20** [comment]
While i doing some playtesting on this subject, please try following the next steps in order to doing a clean install of Beemod just to see if this fixes your issue: 

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - If this fixed your issue, make sure to save these steps in a text file in case you get similar issues in the future.

**Comment by Anus95** [comment]
For now i am not going to do any of these as i have no issues occurring currently although if a similar issue occurs again I am going to follow all these steps and see if that changes anything. I have saved all the steps in a text document on my desktop so I don't forget it. Thanks again

**Comment by LautaroL20** [comment]
It seems that for now, i am not able to launch Portal 2 because Steam decided to become supid saying that the game can not be launched due that Steam is not running, but it´s running! ![Steam is not runnig](https://user-images.githubusercontent.com/12244376/72062321-56356d00-32b6-11ea-8e78-474529366baf.png)

**Comment by LautaroL20** [comment]
Anyways, if you see that the problem gets back even if in the future you follow all the steps i gave to you, make sure to let us know and we will re-open this issue again.

**Comment by Bumbersnatch** [comment]
I fixed this problem soundly by changing the skybox to _2D BTS_
