### ISSUE TITLE
Add an aditional note to Goo's description telling people it can turn into bottomless pit

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3224]
Not many people knows that Beemod can produce bottomless pits and they seem to not play atention at the skyboxes description. This is why it would be good to include a note on the Deadlygoo window description with a message like: 
"If certain skyboxes such as 3D Factory are selected, Goo placed at the bottom of the map will be replaced by a bottomless pit."

**Comment by LautaroL20** [comment]
Not sure if this would be an application issue since its related to the interface, but at same time its something that can only be implemented thru edit the package...

**Comment by Luke18033** [comment]
Yeah, it would be a package issue.

**Comment by Slips-PC** [comment]
I second this. Maybe something more like "If you have the 3D factory skybox enabled, placing deadlygoo two tiles deep will create a bottomless pit." I honestly had no idea that you could make pits.

**Comment by Luke18033** [comment]
Since people can (and have) made custom 3D skyboxes, it would be better to say "when certain skyboxes are selected, Goo that is at least two tiles deep will be replaced by a bottomless pit". In the skybox selector, I think there's then a "3D skybox" indicator at the bottom, below the description.

**Comment by Slips-PC** [comment]
Really? Interesting.

**Comment by JavierNovellon** [comment]
@Luke18033 and @Slips-PC 

>Placing deadlygoo two tiles deep
>Goo that is at least two tiles deep

Does the goo _have_ to be two tiles deep to turn into a bottomless pit? What I found is that the **lowest** pit turns into a bottomless one, regardless of depth.

Examples here, I might add more:
**EXHIBIT A**
Two tile deep goo is placed hovering above a one tile deep goo.
![20200305184106_1](https://user-images.githubusercontent.com/47536167/76014776-17b4db00-5f12-11ea-9b6b-f9685e58cc75.jpg)
![20200305184115_1](https://user-images.githubusercontent.com/47536167/76014779-184d7180-5f12-11ea-92fe-07426ce6d911.jpg)

Because the two tile deep pit is physically higher, it does not turn into a bottomless pit.
![20200305184244_1](https://user-images.githubusercontent.com/47536167/76014780-18e60800-5f12-11ea-8114-fb8094c69861.jpg)

**EXHIBIT B**
The chamber is split in two, with a large, two tile deep goo; and lower below, a smaller, one tile deep goo pit.
![20200305183706_1](https://user-images.githubusercontent.com/47536167/76015056-87c36100-5f12-11ea-9813-615c8318b5a6.jpg)

Once again, the lower pit turns bottomless, despite being smaller and shallower.
![20200305183918_1](https://user-images.githubusercontent.com/47536167/76015058-885bf780-5f12-11ea-8a9c-60f11f9e7871.jpg)
![20200305183924_1](https://user-images.githubusercontent.com/47536167/76015060-88f48e00-5f12-11ea-87eb-19bbd14eb9cf.jpg)

**Comment by Slips-PC** [comment]
Hm, That complicates things... 
I'd love to know the exact criteria for a 3D skybox to be generated.

**Comment by Luke18033** [comment]
Oh yeah, it needs to be placed at the bottom of the map (to ensure there isn't any geometry below that would get in the way). It's also recommended to make it at least 2 blocks deep, but not a requirement like I thought earlier.

**Comment by JavierNovellon** [comment]
> Oh yeah, it needs to be placed at the bottom of the map (to ensure there isn't any geometry below that would get in the way). It's also recommended to make it at least 2 blocks deep, but not a requirement like I thought earlier.

That makes a lot more sense.

**Comment by Slips-PC** [comment]
> Oh yeah, it needs to be placed at the bottom of the map (to ensure there isn't any geometry below that would get in the way). It's also recommended to make it at least 2 blocks deep, but not a requirement like I thought earlier.

Ohhhhh

**Comment by Luke18033** [comment]
This should still be added but the text would need to be changed once non-skybox pits are implemented.

**Comment by Konclan** [comment]
Closing this for now because its not an issue for the moment. We'll change it when we do *eventually* make the extended chamber system #3891
