### ISSUE TITLE
items show up as errors!

### ISSUE THREAD

**Issue by BluefreddyP** [BEEmod/BEE2-items#3236]
my items appear as errors and/or missing textures in the palette.
![D8HgKxR](https://user-images.githubusercontent.com/54141759/75629522-081c5600-5be3-11ea-9200-b474aa337c6f.png)
&
![MGV5dAK](https://user-images.githubusercontent.com/54141759/75629543-297d4200-5be3-11ea-8506-b081e9c8f775.png)

please help

**Comment by Flash4433** [comment]
It seems that BEE2 didn't export all of the needed files. Try re-exporting.

**Comment by Flash4433** [comment]
Also, by any chance, is there an antivirus blocking BEE2 from exporting the files? Did you ever use one of the older BEE versions?

**Comment by BluefreddyP** [comment]
> 
> 
> Also, by any chance, is there an antivirus blocking BEE2 from exporting the files? Did you ever use one of the older BEE versions?

nope, nothing, it just happens

**Comment by Flash4433** [comment]
Well, you try steps 1, 4, 5 and 6 in this order from this guide.
https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

**Comment by BluefreddyP** [comment]
> 
> 
> Well, you could try steps 1, 4, 5 and 7 in this order from this guide.
> https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

ima try

**Comment by BluefreddyP** [comment]
> 
> 
> > Well, you could try steps 1, 4, 5 and 7 in this order from this guide.
> > https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod
> 
> ima try

still broken

**Comment by LautaroL20** [comment]
In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by Luke18033** [comment]
Please read the rest of the comments. He already tried that multiple times, it didn't do anything.

**Comment by LautaroL20** [comment]
Whoops, i only played attention to issue´s description only. I missed comments but i will check them in future for this kind of weird issues.

**Comment by BluefreddyP** [comment]
> 
> 
> In order to solve this issue, you will have to do the following:
> 
>     1. Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.
> 
>     2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.
> 
>     3. Wait 1 minute while BEEmod resources are removed from Portal 2.
> 
>     4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.
> 
>     5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4.
>        Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).
> 
>     6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.
> 
>     7. Select a palette and style, and export it to the game as normal.
> 
>     8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.
> 
>     9. Happy mapmaking!

i tried step 2 & 3 & 8 and it worked!

**Comment by Flash4433** [comment]
Hum, are you sure you never used one of the older versions of BEE?

**Comment by BluefreddyP** [comment]
> 
> 
> Hum, are you sure you never used one of the older versions of BEE? Those steps usually fix issues if there are still old BEE files in your Portal 2 folder.

idk

**Comment by LautaroL20** [comment]
YAY, i am glad these steps solved your issue!
