### ISSUE TITLE
Art therapy indicator does not behave like it's supposed to.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3272]
![image](https://user-images.githubusercontent.com/18079316/79629499-e704ca00-817c-11ea-99a7-129bda93fc16.png)

**Comment by Luke18033** [comment]
Art therapy style hasn't been updated in years, why are you even still trying to use it? This probably has something to do with the switch to the new connections system

**Comment by The-Queen55142** [comment]
Updated recently or otherwise (this case being Otherwise) 
The bug still applies and I don't see the issue with reporting it, it gets the bug report out of the way early, That way when progress on Art Therapy eventually continues, You can nip the bug in the bud before you get a million people all reporting the same bug.

**Comment by ZombiePwner1** [comment]
@Luke18033 I'm trying to see if I can get art therapy to a actual playable state for use in both aperture tag and portal 2. Atleast that way it's actually playable and not some broken mess.

**Comment by Luke18033** [comment]
Opening this issue just seems kind of pointless, it likely only exists because the style hasn't been updated in a while, and would already end up being fixed if it ever was. But if you're working on the style yourself and just opened this as a sort of reminder, then I'm totally fine with it in that case.

**Comment by Luke18033** [comment]
Although it might be a good idea to wait for TeamSpen to finish the tiling system rewrite before attempting anything major like this. Otherwise you might have to go back and check/modify a lot of stuff once it's out.

**Comment by ZombiePwner1** [comment]
@Luke18033 I am gonna try fix the style up to the point that it's fully playable for both portal 2 and aperture tag then once work is resumed on it all the bugs that I posted can be easily fixed.

**Comment by ZombiePwner1** [comment]
I will be taking back ups of the modified files on my PC so when the tile system is completely re-written I'll still have backups of the old Art therapy files to test on the new system.

**Comment by Luke18033** [comment]
This is probably another connection system mismatch issue.
