### ISSUE TITLE
Make Flux Fields also detect rockets

### ISSUE THREAD

**Issue by RmxMi** [BEEmod/BEE2-items#3342]
From what I see Rocket Turrets from Portal 1 are useless as turrets do almost the same thing so I suggest making a hole that activates what's connected to the hole when a rocket hit's it or a rocket button so they are unique.

**Comment by Luke18033** [comment]
The intention is to add breakable glass which can be destroyed by rockets, like in Portal 1. It might also be useful to have some sort of rocket sensor though, maybe with the ability to have a timed output.

**Comment by TeamSpen210** [comment]
Not really sure how that would be visually depicted.

**Comment by Some-Username-Available** [comment]
Maybe some sort of Electrical Box?

**Comment by ThEnderYoshi** [comment]
Maybe a fizzler, like the radiative flux rectangle.

**Comment by Konclan** [comment]
Why not just have the flux rectangle also detect rockets, like it detects projectiles. It could even detect futbols being thrown through it.

**Comment by Luke18033** [comment]
That could work. Those are all physics objects and are specific entities, so they can be detected with triggers and it's easy to filter for them.

**Comment by Konclan** [comment]
Actually instead of modifying the RFR to a projectile field I think it can keep its energy ball niche and add another sensor for test objects (cubes, futbols, rockets, etc) #2122

**Comment by Luke18033** [comment]
For rockets at least, I think they should still activate flux fields rather than object sensors. The problem with having them activate object sensors is that it restricts what you can do with cubes and rockets in the same map, since either can activate the sensor. Using the flux field instead for rocket detection would fix that problem, and I think it's a lot less likely that you'd be using rockets and HEPs in the same map.

**Comment by TeamSpen210** [comment]
I like having flux fields detect rockets.
