### ISSUE TITLE
Cube dropper not dropping cube

### ISSUE THREAD

**Issue by bostonlondon** [BEEmod/BEE2-items#3424]
My cube dropper isnt dropping a cube, ive tried multiple options on the dropper itself and it doesnt seem to work, ive tried moving it and without a button but it still doesnt work 
![giphy](https://user-images.githubusercontent.com/62776270/89094186-ca387f00-d386-11ea-83d7-251178cb0010.gif)

**Comment by FrozenDragon0** [comment]
Is this version 4.37?

**Comment by bostonlondon** [comment]
Yeah

**Comment by FrozenDragon0** [comment]
Wow this version is seriously bugged.

**Comment by LautaroL20** [comment]
@bostonlondon - Dude, why you don´t reply to some messages? It would be interesting to know why did you close issue #3423 without explaining the why, because that issue is not supposed to have been solved yet.

**Comment by Luke18033** [comment]
Why do you care so much? They probably just fixed the problem.

**Comment by LautaroL20** [comment]
> Why do you care so much? They probably just fixed the problem.

Because it is interesting to know the reason, just a "fixed my probem" would have been ok, and also because you were asking him for the preview file to analyze it which made me thought it was kind of important issue for you, but now i see it wasn´t... 

From now i will not care if the authors mysteriously closes their issue without any kind of explanation.

**Comment by Luke18033** [comment]
I mean yeah, I'm curious about it too. But I wouldn't go and ask the person about it on another issue of theirs, I'd just wait to see if they responded, if not, then whatever.

**Comment by LautaroL20** [comment]
> But I wouldn't go and ask the person about it on another issue of theirs, I'd just wait to see if they responded, if not, then whatever.

Problem is that he seems to have deliverately ignored the comment i did on issue #3423 because at the same time he is now replying to newer commenst here, this clearly means he had to see the notification of my comment which is earlier. So, waiting to his reply at this time is evidently useless as he seems to have choosen to ignore certain comments for some reason, i really care about his replies? Honestly, no but the behavior of some people can be strange sometimes though.

**Comment by LautaroL20** [comment]
By the way, this issue does not happens to me, and i am using version Version 4.37.0. The issue´s author probably did not a clean install of Beemod, screenshot:

![Image](https://user-images.githubusercontent.com/12244376/89113997-3631ea80-d44e-11ea-8d01-201847a2272d.jpg)

I would like if more people can do aditional playtest on this subject though.

**Comment by Luke18033** [comment]
I've heard some people have had problems with cube droppers in the latest release, though it usually has to do with cubes getting stuck when leaving the dropper. I haven't seen anyone else saying that they won't activate at all, and they worked fine for me in the development builds.

**Comment by Luke18033** [comment]
Also, those "clean update" steps really shouldn't be necessary anymore. As long as you have Preserve Game Directories turned off, it should recognize that the packages have been modified and copy over the new resources. Even if it doesn't, clicking Reset Package Caches would fix the problem.

**Comment by LautaroL20** [comment]
I can´t replicate this.

**Comment by Luke18033** [comment]
They've also been working fine for me.
