### ISSUE TITLE
Global hazard settings for turrets

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3479]
Add global settings for turrets including:
- "Super damage" mode on/off
- Shoot through portals on/off

I am working on implementing this.

**Comment by seagemgames** [comment]
I've already made a package for this, not sure if it works for latest BEEmod, however.
https://github.com/CheezyPig/saismee-addons/releases/latest

**Comment by maxdevgithub** [comment]
> I've already made a package for this, not sure if it works for latest BEEmod, however.
> https://github.com/CheezyPig/saismee-addons/releases/latest

It works

**Comment by Konclan** [comment]
I think it would be bad to have turrets act radically different with an option. Especially if the change isn't clearly visible in the map. You might say just have text or signage announce it but thats not a very good solution either. Turrets are a form of area denial and the better way is to use a different hazard entirely. The fan item #3884 makes a good alternative because it can also deny area with a deadly suck and be blocked with a vertical lightbridge like turrets. Overall if you want these super turrets make a UCP with a turret that has a custom skin or something.

**Comment by GiovanH** [comment]
Neither of these options are new testing elements. These are both native features vanilla turrets have in the main game. This just makes the options accessible.

**Comment by seagemgames** [comment]
As I stated before, I've made a UCP for it. It does now work for the latest version of BEEmod, and has been moved to
https://github.com/seagemgames/saismee-addons/releases/latest
