### ISSUE TITLE
Beemod 2 items missing texture

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3528]
Picture says it all

![beemod](https://user-images.githubusercontent.com/63530071/93691291-721c2e80-fb26-11ea-822a-34207dc2d8ce.png)

**Comment by LautaroL20** [comment]
In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by supersean08-pro** [comment]
the problem is still here, I do not have an antivirus but I have mods (if you think that's interfering)

**Comment by LautaroL20** [comment]
> I do not have an antivirus but I have mods (if you think that's interfering)

That could be interfering most likely, try removing them from the Portal 2 folder, then repeat the steps i gave you in my previous comment and then it should solve your issue. Most people who have reported having the issue you shown in that pict, they solved it by following these steps i gave you.

**Comment by supersean08-pro** [comment]
it worked thanks chap

**Comment by LautaroL20** [comment]
Glad to known my steps helped on your issue.
