### ISSUE TITLE
1950's Pellet Catcher doesn't send output after catching pellet

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3534]
**BEE2 version:** 4.37.0

**Description of the bug:** Self-explaination. Catcher catches a pellet, but outputed thing doesn't activate and antlines are still blue.

**Expected behavior:** Fix that.

**Comment by LautaroL20** [comment]
Now that every person who uses a Github account is able to add labels to their own issues, you do not need to writte on the issue´s title things like "Bug, suggestion, new item, etc".

**Comment by Luke18033** [comment]
Specific labels get applied automatically if you use one of the issue templates, I think adding them manually is still restricted to organization members.

**Comment by LautaroL20** [comment]
Ah, it was that then. It looks like an interesting feature.

**Comment by Thedoczek** [comment]
So, when do you plan to release fixed version?

**Comment by LautaroL20** [comment]
Well, we usually do new public releases when we reach a reasonable ammount of bugfixes/new feature implementations. I think that a new public release by the end of this year is the most likely.

**Comment by Luke18033** [comment]
I'd like to have 4.38 out soon, to fix some of the problems in 4.37. But I think there were a couple of things in the app that still need to be fixed before a new release can be made.

**Comment by LautaroL20** [comment]
> Luke18033 Said: "I'd like to have 4.38 out soon, to fix some of the problems in 4.37. But I think there were a couple of things in the app that still need to be fixed before a new release can be made."

Despite that that is not a bad idea, could you wait me until i can address the auxiliary pillars support and color picking on the brushes from the Standing/Reclined fizzlers? TeamSpen210 told me that he will develop a special debug feature that will allow me to solve the issue that is explained in the #Developer tab from the Bee´s Discord server. 

He told me he would develop it before the next Bee´s release and this issue is really an high priority for me.

**Comment by Luke18033** [comment]
For the color matching, I looked at the conditions and templates and don't specifically see any problems. There seems to be an issue in the compiler (which is partially what I was referring to in my last comment). But as nice as the color matching and support pillars look, I don't think it's such a critical issue that the next release needs to  be held back because of it, considering that there are currently some major issues preventing people from being able to use 4.37 (the logic gate compile error and cubes getting stuck in droppers, among other things). I'd like to have a new release out sooner rather than later. If it happens to include fixes for the standing fizzler pillars, that's great. If not, I don't think people will mind having to wait until 4.39 for that.

**Comment by LautaroL20** [comment]
Alright, that was explanatory and now i understand your point, seems fair.

**Comment by Luke18033** [comment]
Regarding the actual issue here, it sounds like a connection mismatch. I'll take a look.

**Comment by TeamSpen210** [comment]
Fixed in 2.4.42.0.
