### ISSUE TITLE
BEE2 bug

### ISSUE THREAD

**Issue by CMSEv7** [BEEmod/BEE2-items#3535]
Hi,

I have a problem with my BEE2. When I open Portal 2 with a new palette, all the BEE2 objects are Missing Textures or famous blue ERRORs.

**Comment by LautaroL20** [comment]
> CMSEv7 Said: "All the BEE2 objects are Missing Textures or famous blue ERRORs."

In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by Thedoczek** [comment]
> Check that "Preserve game directories" is unchecked
That should be the first step of this...

**Comment by LautaroL20** [comment]
Nope. Almost, or even all the steps there are important to address issues like this because you can´t be 100% sure that just that single step you mention is the only thing that will entirely fix it.
