### ISSUE TITLE
Is #3534 fixed? And are there bottomless pits again?

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3592]
It was about old Ap HEP Catcher didn't send output. #3534. I understand that you could not reply to all when giving an update, so, is it done?

And, did btmls pits come back?

**Comment by LautaroL20** [comment]
If you don´t see that issue #3534 did not get any commit or it wasn´t "done labeled", then i doubt that it was fixed. Also, you could have commented about this subject on the issue #3534 comment section instead of open a new issue. You can give a try to the recent Beemod release 38 and check it yourself to see if the bug still exist though, you can get it below:

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.38.0 (User Interface)
https://github.com/BEEmod/BEE2-items/releases/tag/v4.38.0 (Items Packages)

**Comment by FrozenDragon0** [comment]
No bottomless pits are not back. TeamSpen would've stated in the release notes if they did.
