### ISSUE TITLE
BEE 4.38.1 Packages Issue

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#3596]
**BEE2 version:** 4.38.0 (4.38.1 for the App)

**Description of the bug:**  Missing Icons, textures, and models, along with some textures being Fullbright.

**Expected behavior:** Everything to be there, nothing missing.

**Steps to reproduce:** 
Remove all instances of BEE from your computer, 
Go through the reinstall process (verify integrity, reinstall apps and packages, etc)
Just try exporting your BEE.

**Additional information:**
![image](https://user-images.githubusercontent.com/37309250/104805673-d3d06a80-579f-11eb-822b-6d675a94d8b2.png)
![image](https://user-images.githubusercontent.com/37309250/104805677-d92db500-579f-11eb-8df0-917983d61f8f.png)
![image](https://user-images.githubusercontent.com/37309250/104805678-db900f00-579f-11eb-87a4-f6503de2a058.png)

I should note! I have tried everything, I've added files to my Anti-Virus exception list, I did a 100% fresh install of both BEE and Portal 2. Verified integrity, I even disabled my anti-virus just to see, and nothing works.

I have the suspicion this is a package issue due to all non-BEE icons appearing just fine.

EDIT: I should also note. Preserve Game Directories is NOT checked, it's been off for a long time.

**Comment by FrozenDragon0** [comment]
Looks like you have preserve game directories checked. You need to uncheck that in the BEE2 options.

**Comment by The-Queen55142** [comment]
Please refer to the edit at the bottom, I have stated already that I did not have it checked.

I ensured this multiple times.

**Comment by FrozenDragon0** [comment]
Didn't see the edit in my emails.

**Comment by The-Queen55142** [comment]
It's fine! Don't worry about it!

**Comment by LautaroL20** [comment]
Hi, i have readed your entirely issue´s description with the things you´ve tried to solve it, but still, i have to say that your issue about the missing textures/models in the puzzlemaker, many people has confirmed me that they solved it by following carefully the steps i will point below. Like i said, i know you have told you already tried some of those methods, but this time i´d recomend you to follow carefully the next steps neatly because this is the only thing that could help you solving it:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. Latest version is BEE2 4.38.1 and packages are 4.38.0. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Hope these steps solved your issue, if so, happy mapmaking!

**Comment by LautaroL20** [comment]
Maybe you have other mods who could be interfering in your Portal 2 folder among with the Beemod files too, if so, try remove all them from Portal 2. Other than that, it is unlikely that there is more we can do to help you solving that.

**Comment by The-Queen55142** [comment]
I gave it a shot, following what you said, and, unfortunately, no luck.

For now I'll stick to the previous versions, as they seem to work perfectly fine. (It's only 4.38/4.38.1 that has the issue) 

Thanks for attempting to help, though!
