### ISSUE TITLE
Customizable Glass

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3728]
**Description of the item:** A version of glass that offers deeper customization options.

**Item options:**
- Borderless glass ( every style )
- Broken glass ( every style )
- Reinforced glass ( portal 1 only, other versions have a different specific look )

_Examples:_
![clear-subtle-lines-glass](https://user-images.githubusercontent.com/42079031/113242039-fd1c7500-927d-11eb-808f-fdb10b7381f7.PNG)
![broken-glass](https://user-images.githubusercontent.com/42079031/113242042-00affc00-927e-11eb-8c67-956ea9c6d98d.PNG)
![reinforced-glass](https://user-images.githubusercontent.com/42079031/113242050-0279bf80-927e-11eb-924f-02df679e1ea4.PNG)

**Additional information:** I was trying to recreate this room from rexaura using only beemod, and I would've naturally managed to merge the glass with the wall if it weren't for the borders. Without the borders, it's possible to create sections of glass in between the voxels where glass is supposed to be.

_Goal:_
![example](https://user-images.githubusercontent.com/42079031/113242284-99467c00-927e-11eb-9349-e4f939483379.PNG)

_Editor:_
![Screenshot (241)](https://user-images.githubusercontent.com/42079031/113242205-64d2c000-927e-11eb-82b3-4f70c81f55a1.png)
![Screenshot (242)](https://user-images.githubusercontent.com/42079031/113242206-656b5680-927e-11eb-902f-5d1f181d3315.png)

_Visual Error:_
![Screenshot (243)](https://user-images.githubusercontent.com/42079031/113242650-79638800-927f-11eb-9f32-ca2fe392ed23.png)
![Screenshot (244)](https://user-images.githubusercontent.com/42079031/113242653-7a94b500-927f-11eb-840c-c045813a29c2.png)

**Comment by TeamSpen210** [comment]
* Borderless glass just really looks bad. The proper solution there would be to implement a CSG system for the blocks and glass, so that the border reshapes to the blocks involved. 
* For "reinforced" glass, that seems rather pointless if it's identical to regular glass. I've considered wanting to add some sort of "dark" glass, which blocks LOS and lasers. I don't know which picture you're showing for this anyway, P1 produces the beams across floor surfaces already.
* Broken glass I'm rather against, because it exposes an obvious issue - if the glass has to be broken for the puzzle to work, how was the player supposed to solve the chamber in the "past" when it was Clean? It also makes little sense in styles which aren't decayed.
