### ISSUE TITLE
Missing beemod items

### ISSUE THREAD

**Issue by pingist** [BEEmod/BEE2-items#3787]
![IMG_20210516_112839](https://user-images.githubusercontent.com/79645882/118390828-e2d60500-b639-11eb-81ce-7c2d7339c28a.png)
Everything related to beemod is missing, even styles. I tried reinstalling it, i tried downloading clean beemod and packages from github. But it didn't fix.

**Comment by SCIENTIST2004** [comment]
In order to solve this issue, you will have to do the following:

1 Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 bin folder. Add the entire bin folder in your antivirus exception list; if the exception list only allows individual files, add vbsp.exe and vrad.exe. Otherwise, this can cause a compile error when building your puzzle.

2 Open BEEmod and click on File > Uninstall From Selected Game. Choose Yes in the dialog that appears.

3 Wait 1 minute while BEEmod resources are removed from Portal 2.

4 Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting Properties > Local Files > Verify Integrity of Game Files.

5 Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4.
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: Application and Packages.

6 Click on: File > Options. Go to the Development tab, and uncheck the option Preserve Game Directories.

7 Select a palette and style, and export it to the game as normal.

8 Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9 Happy mapmaking!

**Comment by pingist** [comment]
> In order to solve this issue, you will have to do the following:
> 
> 1 Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 bin folder. Add the entire bin folder in your antivirus exception list; if the exception list only allows individual files, add vbsp.exe and vrad.exe. Otherwise, this can cause a compile error when building your puzzle.
> 
> 2 Open BEEmod and click on File > Uninstall From Selected Game. Choose Yes in the dialog that appears.
> 
> 3 Wait 1 minute while BEEmod resources are removed from Portal 2.
> 
> 4 Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting Properties > Local Files > Verify Integrity of Game Files.
> 
> 5 Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4.
> Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: Application and Packages.
> 
> 6 Click on: File > Options. Go to the Development tab, and uncheck the option Preserve Game Directories.
> 
> 7 Select a palette and style, and export it to the game as normal.
> 
> 8 Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.
> 
> 9 Happy mapmaking!

THANK YOU SO MUCH😃!!! IT WORKED!

**Comment by LautaroL20** [comment]
Those steps i´ve made has always been useful, glad to see it helped a lot of people and it still helps :)
