### ISSUE TITLE
All maps giving compile error, even when new and clean

### ISSUE THREAD

**Issue by Greypilgrim228** [BEEmod/BEE2-items#3793]
**BEE2 Version:** **4.39.2 with 4.39.1 packages**

**Error Log**

[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_BEE2/logic/antigel_marker.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_BEE2/logic/antigel_marker.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Requested non-existent write path LOCAL!
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 23 (ms)

VBSP failed.

Valve Software - vbsp.exe (May 19 2021)
6 threads
Using shader api: shaderapiempty.dll
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf

**Additional Info**
I'm unsure if this should be logged in Bee2 - Items or or Bee2.4, and whether it's an issue on my end or problem caused by the recent portal 2 update (18th May), but ever since then I've been unable to edit any of my maps, existing or new. Trying to rebuild them results in an error. I know it occurred then because I'd uploaded a finished map late on the 17th, came to edit and republish it the following morning and...error.

![LgXlQzl](https://user-images.githubusercontent.com/79481385/119008628-4047ba00-b98a-11eb-82df-84bfedb56c55.png)
![vYJQ7NX](https://user-images.githubusercontent.com/79481385/119008668-49d12200-b98a-11eb-92a9-82d10a43ee76.png)

**Comment by TheEnderek0** [comment]
On my side after installing P2 update everything still works fine, so it's probably not the case.
Probably...

**Comment by LautaroL20** [comment]
@Greypilgrim228 - In order to solve this issue, you can try doing the following and see if it works. If it works, please let us know:

1.  Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by Greypilgrim228** [comment]
Followed the instructions to the letter and uninstalled/reinstalled beemod and verified game cache etc. etc.
Long story short, it all seems to be working again. No compile errors any more.
Thank you very much for the help!
