### ISSUE TITLE
there are missing models just fix them

### ISSUE THREAD

**Issue by lolfood1533** [BEEmod/BEE2-items#3849]
see for yourself
![20210714202054_1](https://user-images.githubusercontent.com/81488421/125724049-62b71e7f-8c3b-4d13-b4a4-cf1aa9e95d17.jpg)

**Comment by CardsAndGamesYT** [comment]
what version are you using

**Comment by CardsAndGamesYT** [comment]
because if your not using the newest version then you need to upgrade.

**Comment by FrozenDragon0** [comment]
First of all those are not models.
Second of all what version are you using? If you do not provide any information on what version your using we cannot help you fix your problem as we have nothing to know what the issue is.

**Comment by LautaroL20** [comment]
@lolfood1533 - In order to solve your issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

In case that after doing this, did not solve your issue, let us know and we will re-open the issue.
