### ISSUE TITLE
Overgrown add skylight and more plants to ceiling corridors

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#390]
A sky and some plants to the ceilling corridors from Overgrown style would make look it more interesting.

![20160314122256_1](https://cloud.githubusercontent.com/assets/12244376/13780164/fb1a8230-ea9c-11e5-83e1-dadf6da8403b.jpg)

**Comment by ellingtonvengaboysmuseum** [comment]
this will be done with a item like the cutout tile eventually

**Comment by ZombiePwner1** [comment]
Overgrown looks horrible without plants I literally can't stand overgrown unless there is some plants in the area.

**Comment by Konclan** [comment]
What does "Add a sky" mean?

**Comment by LautaroL20** [comment]
@Konclan - ![sky](https://user-images.githubusercontent.com/12244376/33242307-70ad28a6-d2b1-11e7-8045-e3342c70a438.jpg)

The current sky that is using some open ceilling areas from corridors looks like a "leak" rather than an actual "sky", thats why i am suggesting a better one.

**Comment by Konclan** [comment]
I don't think you'd see blue sunlight or clouds, the way I understand the sunlight works in overgrown is like this
![sunlight](https://user-images.githubusercontent.com/16567080/33244676-3803973c-d2c1-11e7-9e72-6e5180ebbe9f.png)
The sunlight pours through large holes in the exterior due to GLaDOS' explosion into the interior which is a giant empty space for building floating test chambers like in the old aperture salt mines. Having a realistic blue sky wouldn't fit the style.

**Comment by LautaroL20** [comment]
Well, the screenshot was just a representation of what i meant, not how it exactly needs to look. I think i should look up for an actual overgrown open ceilling screenshot then.

**Comment by Konclan** [comment]
Merged issue with #468
