### ISSUE TITLE
"vpks were not exported" always show up despite portal 2 and hammer closed

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3989]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.2

### Description of the bug

![20211112112631_1](https://user-images.githubusercontent.com/63530071/141399242-b9af39a9-6761-49c0-a6ed-c4bf81ab8fa8.jpg)
outcom
![see](https://user-images.githubusercontent.com/63530071/141399306-8fb2afff-0394-4c25-95ff-f593f6a23e85.png)

### Expected behavior

perfect export

### Steps to reproduce

i dont know

### Logs and Reports

```shell
[PORTAL2 PUZZLEMAKER] Unrecognised property type:
[PORTAL2 PUZZLEMAKER] Unrecognised property type:
Error reading material data "materials/logo/logo_aperture.vtf"
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
Error reading material data "materials/vgui/badgebg.vtf"
Error reading material data "materials/vgui/badgeoverlay.vtf"
Error reading material data "materials/vgui/logo_aperture_badge.vtf"
```

### Additional information

any

**Comment by supersean08-pro** [comment]
wait i think i have identified the issue

**Comment by supersean08-pro** [comment]
nope

**Comment by LautaroL20** [comment]
> supersean08-pro said: "wait i think i have identified the issue... nope"

Well, I think that I do, the cause of this issue and especially issue #3988 is most likely that you have installed other Portal 2 mods that are getting in conflict with some important files of BEEmod which obstructs the normal behavior of it causing this kind of issues. My suggestion for you is that if you really want BEEmod to work well, first make sure to uninstall any other P2 mods from your game´s directory and then follow these steps:

In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have installed the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by supersean08-pro** [comment]
![maxresdefault (3)](https://user-images.githubusercontent.com/63530071/141596050-61a30ee0-b0f1-40ba-8cd8-89fcc22469cc.jpg)
