### ISSUE TITLE
Locking Adjustable Pedestal Buttons leak in Old Aperture

### ISSUE THREAD

**Issue by dzhemvrot** [BEEmod/BEE2-items#4042]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Goo creates a leak
Same with goo on the bottom of map(pit)
![image](https://user-images.githubusercontent.com/78698870/147446239-cfaf9c63-1a03-477f-bac8-fe841f99b2ad.png)
![image](https://user-images.githubusercontent.com/78698870/147446355-67bb3e36-6963-4fb2-930d-54b65db1cc58.png)

### Expected behavior

Goo don't create a leak

### Steps to reproduce

1. Add Goo
2. Select any other style other than Clean(I use 1980's Old Aperture style)
3. Profit

### Additional information

ZIP file with preview.vmf and preview.lin here
[preview.zip](https://github.com/BEEmod/BEE2-items/files/7778768/preview.zip)

**Comment by Luke18033** [comment]
The goo itself isn't causing the leak, it breaking is just one of the side effects of another item leaking. If you're using any UCP items, try removing those first, otherwise I'll take a look at the attached VMF tomorrow

**Comment by wowemain** [comment]
Sorry for being dumb, but what's an UCP item?

**Comment by Luke18033** [comment]
User-created packages, if you've never heard of them then you're not using any.

**Comment by wowemain** [comment]
Yes, that's right, I'm not using any

**Comment by Luke18033** [comment]
The error is caused by this pedestal button connected to the autoportal:
![image](https://user-images.githubusercontent.com/19228201/147615403-49931dab-4169-4d7c-aab8-ae669b67b037.png)
To work around it, hollow out the block diagonally down from the button and place something that embeds like an angled panel below, like this:
![image](https://user-images.githubusercontent.com/19228201/147615528-90c28fc0-2521-4d14-a6ef-865f0080b54a.png)

**Comment by TeamSpen210** [comment]
This appears fixed.
