### ISSUE TITLE
add the some items,add deep pit,old aperture version rocket turret,alternate turret for old aperture in portal 2(from aperture tag and mel)

### ISSUE THREAD

**Issue by 1209-57238032** [BEEmod/BEE2-items#4061]
### Description of the feature

items:breakble glass,shredder,gel can,incinerator,fire pit(like goo but only in p1 last test glados used by kill chell),bomb ball(used by wheatley) alternate for rocket turret in old aperture ,alternate skeleton turret for old aperture in portal 2 but can changed 2 versions namely tommy turret(mel and tag) and skeleton turret(coop human vault),add deep pit skybox 3d

### Why should this be implemented

i think add these items and 2 versions for old aperture turret,alternate old aperture version rocket turret ,add deep pit skybox(skybox like clean skybox but is deep pit 3d)

### Additional information

alternate old aperture version rocket turret,alternate skeleton turret for old aperture in portal 2(from aperture tag and mel is a tommy turret) can be changed 2 versions and some new items one new 3d skybox
![Uploading 20220117101147_1.jpg…]()

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
