### ISSUE TITLE
consolodate lights into one "lights" item

### ISSUE THREAD

**Issue by patrlim** [BEEmod/BEE2-items#4077]
as title says, this would allow for more test elements in one level if the user wishes to use multiple lights, for example for theming.
it may be possible to do the same with fizzlers.

**Comment by LautaroL20** [comment]
Not sure what do you exactly mean, because the Light Strips are already contained into the "cubetype" class that you can use to change the light colour, something similar happens with the Square Light. If what you mean is collapse the different light icons into a single icon, well this is not a good idea because each light icon has a different colour, and because if you made it a single icon many unexperienced BEEmod users will think that it is a single light and may not bother on deploying the context menu in the puzzlemaker to see if there are more light options available.
