### ISSUE TITLE
 Icons and models disappear.

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2-items#4135]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0 with UCP's

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Item icons are not showing, and editor models just mark the word _ERROR_.
![Problema Bee](https://user-images.githubusercontent.com/88097966/166159996-d14b1953-8ede-41f2-8f55-db0480b92ea5.png)

### Expected behavior

Icons and models would be normal.

### Steps to reproduce

Step 1: Export some palette in Portal 2/Aperture Tag.

Step 2: Open the editor.

Step 3: Open the palette and place an item.

### Logs and Reports

```shell
Nothing.
```

### Additional information

1: I'm using the UCP's from CardAndGames_YT, Flashie/Radelite, Enderek0, Baguettery, Konclans and Areng.

2: The bug occurs in Portal 2 and Aperture Tag, absolutely nothing changes.

3: I've tried uninstalling and reinstalling but nothing happens.

4: The UCP's mentioned above are on discord, as I think it's a more reliable source.

5:Items that contain variations also do not appear, such as buttons, cubes, glasses and flizzers.

![Problema Bee 2](https://user-images.githubusercontent.com/88097966/166160478-d0d350d7-4a3c-46ac-b1f0-9824e6783e35.png)
![Problema Bee 3](https://user-images.githubusercontent.com/88097966/166160480-3cd2fb26-230d-479e-be9b-40c53a8101c1.png)

These are all custom items.
![image](https://user-images.githubusercontent.com/88097966/166160765-b02136d2-9a15-4642-ac4e-03fb7834c98d.png)

The chamber didn't build, forgot to mention.

**Comment by LautaroL20** [comment]
In order to solve this issue, you will have to do the following:

1.  Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have installed the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. If after following these steps solved your issue, make sure to save this in a text file in case you get similar issues with BEEmod in the future.

9.  Happy mapmaking!

**Comment by train66453574657453456345** [comment]
<img width="319" height="269" alt="Image" src="https://github.com/user-attachments/assets/d94a1303-58a1-4a46-8bc2-ee4faf0d2359" />WHAT YOU CAN DO THAT HOW

**Comment by train66453574657453456345** [comment]
EXTRA MENU

**Comment by vrad-exe** [comment]
They edited the screenshot to add the BEE2 app's palette UI next to the in-game one, to show the missing icons. It's not possible to actually have multiple pages like this. Please stop replying to random issues with unrelated/nonsense posts.
