### ISSUE TITLE
add option to have potatos gun

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#418]
add a checkbox to have the potatos gun instead of the regular one for all styles. would be for PTI maps where potatos may appear in a different style in a parallel universe due to some other unseen event triggering it.

**Comment by LautaroL20** [comment]
Nice suggestion!

**Comment by TeamSpen210** [comment]
There's 2 problems with this:

* How would it work with GLaDOS voicelines? That would make two copies of GLaDOS exist at the same time, which they really should react to. I could make PoTaTOS play the Caroline-reaction lines, but that'd be the same for all the dialog - making it very repetitive.
* It won't work in Aperture Tag or Portal 1 style, since they use different portalgun models.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Could it work in "None - voices" at least? Perhaps with a small warning that says "Only works in clean / Overgrown / Old apertures - Quiet only", into the "Export Options" from Bee 2.4?

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 

make it not work in portal 1 and tag

for lines make it play certain ones depending upon style such as the caroline lines in the 70's and 80's and the Wheatley lines for Wheatley. for clean and others make it silent.

**Comment by LautaroL20** [comment]
@TeamSpen210, What do you think of the elli´s suggestion?

**Comment by Luke18033** [comment]
@TeamSpen210 This could be a stylevar available on all styles except Portal 1. There's probablyalso a way you could disable it on Aperture Tag.

**Comment by ZombiePwner1** [comment]
Potatos gun in AT is impossible to get due to the different portal gun model.

**Comment by ZombiePwner1** [comment]
Potatos is possible to have in coop since I've tried it myself.
