### ISSUE TITLE
Make quarter tiles able to act as gridded walls / add gridded walls back.

### ISSUE THREAD

**Issue by Issuecreator1** [BEEmod/BEE2-items#4227]
### Description of the feature

Make the "**quarter tile**" item, if a ton are placed on the same voxel, turn surfaces they are placed on gridded _or_ add back the removed "**gridded wall**".

### Why should this be implemented

The originial "**gridded wall**" item has been removed from the newest version.
By making quarter tiles able to turn surfaces gridded there would be no need to add the original item back.

### Additional information

![Gridded wall replicated by quarter tile works perfectly](https://user-images.githubusercontent.com/113119801/189150530-6c713299-8598-478a-946e-6cab33e6ae39.jpg)
This is a picture of quarter tiles where I attempt to use them as a gridded wall.
I also added a piston platform for comparison, as that uses a gridded texture, to show what I would have expected quarter tiles to look like.

**Comment by Luke18033** [comment]
The gridded wall was removed because it isn't needed anymore, it was a hack to force the 4x4 tiles to appear in certain places around items where it couldn't be done automatically, which it now can be. I'm not sure what would really be the purpose of being able to set a random tile to use 4x4 textures.

Piston platforms always using 4x4 textures is [a bug](https://github.com/BEEmod/BEE2-items/issues/3774), they should also be using the largest tile sizes that can fit.

**Comment by HeimlichLaboratories** [comment]
Actually, using the 4x4 tile texture can be useful as a secondary surface marker. I always found having the same marker texture for two different things to look bad. I did this in one of my latest maps (overgrown chamber 8) - I used the surface marker for the autoportal wall and used the 4x4 tile wall for the place where the energy pellet hits.
