### ISSUE TITLE
Readdition of the BTS style as a seperate package.

### ISSUE THREAD

**Issue by CharlesHere0** [BEEmod/BEE2-items#4236]
### Description of the feature

Im suggesting BTS style to be re-added as a seperate package. BTS is a great style. It may be buggy, but it was very useful. It serverd its purpose of style.

### Why should this be implemented

BTS style was great, every time i playtested a map of mine, i enjoyed every second of going through a BTS styled puzzle. It just feels special, doesn't look too repetitive unlike other styles. It fits perfectly with puzzle elements like: Conveyor belt, diversity vent, and many more. 

### Additional information

I liked the BTS style so much, i tried porting it to the newest version of beemod. As you propably guessed, i failed miserably.

**Comment by TeamSpen210** [comment]
The BTS style already was a seperate package, this doesn't solve any of the problems it has.

**Comment by CharlesHere0** [comment]
> The BTS style already was a seperate package, this doesn't solve any of the problems it has.

Well, i ment for it to be re-added in any way possible.

**Comment by FrozenDragon0** [comment]
> > The BTS style already was a seperate package, this doesn't solve any of the problems it has.
> 
> Well, i ment for it to be re-added in any way possible.

BTS Isn't coming back, it was removed for a reason.

**Comment by HeimlichLaboratories** [comment]
BTS isn't a very good style, and it is repetitive, in fact it's much more noticeable in this style than in test chambers because BTS isn't supposed to be.

BTS was just your regular blocky test chamber with concrete textures and a few style changes. As stated in the FAQ, the more moving parts you added, the more apparent it became that it was just a puzzlemaker retexture.

BTS wasn't onlt removed because of bugs.
