### ISSUE TITLE
New Style Idea: The 1990s

### ISSUE THREAD

**Issue by TheDarkBomber** [BEEmod/BEE2-items#577]
The 1990s is clean style, with some 1970s-1980s elements and textures thrown into the mix.
Vactubes would be 1970s Vactubes. Modern elements like cubes, light strips, lasers, and turrets, would be Clean Style. Aerial Faith Plates are no longer gel, but look old. (like the top has been taken off). There would be elevators, but the elevator room is a large box and the elev videos would be on small screens on a catwalk going straight into the entry corridor. There are 3 types of entry:
- Corridor: Just going straight into a corridor past some decorations
- Lobby: Going into a lobby that welcomes you into the chamber
- Right Turn: Going into a corridor with a right turn.

And 3 types of exit:
- Corridor: A simple corridor leading into the exit elevator room.
- Stairs: Go down some stairs into the exit elevator room.
- No Door: A corridor leading into the exit elevator room with no door at the end.

The Exit Elevator Room will be just like the entry elevator room.
Fizzlers would be modern.
The Recommended Voice Pack would be Caroline or Announcer (Apoc)
The Recommended Skybox would be Clean skybox.
I'll leave you to decide the rest.

:+1::+1::+1:

**Comment by CrashingScience** [comment]
Portal 1 style is set in 1990s

**Comment by TheReviewers** [comment]
@CrashingScience No it isnt...

**Comment by CrashingScience** [comment]
It is. Cave tells aperture to start building glados mid 80's, he dies late
80's after they have filled the salt mines with test spheres. The test
shafts were sealed off and fhe facility above was built. Glados was
finished in 1998 and on bring your daughter to work day she was activated
and killed everyone. However this went unnoticed because very soon
afterwards the combine invaded.

**Comment by TheDarkBomber** [comment]
@CrashingScience 

This would be before 1998.

(1990-1997)

**Comment by TheDarkBomber** [comment]
This would be in the Old Aperture section of the style selector, and the door model would be the same as Clean Door Model, but a different texture.

**Comment by BenVlodgi** [comment]
I've seen suggestions for 90s style chambers. But really if you want a new style, it needs to be more than a mashup of two other styles. It needs new resources, it needs a reason to exist.

**Comment by TheDarkBomber** [comment]
@BenVlodgi 

It has a reason to exist. It is the transition between 1980s and Portal 1. And it isn't just a mashup of two other styles. It has completely different exit and entry rooms. And it can have new resources.

**Comment by BenVlodgi** [comment]
People can spin up ideas all day, but I'd like to see implemented in a chamber first.

**Comment by TheDarkBomber** [comment]
I can't, I'm suggesting this style.

**Comment by TheDarkBomber** [comment]
I can't implement it into a chamber.

**Comment by Luke18033** [comment]
@TheDarkBomber Doors should be square, Old Aperture-like doors, using the modern door design. 1990s chambers shouldn't be located in testing spheres, but I'm not sure where they should be.

**Comment by Luke18033** [comment]
So, is this happening? If not, then this should be closed.

**Comment by TheDarkBomber** [comment]
Don't close an issue just because it is inactive and unconfirmed.

**Comment by Byzarru** [comment]
I've talked about an F-Stop style on Gitter that could potentially take place in the 90s. It is based on the early concept art from Portal 2 back when the game was F-Stop. Judging from the images, it seems to be a mix of Old Aperture and Portal 1 styles. 

Here's a summary of the notes from Gitter:
* "F-STOP" style (which really can't be confirmed)
* A lot of the assets would probably use P1 style, as indicated by the cube and door style
* That button in the last screenshot, there's actually somewhat similar skins for the buttons actually.
* It looks like it could be the missing link between 80s and Portal
* F-Stop would be a more appropriate name, as it's taken from old concept art and promotional material
* Antlines are wires except for one of the arts ... Where it's a red line
* Both [this and Beta] could appear in a "Pre-Release" category of the style chooser
* Observation rooms look like they belong in an operation theatre
* Actually, since BP style is based on P1, and so would this style really
* BP, P1, and F-Stop should go in a P1 style section
* The only problem is that we don't have any of the textures, models or any other assets that existed in alpha.
* I'm not finding anything like fizzlers
* Pistons are in wide use
* Fizzlers would be Portal 1 style. ...  At least, the particles.
* [TDB] already suggested a 1990s style.
* Indicator signs would be red lights
* This is F-Stop style.
* Based mostly on concept arts

**Comment by rms1229** [comment]
Perhaps it could be based off the 2005 beta? (There's a video of it on Bolloxed's channel.) Specifically, the actual test chambers. It does look to me like a proto-Portal(which is good, because it is.). They also seem more "built-in", like Portal 1's chambers. I think Portal 2 might have retconned it, but Portal 1's Test chambers all seemed to be part of the building, rather than giant structures suspended in air. Hallways physically connect the observation rooms, after all. The 2005 beta has that too, but it also looks a lot older. It really does fit to me. If this isn't implemented as its 1990s, I hope it gets implemented in some way. Maybe ask Bolloxed where he got the beta or something?(I know nothing about coding this stuff.)

**Comment by BenVlodgi** [comment]
If this style should be anything, it should be a transition from old aperture to portal 1 aperture

**Comment by TeamSpen210** [comment]
I usually consider P1 about 1990s style. 80s is really quite proto-Clean, and I build items based more on their modern versions.

**Comment by BenVlodgi** [comment]
Or that, I'm down with 90s just being portal 1

**Comment by rms1229** [comment]
To be fair, Portal 2 basically retconned Portal 1 style by having the destroyed chambers clearly not look the same. After all, the black surfaces in P1 were metal and cubic rather than panels(There was even a part where some of the cubes were on the ground and could be pushed. One of the Ratman dens, I think.), and the whole facility felt like an actual building, with the chambers built out of metal and concrete, as opposed to test chambers suspended in the air. That said, again, I'd love it if the 2005 demo got a style, as it looks cool. Eventually. To be honest, I'm excited for all the things to come.

**Comment by TeamSpen210** [comment]
I reconcile the changes by supposing that there are multiple duplicate test tracks. The chambers you went in in Portal 1 are different buildings to the ones in Portal 2. The P2 ones were built later, with the new panel tech, and improved/new chamber layouts. If you pay attention, the location you pick up the Dual Portal Device is actually the fire pit room - it implies another test subject went through there, and died, dropping it.

**Comment by rms1229** [comment]
I think it's just mostly a retcon. Just like with the elevators and GLaDOS. I think if they wanted the Portal 1 look to be canon, they'd have made the destroyed chambers look like Portal 1 ones and had GLaDOS pull out the metal and slide panels in as the tests went on in order to make the new design. The new elevators don't require too much explanation if you just say the old ones aren't working. They use the vactubes, after all. As it is, the new, updated look is basically supposed to be what the facility used to look like. To be honest, I don't see how any other test subjects could've been through without GLaDOS to test them. The Portal Gun probably had been sitting there all that time from a previous subject that didn't escape the fire pit. THe thing can survive up to 4000 degrees Kelvin, after all. I think the Portal 2 look is not a new era, persay, but a graphical update and retcon. There aren't that many parts in Portal 1 that outright depend on the look being the way it is. I guess the new chambers still have observation rooms anyway, and we never actually see if they are suspended. That or the rest of it collapsed into the massive freaking abyss below. I always explain the difference in behind the scenes areas as the P1 ones being things employees walked through, whereas most of P2's Behind the Scenes sections are spent in factories and the like. I talk too much don't I?

**Comment by IceTudor** [comment]
Huh, I actually thought about a logo for A.S. if adhesion gel would've existed, in the 90's, kinda like a mix of 80's and 2010 (P1). The logo is my profile pic for the moment.

**Comment by TeamSpen210** [comment]
80's is the modern logo.

**Comment by ZombiePwner1** [comment]
@IceTudor I do have a pump station textures for adhesion gel which i hope to use soon.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
this could be like 80s refurbished like during portal 1 glados could have recycled old testing spheres and could have added pistons button fizzlers HEPs ect

**Comment by Neightro** [comment]
The Valve Developer Wiki suggests that Art Therapy consists of unfinished chambers from around the '90s. It's fair to say that they are evidence of a retcon the P1 art style; if P1 was still canon, then the old, unfinished chambers would look like P1.

**Comment by Luke18033** [comment]
This is basically what Art Therapy is, we don't really want to add custom styles anyway.
