### ISSUE TITLE
Beta style

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#741]
This would make portal 2 look like it's beta during 2010.

![20160829072830_1](https://cloud.githubusercontent.com/assets/18079316/18037581/c4557646-6dba-11e6-8240-54366b990830.jpg)

Beta metal textures and portal 1 button.

![20160829073024_1](https://cloud.githubusercontent.com/assets/18079316/18037585/d3277e3a-6dba-11e6-8358-56130e297dca.jpg)

Beta light strips.

![20160829073122_1](https://cloud.githubusercontent.com/assets/18079316/18037586/dca83490-6dba-11e6-9a2c-191cac98629f.jpg)

Warm beta light strips and note the use of the P1 fizzler.

![20160829073134_1](https://cloud.githubusercontent.com/assets/18079316/18037587/ef5df11a-6dba-11e6-891e-ab3db011f440.jpg)

Beta cold light strips.

![20160829074049_1](https://cloud.githubusercontent.com/assets/18079316/18037646/fc4ed2da-6dbb-11e6-9cfb-4418de68f52f.jpg)

Green goo. Looks abit better. Look around the top left of the screen a beta faith plate.

![20160829074105_1](https://cloud.githubusercontent.com/assets/18079316/18037648/0a47d81e-6dbc-11e6-8a21-d36e75229571.jpg)

Little P1 observation room.

Note there is a beta version of the vactubes but i can't get it working.

**Comment by LautaroL20** [comment]
Nice suggestion, those wall beta textures looks interesting.

**Comment by ZombiePwner1** [comment]
There might not be alot of things that are changed but atleast a few things are different.

**Comment by TeamSpen210** [comment]
Good news for this, I found the ['Beta pack'](http://www.myapertureinnovations.com/filedb/viewfile.php?id=79) of earlier materials made by ReepBlue.

**Comment by ZombiePwner1** [comment]
Well please add this type of style since it's my type of style for clean.

**Comment by Luke18033** [comment]
The beta vactubes look so much better.

**Comment by ZombiePwner1** [comment]
indeed

**Comment by Luke18033** [comment]
As seen in some unused instances, Laserfields and Paint Fizzlers used the standard blue P1 emitter. This doesn't look very good, so they should use the custom emitters that the P1 versions use. Laserfields likely also had a different texture in the beta, as indicated by the overly scaled texture in the instance, but unfortunately we don't know what it looks like since laserfields never appeared in the trailers.

@ZombiePwner1 - Where did you get the beta portal gun skin? It wasn't included in the betapack.

**Comment by ZombiePwner1** [comment]
@Luke18033 I found it on a website.

**Comment by Luke18033** [comment]
While making beta maps in Hammer, I realized one problem with this style: Beta light strips have to embed slightly, which wouldn't work very well in PeTI. They'd have to use the same compiler logic as P1 light holes, embedding only when possible.

**Comment by TeamSpen210** [comment]
Clean strips also 'need' to embed, but instead they sit on top 0.0001 units.

**Comment by ZombiePwner1** [comment]
@LautaroL20  @TeamSpen210  @Luke18033 It turns out i seem to have actually found a beta catwalk model left over in the game files by valve. 
![20170519191000_1](https://cloud.githubusercontent.com/assets/18079316/26245813/7ebbda3e-3cc8-11e7-837f-e6b05592a149.jpg)

**Comment by LautaroL20** [comment]
Interesting.

**Comment by iEnderMan06** [comment]
@ZombiePwner1 Looks to me like the one that accepts gel which was used in the 'lair chase' sequence...

**Comment by Luke18033** [comment]
@ZombiePwner1 We'd want to use the beta catwalks you posted [here](http://steamcommunity.com/sharedfiles/filedetails/?id=928539012).

@iEnderMan06, for that they just add a brush on top of the catwalk. It's not a separate model.

**Comment by ZombiePwner1** [comment]
@LautaroL20 @TeamSpen210 @Luke18033 Only problem is we can't really use it since this is the only beta catwalk model in the game files we'd need someone to make custom models for the rest of the pieces.

**Comment by Luke18033** [comment]
Didn't somebody already make them...?

**Comment by Luke18033** [comment]
Also that model only comes in a straight variant.

**Comment by ZombiePwner1** [comment]
@Luke18033 Yes and that's the problem since there is no end_caps and such. And as for my beta catwalk models it's actually a VTF file that replaces the catwalk grating texture with the beta one.

**Comment by Luke18033** [comment]
We'd add that as a skin of the rusted catwalk models.

**Comment by ZombiePwner1** [comment]
@Luke18033 Heres a screenshot of the rusted catwalk models with the texture.

![20170520073747_1](https://cloud.githubusercontent.com/assets/18079316/26270640/3e920bce-3d2f-11e7-83f8-406edb367811.jpg)

**Comment by Luke18033** [comment]
That's not what I meant. See the BEE2.4 triple wallpipe models.

**Comment by Luke18033** [comment]
Skin 0 is a version of the vanilla model with the inside textured. Skin 1 is a rusty version that isn't modeled inside. Skin 2 is a rusty version which is textured inside. We'd do something similar for the catwalks - Skin 0 would be rusted, Skin 1 beta and Skin 2 rusted beta (if necessary).

**Comment by ZombiePwner1** [comment]
@Luke18033 Well just try to be more specific next time since it's abit hard for me to understand things.

**Comment by Luke18033** [comment]
Okay.

**Comment by IceTudor** [comment]
[ ] What about the round beta laser catchers? Those look cool. 
[ ] Same with the relays
[ ] The large faith plate could be like the small one, only a whole voxel big panel instead of a half voxel big one.
[ ] The laserfields could be just like 1980's old aperture's as the actual "field", the emitter would be the P2 beta fizzler emitter. 
[ ] We could have the other fields as more clean versions, without the weird web-like structures that the fizzlers have, almost like a more uniform and transparent version of the physler.
[ ] Perhaps portals could have r_portal_use_dlights on as a stylevar, since that's what we see at near-beta/e3.
[ ] Portals could have a more liquidy sound, as in the actual beta and e3 trailer.
[ ] Maybe the old test complete sound? (God, I love the look, sound and feel of P2 beta)
[ ] GLaDOS (Apoc), Science is fun/Reconstructing science and P1 Skybox could work as suggested, Elev vid not sure.

**Comment by ZombiePwner1** [comment]
@IceTudor I know how this style will turn out since i currently have half of the beta content on my game already.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 I already have some of the beta models since i'm friends with 2 guys who are in love with portal 2's beta and are remaking beta content.

**Comment by IceTudor** [comment]
Huh, lemme just change my comment, I'm gonna make it a checklist for models.

**Comment by Endermage77** [comment]
@IceTudor: I believe you mean music, not themes.

**Comment by Luke18033** [comment]
We've basically decided now that there won't be any recreated beta content in the default pack. This could be implemented as a UCP, but otherwise I don't think it's happening.
