### ISSUE TITLE
[PRL22 Visual Bug] A "Mysterious Radioactive Plant" is living on DeadlyGoo, when debris is enabled.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#842]
![20160915121002_1](https://cloud.githubusercontent.com/assets/12244376/18626793/762d288c-7e2d-11e6-8b6e-e22f3c3304ca.jpg)

**Comment by ZombiePwner1** [comment]
This mean't to happen.

**Comment by LautaroL20** [comment]
Thats why i am reporting the bug........

**Comment by TeamSpen210** [comment]
Ok, true :). I'll remove the plants from the debris variants.

**Comment by ZombiePwner1** [comment]
:( I like that plant.

**Comment by cartman1337** [comment]
Plants should be among debris. There are all sorts of plants, life and poisons out there. As Ian Malcolm (Jurassic Park) said; "life finds a way". The idea behind Overgrown style is for it to look like something that has been left alone for hundreds of years. In that time, it wouldn't be against nature to find a way to live and grow in substances that are poisonous to humans. In fact, many plants are already poisonous, and produce liquids that are deadly to humans.

At the very least, add plants as a choice instead of removing it completely.

**Comment by LautaroL20** [comment]
What an explanation O_O, well my point of view is that it still does not make sense, but in order to please all tastes seen here, as you said, it would be good to include an aditional stylevar for people who find that "Plants" living on acid have a logic.
