### ISSUE TITLE
Mid chamber elevator

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#942]
new item: mid chamber elevator

some test chambers in both portal and portal 2 and mel where two small test chambers in one map that had an elevator in the map between them that transitioned you between tests. this was seen a lot in mel.

implement this item if you can,

my idea is a door with a world portal that would take you to an elevator instance that would take you up one floor to another door with a world portal back to the second test chamber in the map.

also you could create an elevator that could be placed in the test chamber, this could create some very interesting tests...

**Comment by Konclan** [comment]
I do like the item idea; However, it may confuse players thinking it's the end of the chamber. There are many different ways to transition from one puzzle to another and sometimes it is just best to make multiple chambers instead of one giant one. This is a good idea in theory but may not work well in a chamber.

**Comment by ellingtonvengaboysmuseum** [comment]
this would be useful for very small tests that where completely enclosed, or if you wanted to have a elevator in the test chamber it would take you up through the ceiling to the exit node. in a wheatley test chamber this could create a really unique transport to enter the next test chamber above the first one that could be seen through the ceiling of the first test chamber of the floor of the top test chamber.

**Comment by Konclan** [comment]
How would this item react in coop, I know there are items like chamber locks that are designed for singleplayer but an item like this could cause major issues.

**Comment by Luke18033** [comment]
Portal 2 actually only has this once, which is when you enter the conversion testing sphere. Portal 1 uses it in some of the earlier maps.

**Comment by ZombiePwner1** [comment]
This item definitely would not work in coop

**Comment by xDadiKx** [comment]
I was thinking of this idea for months, but I thought it would never work.

**Comment by Jadeygaming** [comment]
For Co-op just make 2 elevators.

**Comment by TeamSpen210** [comment]
This isn't really needed. First it'd be a massive item - at least about 20 blocks tall. Secondly it won't make sense in Old Aperture or BTS styles - they don't even have elevators like this. This is what the chamberlock and checkpoint items are intended for. An actual elevator item might be more interesting, where it allows the player to move up and down a shaft.

**Comment by Konclan** [comment]
I mean that's mostly what a piston plateform is for, However maybe we need a worldportal chamberlock. A door you hook up to another door but it still works like a chamber lock. This way people can stack chambers on top of eachother but not have to create a makeshift chamberlock for when you adventually do add worldportal doors back.

**Comment by TeamSpen210** [comment]
The 'sphere' variant of the Worldportal Door works exactly like that.

**Comment by Endermage77** [comment]
I'm fairly certain that the standard Old Aperture lifts would work for a Mid-Chamber Elevator.

But I think I can see how this would work:
1. The item in the editor would appear as a normal worldportal door. albeit with, perhaps, 5x5x5 space instead of 3x3x3.
2. Inside, there would be the usual elevator station, and when the elevator is entered, it goes up, passes through a worldportal to a shortish elevator section outside of the map, and then through another one to arrive at the destination.
3. To save on worldportals, any worldportals generated by elevators would be closed until a player enters the elevator space, and would close when the elevator space is exited.
4. To be compatible with coop, the elevator would go back down to its normal position after being ridden, so that multiple people may use the same elevator.

If the elevator ride section outside the map poses a problem, the elevator can still simply pass through one worldportal without the ride section.

An optional variant, probably with Start Open or Start Reversed, would place a fizzler over the entrance/exit so that player portals do not cause rendering errors when riding the lift.
The elevator would also have the normal variants that worldportal doors have had in the past.

**Comment by TeamSpen210** [comment]
You can't have moving things like that through portals.

**Comment by V0pT** [comment]
I don't think having it use worldportals would work, as PeTI already uses a bunch for entry/exit and player portals, and having any more would probably cause a log of lag and rendering issues. In Co-op it would probably totally break the game. Maybe having it as an adjustable service lift like in one of the Wheatley tests in-game would work, at least in the BTS style.

   I've also seen a lot of workshop maps (most made by skyferret) that use the clean style elevator (without the elevator room) mid-chamber. This could probably work in clean/wheatley/bts styles pretty easily, and old aperture could just swap to the old lift design. Not sure about portal 1 though...

**Comment by King0191** [comment]
Some Idea Tossing here, don't mind me: 
I don't think "Thinking it's the end of the chamber" is an issue until we add seamless elevators (where there's no entrance/exit hallway.) As they'd notice the lack of a hallway. 

And sure, while it may appear as a big object. I think it'd be worth it. In the long run if we add these things. People would be happy with the inclusion and want to use them for, whatever they end up using them for. They'd find way around entity limits or size limitations. It's what they kinda do best.

**Comment by King0191** [comment]
As for Co-Op. Why not have a `Start Reversed`
That makes sure both players are inside the elevator before going up?

It eliminates the issue, and if we split them up, we can still have One-Person Elevators for those occasions. 

World Portals wouldn't be necessary. We could do something similar to how the Checkpoints or Chamberlocks are where it requires a ton of empty space to build the area. We did it with the Co-Op seperater and checkpoints. I really do not see why it can't be done here. Sure there's the issue of varying sizes. But I could see this working.

Perhaps for Old Aperture. We could remove the big old platform and catwalks leading up to the elevator, just leaving the Elevator in a room with some grating floor and perhaps some goop under said grating floor. This would make it around as small as a P1 Elevator room, saving more space in a chamber. But also allowing us to have styled variants.

-Start Open: determines if the doors are... open on map start. 
-Start Reversed: Adds a Fizzler (Able to be changed by connecting a certain fizzler type to it? Or just an absolute fizzler if necessary?)

Perhaps use two elevator objects and connect them like a Vac-Tube to create a connection? No curves allowed, of course.

It may be a bit difficult to work out all the kinks. But it'll make people happy.

**Comment by Luke18033** [comment]
So mid-chamber elevators are something we're still considering? Not sure exactly how we'd want to implement it, does the elevator connect directly to the chamber? Then it takes up a massive amount of space, so do we use worldportals? Does it have corridors? How does it work with music and voicelines? Not to mention that most people expect the elevator to be the end of the map in Portal 2, especially in workshop maps and *especially* in Puzzlemaker maps. If you want to make a multi-chamber map, seems like it'd make more sense to just use chamberlocks, or if you're out of space, worldportal doors once those are added.

**Comment by Konclan** [comment]
I was assuming its just an elevator that sticks slightly out of the floor and removed all the normal entrance stuff. Would probably be complicated to implement though since its relying on people to delete the entrance. Although if people place it in there level we could just skip the normal entrance item and it just gets ignored.

**Comment by Luke18033** [comment]
Huh? This suggestion was to add elevators to go between multiple chambers in multi-chamber maps, you seem to be interpreting it as a freestanding elevator.

**Comment by Konclan** [comment]
Oh, is #2565 a duplicate then?

**Comment by Luke18033** [comment]
It would be, although that suggestion is better so I'd close this one instead.
