### ISSUE TITLE
Dynamically adjust P1 & Retro Exit Door signs

### ISSUE THREAD

**Issue by LogicDeLuxe** [BEEmod/BEE2-items#969]
In the editor, if the space above the exit door is occupied, the sign moves around as it should. In game, the sign is still above the door. If placed under the ceiling, only the bottom of the frame visible.

**Comment by cartman1337** [comment]
The same is also the case in old Aperture styles.

**Comment by ZombiePwner1** [comment]
Can you show a picture by any chance?

**Comment by TeamSpen210** [comment]
Place an item above the exit door, and you'll see the sign move to the side of the door in the editor.

**Comment by cartman1337** [comment]
I previously opened an issue about the doors being missing on the exit corridors in the 70s (or was it 80s?) chambers, when there were no inputs on the exit, but it got closed as being intentional, reflecting Apperture's budget cuts in the time period. However, the pictures I provided then also serves as proof that the exit sign is not moved to the side in this mode; there is no signage visible when the roof is just above the exit. Here are pictures from two different Old Apperture styles:
![old1](http://i.imgur.com/LDCxRDS.jpg)
![old2](http://i.imgur.com/X5qHi3O.jpg)

**Comment by LogicDeLuxe** [comment]
How it looks in the editor:
![editor](https://cloud.githubusercontent.com/assets/6632046/19963682/c1b042e0-a1bd-11e6-8d28-b863620086b9.jpg)

And this is the same place in game. On the top exit doors, only the bottom of the frame is visible:
![ingame](https://cloud.githubusercontent.com/assets/6632046/19963691/cf357336-a1bd-11e6-9697-4a62a72901ff.jpg)

You can only see the complete sign with noclip:
![noclip](https://cloud.githubusercontent.com/assets/6632046/19963700/dadbf53e-a1bd-11e6-81eb-d2aef22cca32.jpg)

**Comment by Luke18033** [comment]
With the switch to the new tiling system, this now causes a leak if the door is below a solid block since the sign ends up out of bounds.
